// Code generated by go run ./internal/tools/toolgen; DO NOT EDIT.

package email

import (
	"context"
	"fmt"

	"github.com/CherryHQ/stella/pkg/toolmeta"
	"github.com/CherryHQ/stella/pkg/tools"
)

// ToolPrefix is the family every generated email tool name starts with.
const ToolPrefix = "email"

// ActionTool describes one generated tool: an exact schema bound to one action.
type ActionTool = toolmeta.ActionTool

// ActionTools lists every generated tool in a stable order.
func ActionTools() []ActionTool {
	return []ActionTool{
		{Name: "email__account_list", PluginID: "system/email", Namespace: "email", LocalName: "account_list", Family: "email", Action: "account_list", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {},
  "type": "object"
}`},
		{Name: "email__message_list", PluginID: "system/email", Namespace: "email", LocalName: "message_list", Family: "email", Action: "message_list", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "account": {
      "type": "string"
    },
    "before": {
      "format": "date",
      "type": "string"
    },
    "folder": {
      "default": "INBOX",
      "type": "string"
    },
    "from": {
      "type": "string"
    },
    "limit": {
      "default": 20,
      "description": "Maximum envelopes to return.",
      "maximum": 100,
      "minimum": 1,
      "type": "integer"
    },
    "since": {
      "format": "date",
      "type": "string"
    },
    "subject": {
      "type": "string"
    },
    "unread": {
      "type": "boolean"
    }
  },
  "type": "object"
}`},
		{Name: "email__message_read", PluginID: "system/email", Namespace: "email", LocalName: "message_read", Family: "email", Action: "message_read", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "account": {
      "type": "string"
    },
    "folder": {
      "default": "INBOX",
      "type": "string"
    },
    "uid": {
      "maximum": 4294967295,
      "minimum": 1,
      "type": "integer"
    }
  },
  "required": [
    "uid"
  ],
  "type": "object"
}`},
		{Name: "email__message_send", PluginID: "system/email", Namespace: "email", LocalName: "message_send", Family: "email", Action: "message_send", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "account": {
      "type": "string"
    },
    "bcc": {
      "items": {
        "minLength": 1,
        "type": "string"
      },
      "type": "array"
    },
    "body": {
      "minLength": 1,
      "type": "string"
    },
    "cc": {
      "items": {
        "minLength": 1,
        "type": "string"
      },
      "type": "array"
    },
    "from": {
      "type": "string"
    },
    "html": {
      "type": "boolean"
    },
    "idempotency_key": {
      "description": "Optional for HTTP clients; required by the native email tool to suppress duplicate sends.",
      "type": "string"
    },
    "in_reply_to": {
      "type": "string"
    },
    "reply_to": {
      "type": "string"
    },
    "subject": {
      "minLength": 1,
      "type": "string"
    },
    "to": {
      "items": {
        "minLength": 1,
        "type": "string"
      },
      "minItems": 1,
      "type": "array"
    }
  },
  "required": [
    "body",
    "idempotency_key",
    "subject",
    "to"
  ],
  "type": "object"
}`},
	}
}

// ToolNames lists every generated tool name, for callers that gate on names.
func ToolNames() []string {
	names := make([]string, 0, len(ActionTools()))
	for _, spec := range ActionTools() {
		names = append(names, spec.Name)
	}
	return names
}

type Handler interface {
	AccountList(context.Context, AccountListInput) (any, error)
	MessageList(context.Context, MessageListInput) (any, error)
	MessageRead(context.Context, MessageReadInput) (any, error)
	MessageSend(context.Context, MessageSendInput) (any, error)
}

type AccountListInput struct {
}

type MessageListInput struct {
	Account string `json:"account,omitempty"`
	Before  string `json:"before,omitempty"`
	Folder  string `json:"folder,omitempty"`
	From    string `json:"from,omitempty"`
	Limit   int    `json:"limit,omitempty"`
	Since   string `json:"since,omitempty"`
	Subject string `json:"subject,omitempty"`
	Unread  *bool  `json:"unread,omitempty"`
}

type MessageReadInput struct {
	Account string `json:"account,omitempty"`
	Folder  string `json:"folder,omitempty"`
	Uid     int    `json:"uid,omitempty"`
}

type MessageSendInput struct {
	Account        string `json:"account,omitempty"`
	Bcc            []any  `json:"bcc,omitempty"`
	Body           string `json:"body,omitempty"`
	Cc             []any  `json:"cc,omitempty"`
	From           string `json:"from,omitempty"`
	Html           *bool  `json:"html,omitempty"`
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	InReplyTo      string `json:"in_reply_to,omitempty"`
	ReplyTo        string `json:"reply_to,omitempty"`
	Subject        string `json:"subject,omitempty"`
	To             []any  `json:"to,omitempty"`
}

func Dispatch(ctx context.Context, h Handler, action string, args map[string]any) (any, error) {
	switch action {
	case "account_list":
		var in AccountListInput
		if err := tools.DecodeInputStrict(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.AccountList(ctx, in)
	case "message_list":
		var in MessageListInput
		if err := tools.DecodeInputStrict(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.MessageList(ctx, in)
	case "message_read":
		var in MessageReadInput
		if err := tools.DecodeInputStrict(args, &in, []string{"uid"}); err != nil {
			return nil, err
		}
		return h.MessageRead(ctx, in)
	case "message_send":
		var in MessageSendInput
		if err := tools.DecodeInputStrict(args, &in, []string{"body", "idempotency_key", "subject", "to"}); err != nil {
			return nil, err
		}
		return h.MessageSend(ctx, in)
	default:
		return nil, fmt.Errorf("unknown email action %q", action)
	}
}
