// Code generated by go run ./internal/tools/toolgen; DO NOT EDIT.

package mcp

import (
	"context"
	"fmt"

	"github.com/CherryHQ/stella/pkg/toolmeta"
	"github.com/CherryHQ/stella/pkg/tools"
)

// SettingsMcpToolPrefix is the family every generated settings_mcp tool name starts with.
const SettingsMcpToolPrefix = "settings_mcp"

// SettingsMcpActionTool describes one generated tool: an exact schema bound to one action.
type SettingsMcpActionTool = toolmeta.ActionTool

// SettingsMcpActionTools lists every generated tool in a stable order.
func SettingsMcpActionTools() []SettingsMcpActionTool {
	return []SettingsMcpActionTool{
		{Name: "settings_mcp_server_create", Family: "settings_mcp", Resource: "server", Action: "create", Description: "Register a no-auth MCP server in an authorized scope. Credentials must be configured in the Web UI.", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "scope": {
      "enum": [
        "user",
        "user_agent",
        "system",
        "system_agent"
      ],
      "type": "string"
    },
    "target_agent_id": {
      "description": "Optional Agent whose scoped registration is created.",
      "type": "string"
    },
    "transport": {
      "default": "streamable_http",
      "enum": [
        "streamable_http",
        "sse"
      ],
      "type": "string"
    },
    "url": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "scope",
    "url"
  ],
  "type": "object"
}`},
		{Name: "settings_mcp_server_delete", Family: "settings_mcp", Resource: "server", Action: "delete", Description: "Delete an MCP registration using the version from settings_mcp_server_get. This refuses a stale version.", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "expected_version": {
      "description": "Opaque version returned by settings_mcp_server_get.",
      "minLength": 1,
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "scope": {
      "default": "user",
      "enum": [
        "user",
        "user_agent",
        "system",
        "system_agent"
      ],
      "type": "string"
    },
    "target_agent_id": {
      "description": "Optional Agent whose scoped registration is deleted.",
      "type": "string"
    }
  },
  "required": [
    "expected_version",
    "id"
  ],
  "type": "object"
}`},
		{Name: "settings_mcp_server_get", Family: "settings_mcp", Resource: "server", Action: "get", Description: "Read one authorized MCP registration and its version. Bearer credentials are never returned.", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "scope": {
      "default": "user",
      "enum": [
        "user",
        "user_agent",
        "system",
        "system_agent"
      ],
      "type": "string"
    },
    "target_agent_id": {
      "description": "Optional Agent whose scoped registration is read.",
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "settings_mcp_server_list", Family: "settings_mcp", Resource: "server", Action: "list", Description: "List up to 50 MCP registrations in one authorized scope. Bearer credentials are never returned.", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "limit": {
      "default": 50,
      "description": "Maximum registrations to return before truncation.",
      "maximum": 50,
      "type": "integer"
    },
    "scope": {
      "default": "user",
      "enum": [
        "user",
        "user_agent",
        "system",
        "system_agent"
      ],
      "type": "string"
    },
    "target_agent_id": {
      "description": "Optional Agent whose scoped registrations are listed.",
      "type": "string"
    }
  },
  "type": "object"
}`},
		{Name: "settings_mcp_server_probe", Family: "settings_mcp", Resource: "server", Action: "probe", Description: "Probe one authorized MCP registration: connect, list its tools, and persist the result. A failed probe still returns the server with a redacted error status.", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "scope": {
      "default": "user",
      "enum": [
        "user",
        "user_agent",
        "system",
        "system_agent"
      ],
      "type": "string"
    },
    "target_agent_id": {
      "description": "Optional Agent whose scoped registration is probed.",
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "settings_mcp_server_update", Family: "settings_mcp", Resource: "server", Action: "update", Description: "Update safe MCP metadata using the version from settings_mcp_server_get. Bearer credentials and their scope cannot change here.", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "enabled": {
      "type": "boolean"
    },
    "expected_version": {
      "description": "Opaque version returned by settings_mcp_server_get.",
      "minLength": 1,
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "scope": {
      "enum": [
        "user",
        "user_agent",
        "system",
        "system_agent"
      ],
      "type": "string"
    },
    "target_agent_id": {
      "description": "Optional Agent whose scoped registration is updated.",
      "type": "string"
    },
    "transport": {
      "enum": [
        "streamable_http",
        "sse"
      ],
      "type": "string"
    },
    "url": {
      "type": "string"
    }
  },
  "required": [
    "expected_version",
    "id"
  ],
  "type": "object"
}`},
	}
}

// SettingsMcpToolNames lists every generated tool name, for callers that gate on names.
func SettingsMcpToolNames() []string {
	names := make([]string, 0, len(SettingsMcpActionTools()))
	for _, spec := range SettingsMcpActionTools() {
		names = append(names, spec.Name)
	}
	return names
}

type SettingsMcpHandler interface {
	Create(context.Context, SettingsMcpCreateInput) (any, error)
	Delete(context.Context, SettingsMcpDeleteInput) (any, error)
	Get(context.Context, SettingsMcpGetInput) (any, error)
	List(context.Context, SettingsMcpListInput) (any, error)
	Probe(context.Context, SettingsMcpProbeInput) (any, error)
	Update(context.Context, SettingsMcpUpdateInput) (any, error)
}

type SettingsMcpCreateInput struct {
	Name          string `json:"name,omitempty"`
	Scope         string `json:"scope,omitempty"`
	TargetAgentId string `json:"target_agent_id,omitempty"`
	Transport     string `json:"transport,omitempty"`
	Url           string `json:"url,omitempty"`
}

type SettingsMcpDeleteInput struct {
	ExpectedVersion string `json:"expected_version,omitempty"`
	Id              string `json:"id,omitempty"`
	Scope           string `json:"scope,omitempty"`
	TargetAgentId   string `json:"target_agent_id,omitempty"`
}

type SettingsMcpGetInput struct {
	Id            string `json:"id,omitempty"`
	Scope         string `json:"scope,omitempty"`
	TargetAgentId string `json:"target_agent_id,omitempty"`
}

type SettingsMcpListInput struct {
	Limit         int    `json:"limit,omitempty"`
	Scope         string `json:"scope,omitempty"`
	TargetAgentId string `json:"target_agent_id,omitempty"`
}

type SettingsMcpProbeInput struct {
	Id            string `json:"id,omitempty"`
	Scope         string `json:"scope,omitempty"`
	TargetAgentId string `json:"target_agent_id,omitempty"`
}

type SettingsMcpUpdateInput struct {
	Enabled         *bool  `json:"enabled,omitempty"`
	ExpectedVersion string `json:"expected_version,omitempty"`
	Id              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	Scope           string `json:"scope,omitempty"`
	TargetAgentId   string `json:"target_agent_id,omitempty"`
	Transport       string `json:"transport,omitempty"`
	Url             string `json:"url,omitempty"`
}

func SettingsMcpDispatch(ctx context.Context, h SettingsMcpHandler, action string, args map[string]any) (any, error) {
	switch action {
	case "create":
		var in SettingsMcpCreateInput
		if err := tools.DecodeInputStrict(args, &in, []string{"name", "scope", "url"}); err != nil {
			return nil, err
		}
		return h.Create(ctx, in)
	case "delete":
		var in SettingsMcpDeleteInput
		if err := tools.DecodeInputStrict(args, &in, []string{"expected_version", "id"}); err != nil {
			return nil, err
		}
		return h.Delete(ctx, in)
	case "get":
		var in SettingsMcpGetInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Get(ctx, in)
	case "list":
		var in SettingsMcpListInput
		if err := tools.DecodeInputStrict(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.List(ctx, in)
	case "probe":
		var in SettingsMcpProbeInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Probe(ctx, in)
	case "update":
		var in SettingsMcpUpdateInput
		if err := tools.DecodeInputStrict(args, &in, []string{"expected_version", "id"}); err != nil {
			return nil, err
		}
		return h.Update(ctx, in)
	default:
		return nil, fmt.Errorf("unknown settings_mcp action %q", action)
	}
}
