// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mcp_connection_state.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMCPConnectionStatesForConfigs = `-- name: ListMCPConnectionStatesForConfigs :many
SELECT id, config_id, credential_user_id, tools, status, status_error,
       probed_at, config_revision, created_at, updated_at
FROM mcp_connection_state
WHERE config_id = ANY($1::uuid[])
  AND (
      credential_user_id IS NULL
      OR credential_user_id = $2::uuid
  )
ORDER BY array_position($1::uuid[], config_id), credential_user_id NULLS FIRST, id
`

type ListMCPConnectionStatesForConfigsParams struct {
	ConfigIds        []string    `json:"config_ids"`
	CredentialUserID pgtype.Text `json:"credential_user_id"`
}

func (q *Queries) ListMCPConnectionStatesForConfigs(ctx context.Context, arg ListMCPConnectionStatesForConfigsParams) ([]McpConnectionState, error) {
	rows, err := q.db.Query(ctx, listMCPConnectionStatesForConfigs, arg.ConfigIds, arg.CredentialUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpConnectionState{}
	for rows.Next() {
		var i McpConnectionState
		if err := rows.Scan(
			&i.ID,
			&i.ConfigID,
			&i.CredentialUserID,
			&i.Tools,
			&i.Status,
			&i.StatusError,
			&i.ProbedAt,
			&i.ConfigRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMCPConfigRevision = `-- name: LockMCPConfigRevision :one
SELECT revision
FROM plugin_config
WHERE id = $1::uuid
FOR UPDATE
`

func (q *Queries) LockMCPConfigRevision(ctx context.Context, configID string) (int64, error) {
	row := q.db.QueryRow(ctx, lockMCPConfigRevision, configID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const upsertMCPConnectionState = `-- name: UpsertMCPConnectionState :one
INSERT INTO mcp_connection_state (
    config_id, credential_user_id, tools, status, status_error,
    probed_at, config_revision
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::jsonb,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (config_id, credential_user_id) DO UPDATE
SET tools = EXCLUDED.tools,
    status = EXCLUDED.status,
    status_error = EXCLUDED.status_error,
    probed_at = EXCLUDED.probed_at,
    config_revision = EXCLUDED.config_revision,
    updated_at = now()
RETURNING id, config_id, credential_user_id, tools, status, status_error,
          probed_at, config_revision, created_at, updated_at
`

type UpsertMCPConnectionStateParams struct {
	ConfigID         string             `json:"config_id"`
	CredentialUserID pgtype.Text        `json:"credential_user_id"`
	Tools            json.RawMessage    `json:"tools"`
	Status           string             `json:"status"`
	StatusError      string             `json:"status_error"`
	ProbedAt         pgtype.Timestamptz `json:"probed_at"`
	ConfigRevision   int64              `json:"config_revision"`
}

func (q *Queries) UpsertMCPConnectionState(ctx context.Context, arg UpsertMCPConnectionStateParams) (McpConnectionState, error) {
	row := q.db.QueryRow(ctx, upsertMCPConnectionState,
		arg.ConfigID,
		arg.CredentialUserID,
		arg.Tools,
		arg.Status,
		arg.StatusError,
		arg.ProbedAt,
		arg.ConfigRevision,
	)
	var i McpConnectionState
	err := row.Scan(
		&i.ID,
		&i.ConfigID,
		&i.CredentialUserID,
		&i.Tools,
		&i.Status,
		&i.StatusError,
		&i.ProbedAt,
		&i.ConfigRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
