// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Agent struct {
	ID                         string          `json:"id"`
	Name                       string          `json:"name"`
	Model                      string          `json:"model"`
	ModelThinking              string          `json:"model_thinking"`
	ModelStrong                string          `json:"model_strong"`
	ModelStrongThinking        string          `json:"model_strong_thinking"`
	ModelFast                  string          `json:"model_fast"`
	ModelFastThinking          string          `json:"model_fast_thinking"`
	SystemPrompt               string          `json:"system_prompt"`
	Soul                       string          `json:"soul"`
	Workspace                  string          `json:"workspace"`
	Sandbox                    json.RawMessage `json:"sandbox"`
	EnabledBuiltinSkills       json.RawMessage `json:"enabled_builtin_skills"`
	Scope                      string          `json:"scope"`
	CreatorID                  string          `json:"creator_id"`
	Enabled                    bool            `json:"enabled"`
	CreatedAt                  time.Time       `json:"created_at"`
	UpdatedAt                  time.Time       `json:"updated_at"`
	SystemSettingsToolsEnabled bool            `json:"system_settings_tools_enabled"`
}

type AgentGoal struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	AgentID            string             `json:"agent_id"`
	ProjectID          pgtype.Text        `json:"project_id"`
	ParentID           pgtype.Text        `json:"parent_id"`
	RootID             string             `json:"root_id"`
	Depth              int64              `json:"depth"`
	Position           int64              `json:"position"`
	Title              string             `json:"title"`
	Intent             string             `json:"intent"`
	Kind               string             `json:"kind"`
	Priority           string             `json:"priority"`
	Required           bool               `json:"required"`
	AcceptanceContract json.RawMessage    `json:"acceptance_contract"`
	ConvergencePolicy  json.RawMessage    `json:"convergence_policy"`
	ReviewPolicy       string             `json:"review_policy"`
	Lifecycle          string             `json:"lifecycle"`
	BlockReason        string             `json:"block_reason"`
	AcceptanceState    string             `json:"acceptance_state"`
	AcceptedOutput     pgtype.Text        `json:"accepted_output"`
	AcceptanceSeq      int64              `json:"acceptance_seq"`
	ActiveAttemptID    pgtype.Text        `json:"active_attempt_id"`
	AttemptCount       int64              `json:"attempt_count"`
	Context            json.RawMessage    `json:"context"`
	DispatchHint       json.RawMessage    `json:"dispatch_hint"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	AcceptedAt         pgtype.Timestamptz `json:"accepted_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	Plan               json.RawMessage    `json:"plan"`
	PlannedAt          pgtype.Timestamptz `json:"planned_at"`
	// Infrastructure-flaky retry count independent of business attempt budget.
	FlakyCount      int64       `json:"flaky_count"`
	BudgetBonus     int32       `json:"budget_bonus"`
	DoneReason      string      `json:"done_reason"`
	WorkflowID      pgtype.Text `json:"workflow_id"`
	WorkflowVersion pgtype.Int4 `json:"workflow_version"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
}

type AgentGoalAcceptanceEvent struct {
	ID                string          `json:"id"`
	GoalID            string          `json:"goal_id"`
	AttemptID         pgtype.Text     `json:"attempt_id"`
	Seq               int64           `json:"seq"`
	ItemID            string          `json:"item_id"`
	ItemKind          string          `json:"item_kind"`
	Result            string          `json:"result"`
	Command           string          `json:"command"`
	ExitCode          pgtype.Int8     `json:"exit_code"`
	CacheKey          string          `json:"cache_key"`
	Authority         string          `json:"authority"`
	ReviewerUserID    pgtype.Text     `json:"reviewer_user_id"`
	ReviewerAttemptID pgtype.Text     `json:"reviewer_attempt_id"`
	Rationale         string          `json:"rationale"`
	Scope             string          `json:"scope"`
	ScopeHash         string          `json:"scope_hash"`
	Detail            json.RawMessage `json:"detail"`
	CreatedAt         time.Time       `json:"created_at"`
}

type AgentGoalAttempt struct {
	ID              string             `json:"id"`
	GoalID          string             `json:"goal_id"`
	UserID          string             `json:"user_id"`
	AgentID         pgtype.Text        `json:"agent_id"`
	ExecutorAgentID pgtype.Text        `json:"executor_agent_id"`
	SessionID       string             `json:"session_id"`
	Purpose         string             `json:"purpose"`
	AttemptNo       int64              `json:"attempt_no"`
	Status          string             `json:"status"`
	InputContext    json.RawMessage    `json:"input_context"`
	Evidence        json.RawMessage    `json:"evidence"`
	Output          json.RawMessage    `json:"output"`
	Gaps            json.RawMessage    `json:"gaps"`
	Error           string             `json:"error"`
	HeartbeatAt     pgtype.Timestamptz `json:"heartbeat_at"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	WorkerID        string             `json:"worker_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	FailureClass    string             `json:"failure_class"`
	RepairRounds    int32              `json:"repair_rounds"`
	// Audit copy of legacy failure_class before responsibility-class migration.
	PreviousFailureClass string `json:"previous_failure_class"`
}

type AgentGoalEdge struct {
	GoalID       string             `json:"goal_id"`
	UpstreamID   string             `json:"upstream_id"`
	EdgeKind     string             `json:"edge_kind"`
	OnFailure    string             `json:"on_failure"`
	WaivedAt     pgtype.Timestamptz `json:"waived_at"`
	WaivedByUser pgtype.Text        `json:"waived_by_user"`
	WaiverReason string             `json:"waiver_reason"`
	CreatedAt    time.Time          `json:"created_at"`
}

type AgentGoalEvent struct {
	ID        string          `json:"id"`
	GoalID    string          `json:"goal_id"`
	AttemptID pgtype.Text     `json:"attempt_id"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type AgentLlmCall struct {
	ID                 string         `json:"id"`
	SessionID          string         `json:"session_id"`
	AgentID            string         `json:"agent_id"`
	Provider           string         `json:"provider"`
	Model              string         `json:"model"`
	UsageReported      bool           `json:"usage_reported"`
	InputTokens        pgtype.Int8    `json:"input_tokens"`
	OutputTokens       pgtype.Int8    `json:"output_tokens"`
	CacheReadTokens    pgtype.Int8    `json:"cache_read_tokens"`
	CacheWriteTokens   pgtype.Int8    `json:"cache_write_tokens"`
	CostUsd            pgtype.Numeric `json:"cost_usd"`
	DurationMs         int64          `json:"duration_ms"`
	TimeToFirstTokenMs pgtype.Int8    `json:"time_to_first_token_ms"`
	StopReason         string         `json:"stop_reason"`
	Error              string         `json:"error"`
	OccurredAt         time.Time      `json:"occurred_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	ReasoningTokens    pgtype.Int8    `json:"reasoning_tokens"`
}

type AgentProviderCredential struct {
	AgentID    string    `json:"agent_id"`
	ProviderID string    `json:"provider_id"`
	ApiKeyEnc  string    `json:"api_key_enc"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type AgentWorkflow struct {
	ID                 string          `json:"id"`
	OwnerKind          string          `json:"owner_kind"`
	UserID             pgtype.Text     `json:"user_id"`
	AgentID            pgtype.Text     `json:"agent_id"`
	Name               string          `json:"name"`
	Version            int32           `json:"version"`
	WorkflowKey        pgtype.Text     `json:"workflow_key"`
	Intent             string          `json:"intent"`
	AcceptanceContract json.RawMessage `json:"acceptance_contract"`
	ConvergencePolicy  json.RawMessage `json:"convergence_policy"`
	Inputs             json.RawMessage `json:"inputs"`
	PayloadFormat      string          `json:"payload_format"`
	Payload            json.RawMessage `json:"payload"`
	FullyFrozen        bool            `json:"fully_frozen"`
	SourceGoalID       pgtype.Text     `json:"source_goal_id"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type AgentWorkflowRun struct {
	ID              string          `json:"id"`
	WorkflowID      string          `json:"workflow_id"`
	WorkflowVersion int32           `json:"workflow_version"`
	IdempotencyKey  string          `json:"idempotency_key"`
	RootGoalID      pgtype.Text     `json:"root_goal_id"`
	Status          string          `json:"status"`
	Inputs          json.RawMessage `json:"inputs"`
	PlanHash        string          `json:"plan_hash"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AuthCredential struct {
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type AuthIdentity struct {
	ID              string          `json:"id"`
	UserID          string          `json:"user_id"`
	Provider        string          `json:"provider"`
	ProviderSubject string          `json:"provider_subject"`
	Email           string          `json:"email"`
	Name            string          `json:"name"`
	AvatarUrl       string          `json:"avatar_url"`
	RawClaims       json.RawMessage `json:"raw_claims"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type AuthPolicy struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Effect     string    `json:"effect"`
	Subjects   string    `json:"subjects"`
	Actions    string    `json:"actions"`
	Resources  string    `json:"resources"`
	Conditions string    `json:"conditions"`
	Priority   int64     `json:"priority"`
	IsSystem   bool      `json:"is_system"`
	Enabled    bool      `json:"enabled"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type AuthProvisionedUser struct {
	ID               string      `json:"id"`
	ExternalID       string      `json:"external_id"`
	UserID           string      `json:"user_id"`
	CreatedByUserID  pgtype.Text `json:"created_by_user_id"`
	CreatedByTokenID pgtype.Text `json:"created_by_token_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type AuthSession struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AuthUser struct {
	ID               string      `json:"id"`
	Email            string      `json:"email"`
	Name             string      `json:"name"`
	AvatarUrl        string      `json:"avatar_url"`
	Role             string      `json:"role"`
	IsActive         bool        `json:"is_active"`
	DefaultAgentID   pgtype.Text `json:"default_agent_id"`
	NotifyIdentityID pgtype.Text `json:"notify_identity_id"`
	AgePublicKey     string      `json:"age_public_key"`
	AgePrivateKey    string      `json:"age_private_key"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type AuthUserAgent struct {
	UserID  string `json:"user_id"`
	AgentID string `json:"agent_id"`
}

type AuthUserToken struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	TokenPrefix   string             `json:"token_prefix"`
	AutoGenerated bool               `json:"auto_generated"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RotatedAt     pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type Channel struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	AgentID   pgtype.Text `json:"agent_id"`
	Enabled   bool        `json:"enabled"`
	Config    string      `json:"config"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type ChannelAgent struct {
	ChannelID string    `json:"channel_id"`
	Platform  string    `json:"platform"`
	ChatID    string    `json:"chat_id"`
	AgentID   string    `json:"agent_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ChannelChatCommandReceipt struct {
	ID        string    `json:"id"`
	ChannelID string    `json:"channel_id"`
	ChatKey   string    `json:"chat_key"`
	MessageID string    `json:"message_id"`
	Command   string    `json:"command"`
	Binding   string    `json:"binding"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ChannelGroupMember struct {
	GroupID        string    `json:"group_id"`
	AgentID        string    `json:"agent_id"`
	ReplyChannelID string    `json:"reply_channel_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ChannelGuest struct {
	ID         string    `json:"id"`
	ChannelID  string    `json:"channel_id"`
	Platform   string    `json:"platform"`
	ExternalID string    `json:"external_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ChannelIdentity struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	Platform   string    `json:"platform"`
	ExternalID string    `json:"external_id"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CtxAgentMemory struct {
	UserID         string          `json:"user_id"`
	AgentID        string          `json:"agent_id"`
	Content        string          `json:"content"`
	Soul           string          `json:"soul"`
	Version        int64           `json:"version"`
	Constraints    json.RawMessage `json:"constraints"`
	ProfileEntries json.RawMessage `json:"profile_entries"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type CtxAgentMemoryChangelog struct {
	ID                  string      `json:"id"`
	UserID              string      `json:"user_id"`
	AgentID             string      `json:"agent_id"`
	SessionID           pgtype.Text `json:"session_id"`
	EntityID            pgtype.Text `json:"entity_id"`
	Scope               string      `json:"scope"`
	Action              string      `json:"action"`
	Source              string      `json:"source"`
	MemoryVersionBefore pgtype.Int8 `json:"memory_version_before"`
	MemoryVersionAfter  pgtype.Int8 `json:"memory_version_after"`
	BeforeText          pgtype.Text `json:"before_text"`
	AfterText           pgtype.Text `json:"after_text"`
	Metadata            pgtype.Text `json:"metadata"`
	CreatedAt           time.Time   `json:"created_at"`
}

type CtxAgentMemorySnapshot struct {
	SessionID string    `json:"session_id"`
	UserID    string    `json:"user_id"`
	AgentID   string    `json:"agent_id"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CtxConversation struct {
	ID                  string             `json:"id"`
	SessionID           string             `json:"session_id"`
	Title               pgtype.Text        `json:"title"`
	Channel             string             `json:"channel"`
	Kind                string             `json:"kind"`
	ProjectID           pgtype.Text        `json:"project_id"`
	Archived            bool               `json:"archived"`
	LastActive          time.Time          `json:"last_active"`
	BootstrappedAt      pgtype.Timestamptz `json:"bootstrapped_at"`
	AgentID             pgtype.Text        `json:"agent_id"`
	UserID              pgtype.Text        `json:"user_id"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	GroupID             pgtype.Text        `json:"group_id"`
	GuestID             pgtype.Text        `json:"guest_id"`
	LastTurnStartedAt   pgtype.Timestamptz `json:"last_turn_started_at"`
	LastTurnCompletedAt pgtype.Timestamptz `json:"last_turn_completed_at"`
	LastTurnResult      pgtype.Text        `json:"last_turn_result"`
	LastViewedAt        pgtype.Timestamptz `json:"last_viewed_at"`
}

type CtxGroupDispatch struct {
	ID               string             `json:"id"`
	GroupMessageID   string             `json:"group_message_id"`
	GroupID          string             `json:"group_id"`
	AgentID          string             `json:"agent_id"`
	ReplyChannelID   string             `json:"reply_channel_id"`
	Status           string             `json:"status"`
	AttemptCount     int64              `json:"attempt_count"`
	LeaseUntil       pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	LastError        string             `json:"last_error"`
	ResultMessageID  string             `json:"result_message_id"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	Kind             string             `json:"kind"`
	TriggerSeq       int64              `json:"trigger_seq"`
	HeldUpToSeq      pgtype.Int8        `json:"held_up_to_seq"`
	PublishStartedAt pgtype.Timestamptz `json:"publish_started_at"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

type CtxGroupIngestCursor struct {
	GroupID   string    `json:"group_id"`
	Pipeline  string    `json:"pipeline"`
	LastSeq   int64     `json:"last_seq"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CtxGroupMessage struct {
	ID                string             `json:"id"`
	GroupID           string             `json:"group_id"`
	Seq               int64              `json:"seq"`
	SourceChannelID   pgtype.Text        `json:"source_channel_id"`
	ActorType         string             `json:"actor_type"`
	ActorID           string             `json:"actor_id"`
	PlatformMessageID pgtype.Text        `json:"platform_message_id"`
	ReplyTo           pgtype.Text        `json:"reply_to"`
	PlatformTimestamp pgtype.Timestamptz `json:"platform_timestamp"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	Content           string             `json:"content"`
	Reasoning         string             `json:"reasoning"`
	AgentSessionID    string             `json:"agent_session_id"`
	CreatedAt         time.Time          `json:"created_at"`
	ContentBlocks     json.RawMessage    `json:"content_blocks"`
	DeliveryState     string             `json:"delivery_state"`
	ActorDisplayName  pgtype.Text        `json:"actor_display_name"`
}

type CtxGroupOutbox struct {
	ID             string             `json:"id"`
	GroupMessageID string             `json:"group_message_id"`
	GroupID        string             `json:"group_id"`
	Envelope       string             `json:"envelope"`
	Status         string             `json:"status"`
	AttemptCount   int64              `json:"attempt_count"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastError      string             `json:"last_error"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type CtxGroupState struct {
	ID                        string             `json:"id"`
	Platform                  string             `json:"platform"`
	PlatformGroupID           string             `json:"platform_group_id"`
	PlatformThreadID          string             `json:"platform_thread_id"`
	NextSeq                   int64              `json:"next_seq"`
	CreatedAt                 time.Time          `json:"created_at"`
	UpdatedAt                 time.Time          `json:"updated_at"`
	GroupName                 string             `json:"group_name"`
	CreatedByUserID           pgtype.Text        `json:"created_by_user_id"`
	AgentChainHardLimit       int32              `json:"agent_chain_hard_limit"`
	MaxAgentPostsPerMinute    int32              `json:"max_agent_posts_per_minute"`
	MaxRepliesPerHumanTrigger int32              `json:"max_replies_per_human_trigger"`
	HoldLimit                 int32              `json:"hold_limit"`
	NudgeAt                   pgtype.Timestamptz `json:"nudge_at"`
	NudgeCheckedAt            pgtype.Timestamptz `json:"nudge_checked_at"`
	NudgeStreakCount          int32              `json:"nudge_streak_count"`
}

type CtxItem struct {
	ConversationID string      `json:"conversation_id"`
	Ordinal        int64       `json:"ordinal"`
	ItemType       string      `json:"item_type"`
	MessageID      pgtype.Text `json:"message_id"`
	SummaryID      pgtype.Text `json:"summary_id"`
	EventType      string      `json:"event_type"`
	Role           string      `json:"role"`
	CreatedAt      time.Time   `json:"created_at"`
}

type CtxMedium struct {
	ID        string      `json:"id"`
	UserID    pgtype.Text `json:"user_id"`
	Sha256    []byte      `json:"sha256"`
	MimeType  string      `json:"mime_type"`
	SizeBytes int64       `json:"size_bytes"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	GroupID   pgtype.Text `json:"group_id"`
	OwnerID   pgtype.Text `json:"owner_id"`
	OwnerKind pgtype.Text `json:"owner_kind"`
	Baseline  pgtype.Text `json:"baseline"`
}

type CtxMessage struct {
	ID                   string      `json:"id"`
	ConversationID       string      `json:"conversation_id"`
	Seq                  int64       `json:"seq"`
	Role                 string      `json:"role"`
	EventType            string      `json:"event_type"`
	Content              string      `json:"content"`
	TokenCount           int64       `json:"token_count"`
	CreatedAt            time.Time   `json:"created_at"`
	ActorType            string      `json:"actor_type"`
	ActorID              pgtype.Text `json:"actor_id"`
	SourceSessionID      pgtype.Text `json:"source_session_id"`
	InboxID              pgtype.Text `json:"inbox_id"`
	OriginGroupMessageID pgtype.Text `json:"origin_group_message_id"`
}

type CtxMessageEmbedding struct {
	MessageID   string             `json:"message_id"`
	Model       string             `json:"model"`
	ContentHash []byte             `json:"content_hash"`
	Embedding   pgvector_go.Vector `json:"embedding"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type CtxMessagePart struct {
	ID          string      `json:"id"`
	MessageID   string      `json:"message_id"`
	PartType    string      `json:"part_type"`
	Ordinal     int64       `json:"ordinal"`
	TextContent pgtype.Text `json:"text_content"`
	ToolCallID  pgtype.Text `json:"tool_call_id"`
	ToolName    pgtype.Text `json:"tool_name"`
	ToolInput   pgtype.Text `json:"tool_input"`
	ToolOutput  pgtype.Text `json:"tool_output"`
	Metadata    pgtype.Text `json:"metadata"`
	MediaID     pgtype.Text `json:"media_id"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type CtxSessionInbox struct {
	ID              string             `json:"id"`
	EnqueueSeq      pgtype.Int8        `json:"enqueue_seq"`
	SourceSessionID string             `json:"source_session_id"`
	TargetSessionID string             `json:"target_session_id"`
	ActorID         string             `json:"actor_id"`
	Content         string             `json:"content"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	ErrorCode       string             `json:"error_code"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type CtxSummary struct {
	ID                        string             `json:"id"`
	ConversationID            string             `json:"conversation_id"`
	Kind                      string             `json:"kind"`
	Depth                     int64              `json:"depth"`
	Content                   string             `json:"content"`
	TokenCount                int64              `json:"token_count"`
	EarliestAt                pgtype.Timestamptz `json:"earliest_at"`
	LatestAt                  pgtype.Timestamptz `json:"latest_at"`
	DescendantCount           int64              `json:"descendant_count"`
	DescendantTokenCount      int64              `json:"descendant_token_count"`
	SourceMessageTokenCount   int64              `json:"source_message_token_count"`
	CreatedAt                 time.Time          `json:"created_at"`
	ContainsNonPrincipalInput bool               `json:"contains_non_principal_input"`
}

type CtxSummaryEmbedding struct {
	SummaryID   string             `json:"summary_id"`
	Model       string             `json:"model"`
	ContentHash []byte             `json:"content_hash"`
	Embedding   pgvector_go.Vector `json:"embedding"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type CtxSummaryMessage struct {
	SummaryID string `json:"summary_id"`
	MessageID string `json:"message_id"`
	Ordinal   int64  `json:"ordinal"`
}

type CtxSummaryParent struct {
	SummaryID       string `json:"summary_id"`
	ParentSummaryID string `json:"parent_summary_id"`
	Ordinal         int64  `json:"ordinal"`
}

type EmailSendDedup struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	SentAt         time.Time `json:"sent_at"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Fact struct {
	ID         string          `json:"id"`
	Subject    string          `json:"subject"`
	Scope      string          `json:"scope"`
	UserID     string          `json:"user_id"`
	AgentID    string          `json:"agent_id"`
	Content    string          `json:"content"`
	Status     string          `json:"status"`
	Metadata   json.RawMessage `json:"metadata"`
	Supersedes pgtype.Text     `json:"supersedes"`
	Version    int64           `json:"version"`
	Source     string          `json:"source"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type KnowledgeUsage struct {
	FactID     string    `json:"fact_id"`
	UserID     string    `json:"user_id"`
	AgentID    string    `json:"agent_id"`
	LastUsedAt time.Time `json:"last_used_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type LibraryChunk struct {
	ID            string          `json:"id"`
	ChunkSetID    string          `json:"chunk_set_id"`
	Ordinal       int64           `json:"ordinal"`
	Content       string          `json:"content"`
	Locator       json.RawMessage `json:"locator"`
	ContentSha256 []byte          `json:"content_sha256"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	LocatorSha256 []byte          `json:"locator_sha256"`
}

type LibraryChunkSet struct {
	ID            string             `json:"id"`
	FileID        string             `json:"file_id"`
	DerivationKey string             `json:"derivation_key"`
	ProcessorKey  string             `json:"processor_key"`
	RawSha256     []byte             `json:"raw_sha256"`
	Status        string             `json:"status"`
	ChunkCount    pgtype.Int8        `json:"chunk_count"`
	ContentDigest []byte             `json:"content_digest"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type LibraryFile struct {
	ID               string             `json:"id"`
	Scope            string             `json:"scope"`
	UserID           pgtype.Text        `json:"user_id"`
	AgentID          pgtype.Text        `json:"agent_id"`
	FileName         string             `json:"file_name"`
	MediaType        string             `json:"media_type"`
	SizeBytes        int64              `json:"size_bytes"`
	RawSha256        []byte             `json:"raw_sha256"`
	Status           string             `json:"status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	ActiveChunkSetID pgtype.Text        `json:"active_chunk_set_id"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type McpConnectionState struct {
	ID               string             `json:"id"`
	ConfigID         string             `json:"config_id"`
	CredentialUserID pgtype.Text        `json:"credential_user_id"`
	Tools            json.RawMessage    `json:"tools"`
	Status           string             `json:"status"`
	StatusError      string             `json:"status_error"`
	ProbedAt         pgtype.Timestamptz `json:"probed_at"`
	ConfigRevision   int64              `json:"config_revision"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type McpOauthFlow struct {
	ID                string             `json:"id"`
	ServerID          string             `json:"server_id"`
	UserID            string             `json:"user_id"`
	CredentialScope   string             `json:"credential_scope"`
	CredentialUserID  pgtype.Text        `json:"credential_user_id"`
	CredentialAgentID pgtype.Text        `json:"credential_agent_id"`
	PkceVerifier      string             `json:"pkce_verifier"`
	OauthConfig       json.RawMessage    `json:"oauth_config"`
	ExpiresAt         time.Time          `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt         time.Time          `json:"created_at"`
}

type McpServer struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         pgtype.Text        `json:"user_id"`
	AgentID        pgtype.Text        `json:"agent_id"`
	Name           string             `json:"name"`
	Url            string             `json:"url"`
	Transport      string             `json:"transport"`
	AuthType       string             `json:"auth_type"`
	CredentialRef  string             `json:"credential_ref"`
	Enabled        bool               `json:"enabled"`
	Metadata       json.RawMessage    `json:"metadata"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Status         string             `json:"status"`
	StatusError    string             `json:"status_error"`
	ProbedAt       pgtype.Timestamptz `json:"probed_at"`
	Tools          json.RawMessage    `json:"tools"`
	CredentialMode string             `json:"credential_mode"`
}

type ModelCatalog struct {
	ID        string          `json:"id"`
	Payload   json.RawMessage `json:"payload"`
	Etag      string          `json:"etag"`
	SyncedAt  time.Time       `json:"synced_at"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type OauthAccessToken struct {
	ID              string             `json:"id"`
	PublicID        string             `json:"public_id"`
	TokenHash       string             `json:"token_hash"`
	Last4           string             `json:"last4"`
	ClientID        string             `json:"client_id"`
	UserID          string             `json:"user_id"`
	Scopes          []string           `json:"scopes"`
	RefreshFamilyID string             `json:"refresh_family_id"`
	ExpiresAt       time.Time          `json:"expires_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type OauthAuthorizationCode struct {
	ID                  string             `json:"id"`
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	UserID              string             `json:"user_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scopes              []string           `json:"scopes"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	ExpiresAt           time.Time          `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt           time.Time          `json:"created_at"`
}

type OauthClient struct {
	ID               string             `json:"id"`
	ClientID         string             `json:"client_id"`
	Name             string             `json:"name"`
	ClientSecretHash string             `json:"client_secret_hash"`
	ClientType       string             `json:"client_type"`
	RedirectUris     []string           `json:"redirect_uris"`
	GrantTypes       []string           `json:"grant_types"`
	Scopes           []string           `json:"scopes"`
	OwnerUserID      string             `json:"owner_user_id"`
	DisabledAt       pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type OauthRefreshFamily struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ClientID  string             `json:"client_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type OauthRefreshToken struct {
	ID           string             `json:"id"`
	PublicID     string             `json:"public_id"`
	TokenHash    string             `json:"token_hash"`
	ClientID     string             `json:"client_id"`
	UserID       string             `json:"user_id"`
	Scopes       []string           `json:"scopes"`
	FamilyID     string             `json:"family_id"`
	ReplacedByID pgtype.Text        `json:"replaced_by_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ExpiresAt    time.Time          `json:"expires_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type PersonalAccessToken struct {
	ID                   string             `json:"id"`
	PublicID             string             `json:"public_id"`
	UserID               string             `json:"user_id"`
	Name                 string             `json:"name"`
	TokenHash            string             `json:"token_hash"`
	Last4                string             `json:"last4"`
	Scopes               []string           `json:"scopes"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	TokenUse             string             `json:"token_use"`
	IssuedByTokenID      pgtype.Text        `json:"issued_by_token_id"`
	IssuedByProvisioning bool               `json:"issued_by_provisioning"`
}

type Plugin struct {
	ID        string          `json:"id"`
	Kind      string          `json:"kind"`
	Name      string          `json:"name"`
	Enabled   bool            `json:"enabled"`
	Config    json.RawMessage `json:"config"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type PluginConfig struct {
	ID             string          `json:"id"`
	PluginID       string          `json:"plugin_id"`
	Namespace      string          `json:"namespace"`
	Scope          string          `json:"scope"`
	UserID         pgtype.Text     `json:"user_id"`
	AgentID        pgtype.Text     `json:"agent_id"`
	Enabled        pgtype.Bool     `json:"enabled"`
	Config         []byte          `json:"config"`
	CredentialRefs json.RawMessage `json:"credential_refs"`
	Revision       int64           `json:"revision"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type PluginDefinition struct {
	ID                string          `json:"id"`
	Namespace         string          `json:"namespace"`
	DisplayName       string          `json:"display_name"`
	Backend           string          `json:"backend"`
	Source            string          `json:"source"`
	ImplementationKey string          `json:"implementation_key"`
	Spec              json.RawMessage `json:"spec"`
	DefaultEnabled    bool            `json:"default_enabled"`
	Revision          int64           `json:"revision"`
	CreatorUserID     pgtype.Text     `json:"creator_user_id"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type PluginOauthProvider struct {
	ID              string    `json:"id"`
	ProviderID      string    `json:"provider_id"`
	ClientID        string    `json:"client_id"`
	ClientSecretEnc string    `json:"client_secret_enc"`
	RedirectUrl     string    `json:"redirect_url"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Scopes          []string  `json:"scopes"`
}

type PluginOverride struct {
	PluginID           string      `json:"plugin_id"`
	Enabled            pgtype.Bool `json:"enabled"`
	SessionEnvVaultKey string      `json:"session_env_vault_key"`
	Config             string      `json:"config"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type PluginState struct {
	PluginID  string          `json:"plugin_id"`
	ScopeKind string          `json:"scope_kind"`
	ScopeID   string          `json:"scope_id"`
	StateKey  string          `json:"state_key"`
	Value     json.RawMessage `json:"value"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Project struct {
	ID          string      `json:"id"`
	AgentID     string      `json:"agent_id"`
	UserID      string      `json:"user_id"`
	Name        string      `json:"name"`
	BaseDir     string      `json:"base_dir"`
	Description pgtype.Text `json:"description"`
	Archived    bool        `json:"archived"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Provider struct {
	ID        string          `json:"id"`
	Type      string          `json:"type"`
	Name      string          `json:"name"`
	Enabled   bool            `json:"enabled"`
	Config    json.RawMessage `json:"config"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type ProviderModelsCache struct {
	ProviderID string          `json:"provider_id"`
	Models     json.RawMessage `json:"models"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type RecallyArticle struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	AgentID      pgtype.Text        `json:"agent_id"`
	Url          string             `json:"url"`
	CanonicalUrl string             `json:"canonical_url"`
	SourceType   string             `json:"source_type"`
	Title        string             `json:"title"`
	Author       string             `json:"author"`
	Summary      string             `json:"summary"`
	Tags         string             `json:"tags"`
	Status       string             `json:"status"`
	Starred      bool               `json:"starred"`
	FilePath     string             `json:"file_path"`
	Metadata     json.RawMessage    `json:"metadata"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	SavedAt      time.Time          `json:"saved_at"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type RecallyArticleContent struct {
	ArticleID string    `json:"article_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RecallyArticleEmbedding struct {
	ArticleID   string             `json:"article_id"`
	Model       string             `json:"model"`
	ContentHash []byte             `json:"content_hash"`
	Embedding   pgvector_go.Vector `json:"embedding"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type RecallyDigest struct {
	ID                   string          `json:"id"`
	UserID               string          `json:"user_id"`
	Date                 string          `json:"date"`
	Narrative            string          `json:"narrative"`
	SavedYesterdayCount  int64           `json:"saved_yesterday_count"`
	UnreadCount          int64           `json:"unread_count"`
	ReadCount            int64           `json:"read_count"`
	ArchivedCount        int64           `json:"archived_count"`
	StarredCount         int64           `json:"starred_count"`
	WorthRevisitingCount int64           `json:"worth_revisiting_count"`
	TotalArticles        int64           `json:"total_articles"`
	TopTags              json.RawMessage `json:"top_tags"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type RecallyDigestArticle struct {
	DigestID  string `json:"digest_id"`
	ArticleID string `json:"article_id"`
	Section   string `json:"section"`
	Position  int64  `json:"position"`
}

type RecallyFeed struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	AgentID       pgtype.Text        `json:"agent_id"`
	Url           string             `json:"url"`
	Kind          string             `json:"kind"`
	Metadata      json.RawMessage    `json:"metadata"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	CheckInterval string             `json:"check_interval"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	LastEtag      string             `json:"last_etag"`
	LastModified  string             `json:"last_modified"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type RecallyFeedEntry struct {
	ID           string             `json:"id"`
	FeedID       string             `json:"feed_id"`
	Guid         string             `json:"guid"`
	Url          string             `json:"url"`
	Title        string             `json:"title"`
	Status       string             `json:"status"`
	ArticleID    pgtype.Text        `json:"article_id"`
	Attempts     int64              `json:"attempts"`
	ErrorMsg     string             `json:"error_msg"`
	DiscoveredAt time.Time          `json:"discovered_at"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
}

type SchedJob struct {
	ID             string             `json:"id"`
	OwnerKind      string             `json:"owner_kind"`
	ExecScope      string             `json:"exec_scope"`
	JobKey         string             `json:"job_key"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	ScheduleCron   string             `json:"schedule_cron"`
	ScheduleEvery  string             `json:"schedule_every"`
	ScheduleAt     string             `json:"schedule_at"`
	Message        string             `json:"message"`
	Payload        json.RawMessage    `json:"payload"`
	SessionMode    string             `json:"session_mode"`
	Enabled        bool               `json:"enabled"`
	AgentID        pgtype.Text        `json:"agent_id"`
	UserID         pgtype.Text        `json:"user_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	LastRunAt      pgtype.Timestamptz `json:"last_run_at"`
	LastError      string             `json:"last_error"`
	DispatchKind   string             `json:"dispatch_kind"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
}

type SchedJobRun struct {
	ID         string             `json:"id"`
	JobID      string             `json:"job_id"`
	SessionID  string             `json:"session_id"`
	Status     string             `json:"status"`
	StartedAt  time.Time          `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Error      string             `json:"error"`
	Output     string             `json:"output"`
	UserID     pgtype.Text        `json:"user_id"`
	RootGoalID pgtype.Text        `json:"root_goal_id"`
}

type Share struct {
	ID        string             `json:"id"`
	TokenHash string             `json:"token_hash"`
	UserID    string             `json:"user_id"`
	Title     string             `json:"title"`
	MediaType string             `json:"media_type"`
	Content   []byte             `json:"content"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}

type Skill struct {
	ID                     string          `json:"id"`
	Scope                  string          `json:"scope"`
	UserID                 pgtype.Text     `json:"user_id"`
	AgentID                pgtype.Text     `json:"agent_id"`
	Name                   string          `json:"name"`
	Description            string          `json:"description"`
	Status                 string          `json:"status"`
	DisableModelInvocation bool            `json:"disable_model_invocation"`
	Metadata               json.RawMessage `json:"metadata"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              time.Time       `json:"updated_at"`
	Version                int64           `json:"version"`
}

type SkillChangelog struct {
	ID            string          `json:"id"`
	SkillID       string          `json:"skill_id"`
	UserID        pgtype.Text     `json:"user_id"`
	AgentID       pgtype.Text     `json:"agent_id"`
	Scope         string          `json:"scope"`
	Action        string          `json:"action"`
	VersionBefore pgtype.Int8     `json:"version_before"`
	VersionAfter  int64           `json:"version_after"`
	Metadata      json.RawMessage `json:"metadata"`
	CreatedAt     time.Time       `json:"created_at"`
	ContentDigest pgtype.Text     `json:"content_digest"`
}

type SkillFile struct {
	SkillID string `json:"skill_id"`
	Path    string `json:"path"`
	Content []byte `json:"content"`
}

type SkillHomeMigration struct {
	ID                       string          `json:"id"`
	State                    string          `json:"state"`
	SourceSkillCount         int64           `json:"source_skill_count"`
	SourceFileCount          int64           `json:"source_file_count"`
	SourceContentBytes       int64           `json:"source_content_bytes"`
	SourceInventoryDigest    string          `json:"source_inventory_digest"`
	Inventory                json.RawMessage `json:"inventory"`
	WritersStoppedAttestedAt time.Time       `json:"writers_stopped_attested_at"`
	BackupVerifiedAttestedAt time.Time       `json:"backup_verified_attested_at"`
	CompletedAt              time.Time       `json:"completed_at"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
}

type SkillUsage struct {
	SkillID       string      `json:"skill_id"`
	UserID        string      `json:"user_id"`
	AgentID       string      `json:"agent_id"`
	UseCount      int64       `json:"use_count"`
	LastUsedAt    time.Time   `json:"last_used_at"`
	CreatedAt     time.Time   `json:"created_at"`
	ContentDigest pgtype.Text `json:"content_digest"`
}

type ToolOverride struct {
	ID            string      `json:"id"`
	ToolName      pgtype.Text `json:"tool_name"`
	Scope         string      `json:"scope"`
	UserID        pgtype.Text `json:"user_id"`
	AgentID       pgtype.Text `json:"agent_id"`
	Enabled       bool        `json:"enabled"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	PluginID      pgtype.Text `json:"plugin_id"`
	LocalToolName pgtype.Text `json:"local_tool_name"`
}

type VaultEntry struct {
	ID          string      `json:"id"`
	Scope       string      `json:"scope"`
	UserID      pgtype.Text `json:"user_id"`
	AgentID     pgtype.Text `json:"agent_id"`
	Name        string      `json:"name"`
	Ciphertext  string      `json:"ciphertext"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Description pgtype.Text `json:"description"`
}

type Webhook struct {
	ID                   string             `json:"id"`
	UserID               string             `json:"user_id"`
	AgentID              string             `json:"agent_id"`
	Name                 string             `json:"name"`
	Provider             string             `json:"provider"`
	IsEnabled            bool               `json:"is_enabled"`
	WaitTimeoutSeconds   int32              `json:"wait_timeout_seconds"`
	MaxRunTimeoutSeconds int32              `json:"max_run_timeout_seconds"`
	TokenPublicID        string             `json:"token_public_id"`
	TokenHash            string             `json:"token_hash"`
	TokenLast4           string             `json:"token_last4"`
	Revision             int64              `json:"revision"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	RotatedAt            pgtype.Timestamptz `json:"rotated_at"`
}
