// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plugin_snapshot.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPluginConfigsForContext = `-- name: ListPluginConfigsForContext :many
SELECT id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at FROM plugin_config
WHERE scope = 'system'
   OR (scope = 'system_agent' AND agent_id = $1)
   OR (scope = 'user' AND user_id = $2::uuid)
   OR (scope = 'user_agent' AND user_id = $2::uuid AND agent_id = $1)
ORDER BY plugin_id, scope, user_id NULLS FIRST, agent_id NULLS FIRST, id
`

type ListPluginConfigsForContextParams struct {
	AgentID pgtype.Text `json:"agent_id"`
	UserID  pgtype.Text `json:"user_id"`
}

func (q *Queries) ListPluginConfigsForContext(ctx context.Context, arg ListPluginConfigsForContextParams) ([]PluginConfig, error) {
	rows, err := q.db.Query(ctx, listPluginConfigsForContext, arg.AgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginConfig{}
	for rows.Next() {
		var i PluginConfig
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Namespace,
			&i.Scope,
			&i.UserID,
			&i.AgentID,
			&i.Enabled,
			&i.Config,
			&i.CredentialRefs,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
