// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: unified_plugin.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPluginConfig = `-- name: CreatePluginConfig :one
INSERT INTO plugin_config (
    id, plugin_id, namespace, scope, user_id, agent_id, enabled, config,
    credential_refs, revision, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
RETURNING id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at
`

type CreatePluginConfigParams struct {
	ID             string          `json:"id"`
	PluginID       string          `json:"plugin_id"`
	Namespace      string          `json:"namespace"`
	Scope          string          `json:"scope"`
	UserID         pgtype.Text     `json:"user_id"`
	AgentID        pgtype.Text     `json:"agent_id"`
	Enabled        pgtype.Bool     `json:"enabled"`
	Config         []byte          `json:"config"`
	CredentialRefs json.RawMessage `json:"credential_refs"`
	Revision       int64           `json:"revision"`
}

func (q *Queries) CreatePluginConfig(ctx context.Context, arg CreatePluginConfigParams) (PluginConfig, error) {
	row := q.db.QueryRow(ctx, createPluginConfig,
		arg.ID,
		arg.PluginID,
		arg.Namespace,
		arg.Scope,
		arg.UserID,
		arg.AgentID,
		arg.Enabled,
		arg.Config,
		arg.CredentialRefs,
		arg.Revision,
	)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Namespace,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Enabled,
		&i.Config,
		&i.CredentialRefs,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPluginDefinition = `-- name: CreatePluginDefinition :one
INSERT INTO plugin_definition (
    id, namespace, display_name, backend, source, implementation_key,
    spec, default_enabled, revision, creator_user_id, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
RETURNING id, namespace, display_name, backend, source, implementation_key, spec, default_enabled, revision, creator_user_id, created_at, updated_at
`

type CreatePluginDefinitionParams struct {
	ID                string          `json:"id"`
	Namespace         string          `json:"namespace"`
	DisplayName       string          `json:"display_name"`
	Backend           string          `json:"backend"`
	Source            string          `json:"source"`
	ImplementationKey string          `json:"implementation_key"`
	Spec              json.RawMessage `json:"spec"`
	DefaultEnabled    bool            `json:"default_enabled"`
	Revision          int64           `json:"revision"`
	CreatorUserID     pgtype.Text     `json:"creator_user_id"`
}

func (q *Queries) CreatePluginDefinition(ctx context.Context, arg CreatePluginDefinitionParams) (PluginDefinition, error) {
	row := q.db.QueryRow(ctx, createPluginDefinition,
		arg.ID,
		arg.Namespace,
		arg.DisplayName,
		arg.Backend,
		arg.Source,
		arg.ImplementationKey,
		arg.Spec,
		arg.DefaultEnabled,
		arg.Revision,
		arg.CreatorUserID,
	)
	var i PluginDefinition
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.DisplayName,
		&i.Backend,
		&i.Source,
		&i.ImplementationKey,
		&i.Spec,
		&i.DefaultEnabled,
		&i.Revision,
		&i.CreatorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePluginConfigCAS = `-- name: DeletePluginConfigCAS :execrows
DELETE FROM plugin_config
USING plugin_definition
WHERE plugin_config.id = $1
  AND plugin_config.revision = $2
  AND plugin_config.plugin_id = $3
  AND plugin_config.plugin_id = plugin_definition.id
  AND NOT (plugin_definition.source = 'builtin' AND plugin_config.scope = 'system')
`

type DeletePluginConfigCASParams struct {
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
	PluginID string `json:"plugin_id"`
}

func (q *Queries) DeletePluginConfigCAS(ctx context.Context, arg DeletePluginConfigCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePluginConfigCAS, arg.ID, arg.Revision, arg.PluginID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePluginDefinitionCAS = `-- name: DeletePluginDefinitionCAS :execrows
DELETE FROM plugin_definition
WHERE id = $1 AND revision = $2 AND source = 'custom'
`

type DeletePluginDefinitionCASParams struct {
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
}

func (q *Queries) DeletePluginDefinitionCAS(ctx context.Context, arg DeletePluginDefinitionCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePluginDefinitionCAS, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePluginToolPolicies = `-- name: DeletePluginToolPolicies :exec
DELETE FROM tool_override WHERE plugin_id = $1
`

func (q *Queries) DeletePluginToolPolicies(ctx context.Context, pluginID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deletePluginToolPolicies, pluginID)
	return err
}

const ensureSystemPluginConfig = `-- name: EnsureSystemPluginConfig :one
WITH inserted AS (
    INSERT INTO plugin_config (
        plugin_id, namespace, scope, enabled, config, credential_refs, revision, updated_at
    ) VALUES ($1, $2, 'system', NULL, '{}'::jsonb, '{}'::jsonb, 1, now())
    ON CONFLICT (plugin_id, scope, user_id, agent_id) DO NOTHING
    RETURNING id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at
)
SELECT id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at FROM inserted
UNION ALL
SELECT id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at FROM plugin_config
WHERE plugin_id = $1 AND namespace = $2 AND scope = 'system'
LIMIT 1
`

type EnsureSystemPluginConfigParams struct {
	PluginID  string `json:"plugin_id"`
	Namespace string `json:"namespace"`
}

type EnsureSystemPluginConfigRow struct {
	ID             string          `json:"id"`
	PluginID       string          `json:"plugin_id"`
	Namespace      string          `json:"namespace"`
	Scope          string          `json:"scope"`
	UserID         pgtype.Text     `json:"user_id"`
	AgentID        pgtype.Text     `json:"agent_id"`
	Enabled        pgtype.Bool     `json:"enabled"`
	Config         []byte          `json:"config"`
	CredentialRefs json.RawMessage `json:"credential_refs"`
	Revision       int64           `json:"revision"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

func (q *Queries) EnsureSystemPluginConfig(ctx context.Context, arg EnsureSystemPluginConfigParams) (EnsureSystemPluginConfigRow, error) {
	row := q.db.QueryRow(ctx, ensureSystemPluginConfig, arg.PluginID, arg.Namespace)
	var i EnsureSystemPluginConfigRow
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Namespace,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Enabled,
		&i.Config,
		&i.CredentialRefs,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginConfigForOwner = `-- name: GetPluginConfigForOwner :one
SELECT id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at FROM plugin_config
WHERE id = $1 AND plugin_id = $2
  AND ((scope IN ('system', 'system_agent') AND $3::boolean)
    OR (scope IN ('user', 'user_agent') AND user_id = $4::uuid))
`

type GetPluginConfigForOwnerParams struct {
	ID           string `json:"id"`
	PluginID     string `json:"plugin_id"`
	IsAdmin      bool   `json:"is_admin"`
	ViewerUserID string `json:"viewer_user_id"`
}

func (q *Queries) GetPluginConfigForOwner(ctx context.Context, arg GetPluginConfigForOwnerParams) (PluginConfig, error) {
	row := q.db.QueryRow(ctx, getPluginConfigForOwner,
		arg.ID,
		arg.PluginID,
		arg.IsAdmin,
		arg.ViewerUserID,
	)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Namespace,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Enabled,
		&i.Config,
		&i.CredentialRefs,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginDefinition = `-- name: GetPluginDefinition :one

SELECT id, namespace, display_name, backend, source, implementation_key, spec, default_enabled, revision, creator_user_id, created_at, updated_at FROM plugin_definition WHERE id = $1
`

// Unified plugin definitions and four-scope configuration records. These
// queries are intentionally separate from legacy plugin rows until cutover.
func (q *Queries) GetPluginDefinition(ctx context.Context, id string) (PluginDefinition, error) {
	row := q.db.QueryRow(ctx, getPluginDefinition, id)
	var i PluginDefinition
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.DisplayName,
		&i.Backend,
		&i.Source,
		&i.ImplementationKey,
		&i.Spec,
		&i.DefaultEnabled,
		&i.Revision,
		&i.CreatorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPluginConfigs = `-- name: ListPluginConfigs :many
SELECT id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at FROM plugin_config
WHERE plugin_id = $1
ORDER BY scope, user_id NULLS FIRST, agent_id NULLS FIRST, id
`

func (q *Queries) ListPluginConfigs(ctx context.Context, pluginID string) ([]PluginConfig, error) {
	rows, err := q.db.Query(ctx, listPluginConfigs, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginConfig{}
	for rows.Next() {
		var i PluginConfig
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Namespace,
			&i.Scope,
			&i.UserID,
			&i.AgentID,
			&i.Enabled,
			&i.Config,
			&i.CredentialRefs,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginConfigsOwned = `-- name: ListPluginConfigsOwned :many
SELECT id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at FROM plugin_config
WHERE plugin_id = $1
  AND scope = $2
  AND user_id IS NOT DISTINCT FROM $3
  AND agent_id IS NOT DISTINCT FROM $4
ORDER BY id
`

type ListPluginConfigsOwnedParams struct {
	PluginID string      `json:"plugin_id"`
	Scope    string      `json:"scope"`
	UserID   pgtype.Text `json:"user_id"`
	AgentID  pgtype.Text `json:"agent_id"`
}

func (q *Queries) ListPluginConfigsOwned(ctx context.Context, arg ListPluginConfigsOwnedParams) ([]PluginConfig, error) {
	rows, err := q.db.Query(ctx, listPluginConfigsOwned,
		arg.PluginID,
		arg.Scope,
		arg.UserID,
		arg.AgentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginConfig{}
	for rows.Next() {
		var i PluginConfig
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Namespace,
			&i.Scope,
			&i.UserID,
			&i.AgentID,
			&i.Enabled,
			&i.Config,
			&i.CredentialRefs,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginDefinitions = `-- name: ListPluginDefinitions :many
SELECT id, namespace, display_name, backend, source, implementation_key, spec, default_enabled, revision, creator_user_id, created_at, updated_at FROM plugin_definition ORDER BY namespace, id
`

func (q *Queries) ListPluginDefinitions(ctx context.Context) ([]PluginDefinition, error) {
	rows, err := q.db.Query(ctx, listPluginDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginDefinition{}
	for rows.Next() {
		var i PluginDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.DisplayName,
			&i.Backend,
			&i.Source,
			&i.ImplementationKey,
			&i.Spec,
			&i.DefaultEnabled,
			&i.Revision,
			&i.CreatorUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPluginCatalog = `-- name: LockPluginCatalog :exec
SELECT pg_advisory_xact_lock(hashtextextended('plugin_cutover_v1', 0))
`

func (q *Queries) LockPluginCatalog(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPluginCatalog)
	return err
}

const movePluginConfigCAS = `-- name: MovePluginConfigCAS :one
UPDATE plugin_config
SET scope = $2,
    user_id = $3,
    agent_id = $4,
    enabled = $5,
    config = $6,
    credential_refs = $7,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1 AND revision = $8
RETURNING id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at
`

type MovePluginConfigCASParams struct {
	ID             string          `json:"id"`
	Scope          string          `json:"scope"`
	UserID         pgtype.Text     `json:"user_id"`
	AgentID        pgtype.Text     `json:"agent_id"`
	Enabled        pgtype.Bool     `json:"enabled"`
	Config         []byte          `json:"config"`
	CredentialRefs json.RawMessage `json:"credential_refs"`
	Revision       int64           `json:"revision"`
}

func (q *Queries) MovePluginConfigCAS(ctx context.Context, arg MovePluginConfigCASParams) (PluginConfig, error) {
	row := q.db.QueryRow(ctx, movePluginConfigCAS,
		arg.ID,
		arg.Scope,
		arg.UserID,
		arg.AgentID,
		arg.Enabled,
		arg.Config,
		arg.CredentialRefs,
		arg.Revision,
	)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Namespace,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Enabled,
		&i.Config,
		&i.CredentialRefs,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetBuiltinPluginConfig = `-- name: ResetBuiltinPluginConfig :one
UPDATE plugin_config
SET enabled = NULL,
    config = '{}'::jsonb,
    credential_refs = '{}'::jsonb,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1 AND revision = $2 AND plugin_id = $3 AND scope = 'system'
RETURNING id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at
`

type ResetBuiltinPluginConfigParams struct {
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
	PluginID string `json:"plugin_id"`
}

func (q *Queries) ResetBuiltinPluginConfig(ctx context.Context, arg ResetBuiltinPluginConfigParams) (PluginConfig, error) {
	row := q.db.QueryRow(ctx, resetBuiltinPluginConfig, arg.ID, arg.Revision, arg.PluginID)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Namespace,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Enabled,
		&i.Config,
		&i.CredentialRefs,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePluginConfigCAS = `-- name: UpdatePluginConfigCAS :one
UPDATE plugin_config
SET enabled = $2,
    config = $3,
    credential_refs = $4,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1 AND revision = $5
RETURNING id, plugin_id, namespace, scope, user_id, agent_id, enabled, config, credential_refs, revision, created_at, updated_at
`

type UpdatePluginConfigCASParams struct {
	ID             string          `json:"id"`
	Enabled        pgtype.Bool     `json:"enabled"`
	Config         []byte          `json:"config"`
	CredentialRefs json.RawMessage `json:"credential_refs"`
	Revision       int64           `json:"revision"`
}

func (q *Queries) UpdatePluginConfigCAS(ctx context.Context, arg UpdatePluginConfigCASParams) (PluginConfig, error) {
	row := q.db.QueryRow(ctx, updatePluginConfigCAS,
		arg.ID,
		arg.Enabled,
		arg.Config,
		arg.CredentialRefs,
		arg.Revision,
	)
	var i PluginConfig
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Namespace,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Enabled,
		&i.Config,
		&i.CredentialRefs,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePluginDefinitionCAS = `-- name: UpdatePluginDefinitionCAS :one
UPDATE plugin_definition
SET display_name = $2,
    spec = $4,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1 AND revision = $3 AND source = 'custom'
RETURNING id, namespace, display_name, backend, source, implementation_key, spec, default_enabled, revision, creator_user_id, created_at, updated_at
`

type UpdatePluginDefinitionCASParams struct {
	ID          string          `json:"id"`
	DisplayName string          `json:"display_name"`
	Revision    int64           `json:"revision"`
	Spec        json.RawMessage `json:"spec"`
}

func (q *Queries) UpdatePluginDefinitionCAS(ctx context.Context, arg UpdatePluginDefinitionCASParams) (PluginDefinition, error) {
	row := q.db.QueryRow(ctx, updatePluginDefinitionCAS,
		arg.ID,
		arg.DisplayName,
		arg.Revision,
		arg.Spec,
	)
	var i PluginDefinition
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.DisplayName,
		&i.Backend,
		&i.Source,
		&i.ImplementationKey,
		&i.Spec,
		&i.DefaultEnabled,
		&i.Revision,
		&i.CreatorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPluginDefinition = `-- name: UpsertPluginDefinition :one
INSERT INTO plugin_definition (
    id, namespace, display_name, backend, source, implementation_key,
    spec, default_enabled, revision, creator_user_id, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (id) DO UPDATE SET
    display_name = excluded.display_name,
    spec = excluded.spec,
    default_enabled = excluded.default_enabled,
    revision = CASE WHEN (plugin_definition.display_name, plugin_definition.spec, plugin_definition.default_enabled)
        IS DISTINCT FROM (excluded.display_name, excluded.spec, excluded.default_enabled)
        THEN plugin_definition.revision + 1 ELSE plugin_definition.revision END,
    updated_at = CASE WHEN (plugin_definition.display_name, plugin_definition.spec, plugin_definition.default_enabled)
        IS DISTINCT FROM (excluded.display_name, excluded.spec, excluded.default_enabled)
        THEN now() ELSE plugin_definition.updated_at END
WHERE plugin_definition.namespace = excluded.namespace
  AND plugin_definition.backend = excluded.backend
  AND plugin_definition.source = excluded.source
  AND plugin_definition.implementation_key = excluded.implementation_key
RETURNING id, namespace, display_name, backend, source, implementation_key, spec, default_enabled, revision, creator_user_id, created_at, updated_at
`

type UpsertPluginDefinitionParams struct {
	ID                string          `json:"id"`
	Namespace         string          `json:"namespace"`
	DisplayName       string          `json:"display_name"`
	Backend           string          `json:"backend"`
	Source            string          `json:"source"`
	ImplementationKey string          `json:"implementation_key"`
	Spec              json.RawMessage `json:"spec"`
	DefaultEnabled    bool            `json:"default_enabled"`
	Revision          int64           `json:"revision"`
	CreatorUserID     pgtype.Text     `json:"creator_user_id"`
}

func (q *Queries) UpsertPluginDefinition(ctx context.Context, arg UpsertPluginDefinitionParams) (PluginDefinition, error) {
	row := q.db.QueryRow(ctx, upsertPluginDefinition,
		arg.ID,
		arg.Namespace,
		arg.DisplayName,
		arg.Backend,
		arg.Source,
		arg.ImplementationKey,
		arg.Spec,
		arg.DefaultEnabled,
		arg.Revision,
		arg.CreatorUserID,
	)
	var i PluginDefinition
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.DisplayName,
		&i.Backend,
		&i.Source,
		&i.ImplementationKey,
		&i.Spec,
		&i.DefaultEnabled,
		&i.Revision,
		&i.CreatorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
