// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vault_entry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMCPConfigCredentials = `-- name: DeleteMCPConfigCredentials :exec
DELETE FROM vault_entry
WHERE name IN (
    'MCP_TOKEN_' || upper(replace($1::uuid::text, '-', '_')),
    'MCP_OAUTH_' || upper(replace($1::uuid::text, '-', '_')),
    'MCP_OAUTH_CLIENT_' || upper(replace($1::uuid::text, '-', '_'))
)
`

// Names are derived here so the caller cannot broaden the deletion to a prefix.
func (q *Queries) DeleteMCPConfigCredentials(ctx context.Context, configID string) error {
	_, err := q.db.Exec(ctx, deleteMCPConfigCredentials, configID)
	return err
}

const deleteVaultEntryByScope = `-- name: DeleteVaultEntryByScope :exec
DELETE FROM vault_entry
WHERE scope = $1
  AND coalesce(user_id::text, '') = coalesce($2::text, '')
  AND coalesce(agent_id, '') = coalesce($3, '')
  AND name = $4
`

type DeleteVaultEntryByScopeParams struct {
	Scope   string      `json:"scope"`
	UserID  pgtype.Text `json:"user_id"`
	AgentID pgtype.Text `json:"agent_id"`
	Name    string      `json:"name"`
}

func (q *Queries) DeleteVaultEntryByScope(ctx context.Context, arg DeleteVaultEntryByScopeParams) error {
	_, err := q.db.Exec(ctx, deleteVaultEntryByScope,
		arg.Scope,
		arg.UserID,
		arg.AgentID,
		arg.Name,
	)
	return err
}

const getVaultEntryByScope = `-- name: GetVaultEntryByScope :one
SELECT id, scope, user_id, agent_id, name, ciphertext, created_at, updated_at, description
FROM vault_entry
WHERE scope = $1
  AND coalesce(user_id::text, '') = coalesce($2::text, '')
  AND coalesce(agent_id, '') = coalesce($3, '')
  AND name = $4
`

type GetVaultEntryByScopeParams struct {
	Scope   string      `json:"scope"`
	UserID  pgtype.Text `json:"user_id"`
	AgentID pgtype.Text `json:"agent_id"`
	Name    string      `json:"name"`
}

func (q *Queries) GetVaultEntryByScope(ctx context.Context, arg GetVaultEntryByScopeParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, getVaultEntryByScope,
		arg.Scope,
		arg.UserID,
		arg.AgentID,
		arg.Name,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Name,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const listVaultEntriesByScope = `-- name: ListVaultEntriesByScope :many
SELECT id, scope, user_id, agent_id, name, ciphertext, created_at, updated_at, description
FROM vault_entry
WHERE scope = $1
  AND coalesce(user_id::text, '') = coalesce($2::text, '')
  AND coalesce(agent_id, '') = coalesce($3, '')
ORDER BY name
`

type ListVaultEntriesByScopeParams struct {
	Scope   string      `json:"scope"`
	UserID  pgtype.Text `json:"user_id"`
	AgentID pgtype.Text `json:"agent_id"`
}

func (q *Queries) ListVaultEntriesByScope(ctx context.Context, arg ListVaultEntriesByScopeParams) ([]VaultEntry, error) {
	rows, err := q.db.Query(ctx, listVaultEntriesByScope, arg.Scope, arg.UserID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultEntry{}
	for rows.Next() {
		var i VaultEntry
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.UserID,
			&i.AgentID,
			&i.Name,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesForRuntime = `-- name: ListVaultEntriesForRuntime :many
SELECT id, scope, user_id, agent_id, name, ciphertext, created_at, updated_at, description
FROM vault_entry
WHERE ((scope = 'system' AND user_id IS NULL AND vault_entry.agent_id IS NULL)
    OR (scope = 'system_agent' AND user_id IS NULL AND vault_entry.agent_id = $1)
    OR (scope = 'user' AND user_id = $2 AND vault_entry.agent_id IS NULL)
    OR (scope = 'user_agent' AND user_id = $2 AND vault_entry.agent_id = $1))
ORDER BY CASE scope
    WHEN 'system' THEN 1
    WHEN 'system_agent' THEN 2
    WHEN 'user' THEN 3
    WHEN 'user_agent' THEN 4
    ELSE 0
END, name
`

type ListVaultEntriesForRuntimeParams struct {
	RuntimeAgentID pgtype.Text `json:"runtime_agent_id"`
	UserID         pgtype.Text `json:"user_id"`
}

// Keep this precedence in sync with vault.Service.LoadEnvForAgent's merge loop.
func (q *Queries) ListVaultEntriesForRuntime(ctx context.Context, arg ListVaultEntriesForRuntimeParams) ([]VaultEntry, error) {
	rows, err := q.db.Query(ctx, listVaultEntriesForRuntime, arg.RuntimeAgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultEntry{}
	for rows.Next() {
		var i VaultEntry
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.UserID,
			&i.AgentID,
			&i.Name,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVaultEntryByScope = `-- name: UpsertVaultEntryByScope :one
INSERT INTO vault_entry (id, scope, user_id, agent_id, name, ciphertext, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (scope, (COALESCE(user_id::text, '')), (COALESCE(agent_id, '')), name) DO UPDATE SET
    ciphertext = excluded.ciphertext,
    description = coalesce($7, vault_entry.description),
    updated_at = now()
RETURNING id, scope, user_id, agent_id, name, ciphertext, created_at, updated_at, description
`

type UpsertVaultEntryByScopeParams struct {
	ID          string      `json:"id"`
	Scope       string      `json:"scope"`
	UserID      pgtype.Text `json:"user_id"`
	AgentID     pgtype.Text `json:"agent_id"`
	Name        string      `json:"name"`
	Ciphertext  string      `json:"ciphertext"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpsertVaultEntryByScope(ctx context.Context, arg UpsertVaultEntryByScopeParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, upsertVaultEntryByScope,
		arg.ID,
		arg.Scope,
		arg.UserID,
		arg.AgentID,
		arg.Name,
		arg.Ciphertext,
		arg.Description,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.UserID,
		&i.AgentID,
		&i.Name,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}
