package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"maps"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	inputPath      = "internal/server/docs_spec.yaml"
	componentsPath = "api/spec/components.yaml"
	standaloneDir  = "api/spec/agent-tools"
	outputRoot     = "."
)

var identityFields = map[string]bool{
	"agent_id": true,
	"agentId":  true,
	"user_id":  true,
	"userId":   true,
}

// toolgen has two declaration sources and one intermediate representation.
//
// The first source is an `x-agent-tool` annotation on an HTTP operation, which
// is where a tool belongs when the capability already has a REST contract:
//
//	x-agent-tool: { tool: "goal", action: "create" }
//
// or a list when one operation backs several tool actions:
//
//	x-agent-tool:
//	  - { tool: "scheduler", resource: "job", action: "update" }
//	  - { tool: "scheduler", resource: "job", action: "pause", fixed: { enabled: false }, body: false }
//	  - { tool: "scheduler", resource: "job", action: "resume", fixed: { enabled: true }, body: false }
//
// The second source is api/spec/agent-tools/*.yaml, for capabilities that have
// no HTTP operation at all (a session send, a skill load). Inventing an
// endpoint just to hang a tool off it would be a lie about the contract; those
// tools declare their schema directly and still go through this generator.
//
// Both sources produce []toolDecl, which is validated as a whole (globally
// unique names, provider-legal names, snake_case properties) and then rendered
// per family.
//
// Annotation modifiers:
//   - fixed: service-owned constants, removed from the model input.
//   - restrict: narrows a property's enum without changing the HTTP API; the
//     first value becomes the default.
//   - require/optional: change requiredness in the tool schema only.
//   - add: tool-only properties. For a batch action they belong to each item.
//   - omit: drops a property from the tool input without touching the HTTP API.
//   - rename: renames a property (and its required entry) in the tool input.
//   - body: false: take path/query parameters only, ignore the request body.
//   - batch: wrap the request body in an array property of that name.
//   - name_override: an explicit tool name, for the rare case the default
//     family_resource_action grammar reads wrong (see rules/agent-tools.md §4).
func main() {
	if err := run(inputPath, standaloneDir, outputRoot); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(input, declDir, outRoot string) error {
	data, err := os.ReadFile(input)
	if err != nil {
		return fmt.Errorf("read %s: %w", input, err)
	}
	doc, err := parseDoc(data)
	if err != nil {
		return err
	}
	if err := mergeComponentSchemas(doc, componentsPath); err != nil {
		return err
	}
	decls, err := collectOperationTools(doc)
	if err != nil {
		return err
	}
	standalone, err := collectStandaloneTools(declDir, doc)
	if err != nil {
		return err
	}
	decls = append(decls, standalone...)
	if err := validate(decls); err != nil {
		return err
	}
	outputs := groupByOutput(decls)
	expected := map[string]bool{}
	for _, key := range sortedKeysOf(outputs) {
		group := outputs[key]
		family := group[0].Family
		content, err := renderTool(family, group[0].Package, group)
		if err != nil {
			return err
		}
		root := group[0].Package.Root
		if root == "" {
			root = "internal"
		}
		outDir := filepath.Join(outRoot, root, group[0].Package.Dir)
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return err
		}
		out := filepath.Join(outDir, generatedFileName(family))
		expected[out] = true
		if err := os.WriteFile(out, content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", out, err)
		}
	}
	// Keep the supported roots explicit. Deriving them from the current output
	// set leaves stale generated files behind when the last family in a root is
	// removed from the declarations.
	for _, root := range []string{"internal", "plugins"} {
		rootPath := filepath.Join(outRoot, root)
		if _, err := os.Stat(rootPath); os.IsNotExist(err) {
			continue
		} else if err != nil {
			return err
		}
		if err := pruneStaleOutputs(rootPath, expected); err != nil {
			return err
		}
	}
	return nil
}

// generatedFileName gives every family its own output. Families that share a
// package must never overwrite each other or share generated identifiers.
func generatedFileName(family string) string { return "tool_" + family + "_gen.go" }

// generatedMarker is the header every rendered file carries. Pruning keys off
// it rather than off the file name, so a hand-written tool_<family>_gen.go is
// never deleted.
const generatedMarker = "// Code generated by go run ./internal/tools/toolgen; DO NOT EDIT."

// pruneStaleOutputs deletes generated files no declaration produces any more.
// Without it, deleting the last declaration of a family leaves its tool_gen.go
// behind: it keeps compiling, keeps exporting ActionTools(), and keeps the
// removed tool registered. The drift check cannot see it either, because
// nothing changed.
func pruneStaleOutputs(outRoot string, expected map[string]bool) error {
	return filepath.WalkDir(outRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), "tool_") || !strings.HasSuffix(entry.Name(), "_gen.go") || expected[path] {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.HasPrefix(data, []byte(generatedMarker)) {
			return nil
		}
		fmt.Fprintf(os.Stderr, "toolgen: removing stale %s (no declaration generates it)\n", path)
		return os.Remove(path)
	})
}

type openAPIDoc struct {
	Paths      map[string]any `yaml:"paths"`
	Components struct {
		Schemas map[string]any `yaml:"schemas"`
	} `yaml:"components"`
}

type actionSpec struct {
	Tool         string `yaml:"tool"`
	Resource     string `yaml:"resource"`
	Action       string `yaml:"action"`
	NameOverride string `yaml:"name_override"`
	Description  string `yaml:"description"`
	// Input replaces the operation request body for this tool only. It lets a
	// model-facing schema be stricter than the corresponding HTTP contract.
	Input         any               `yaml:"input"`
	Fixed         map[string]any    `yaml:"fixed"`
	Restrict      map[string][]any  `yaml:"restrict"`
	Require       []string          `yaml:"require"`
	Optional      []string          `yaml:"optional"`
	PreserveEmpty []string          `yaml:"preserve_empty"`
	Add           map[string]any    `yaml:"add"`
	Omit          []string          `yaml:"omit"`
	Rename        map[string]string `yaml:"rename"`
	Body          *bool             `yaml:"body"`
	Batch         string            `yaml:"batch"`
}

// useBody reports whether the request body contributes to the tool input.
// It is opt-out rather than inferred: a pause action that fixes the one body
// field it needs must say `body: false`, so the reader of the annotation can
// see why the remaining body fields are gone.
func (s actionSpec) useBody() bool { return s.Body == nil || *s.Body }

type domainPackage struct {
	Root    string
	Dir     string
	Package string
	// PluginID and Namespace are authored at this composition root for the
	// generated families that are real Go plugins. Empty values mean the
	// family is a core tool and keeps its existing name.
	PluginID  string
	Namespace string
	// PrefixGeneratedSymbols makes this family safe to generate alongside other
	// families or hand-written action-shaped types in the same package.
	PrefixGeneratedSymbols bool
	// Split emits one tool per action instead of one union tool. Providers
	// reject oneOf/const at the top level of a function schema, so a union tool
	// cannot express per-action parameters: every action's fields are hoisted
	// together and a wrong one is only caught after the call. Splitting is the
	// only way to get the provider to validate arguments before dispatch.
	Split bool
}

var domainPackages = map[string]domainPackage{
	"goal":      {Dir: "goal", Package: "goal", Split: true},
	"scheduler": {Dir: "scheduler", Package: "scheduler", PluginID: "system/scheduler", Namespace: "scheduler", Split: true},
	"workflow":  {Dir: "workflow", Package: "workflow", Split: true},
	"vault":     {Dir: "vault", Package: "vault", Split: true},
	"oauth":     {Dir: "connections", Package: "connections", Split: true},
	"share":     {Dir: "share", Package: "share", Split: true},
	"recally":   {Dir: "library/recally", Package: "recally", PluginID: "system/recally", Namespace: "recally", Split: true},
	"email":     {Root: "plugins", Dir: "email", Package: "email", PluginID: "system/email", Namespace: "email", Split: true},
	// Settings families share existing Go packages, so generated identifiers stay
	// prefixed to avoid collisions. The unprefixed library and skill mappings are
	// still used by declaration-only runtime tools such as library_search and
	// skill_load.
	"library":                    {Dir: "library", Package: "library", Split: true, PrefixGeneratedSymbols: true},
	"skill":                      {Dir: "skill", Package: "skill", Split: true, PrefixGeneratedSymbols: true},
	"settings_agent":             {Dir: "agent", Package: "agent", Split: true, PrefixGeneratedSymbols: true},
	"settings_agent_tool":        {Dir: "agent", Package: "agent", Split: true, PrefixGeneratedSymbols: true},
	"settings_library":           {Dir: "library", Package: "library", Split: true, PrefixGeneratedSymbols: true},
	"settings_skill":             {Dir: "skill", Package: "skill", Split: true, PrefixGeneratedSymbols: true},
	"settings_provider":          {Dir: "controlplane", Package: "controlplane", Split: true, PrefixGeneratedSymbols: true},
	"settings_default_model":     {Dir: "controlplane", Package: "controlplane", Split: true, PrefixGeneratedSymbols: true},
	"settings_embedding_setting": {Dir: "controlplane", Package: "controlplane", Split: true, PrefixGeneratedSymbols: true},
	"settings_plugin":            {Dir: "controlplane", Package: "controlplane", Split: true, PrefixGeneratedSymbols: true},
	"settings_mcp":               {Dir: "mcp", Package: "mcp", Split: true, PrefixGeneratedSymbols: true},
}

var generatedNameFallbacks = map[string]map[string]string{
	"goal":     {"CreateInput": "ToolCreateInput"},
	"workflow": {"SaveInput": "ToolSaveInput"},
}

// toolDecl is one model-facing tool, whatever it was declared from. Everything
// after collection — validation, naming, rendering — works on this shape only.
type toolDecl struct {
	Family      string
	Resource    string
	Action      string
	Name        string
	PluginID    string
	Namespace   string
	LocalName   string
	Description string
	Schema      map[string]any
	Required    []string
	Batch       string
	ItemSchema  map[string]any
	Package     domainPackage
	// Declared is true when the tool came from api/spec/agent-tools rather than
	// from an HTTP operation, so its description is model-facing prose written
	// for the tool and belongs in the generated file.
	Declared bool
	// SourceLocation names the declaration in a validation error, so the fix
	// lands in the spec rather than in the generated file.
	SourceLocation string
}

func parseDoc(data []byte) (*openAPIDoc, error) {
	var doc openAPIDoc
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("parse OpenAPI: %w", err)
	}
	if len(doc.Paths) == 0 || doc.Components.Schemas == nil {
		return nil, fmt.Errorf("OpenAPI paths/components missing")
	}
	return &doc, nil
}

// mergeComponentSchemas restores schemas referenced only by x-agent-tool.
// Redocly keeps those annotation refs but prunes their otherwise-unreachable
// component definitions from docs_spec.yaml; the assembled spec is the
// spec-first source of truth for resolving them.
func mergeComponentSchemas(doc *openAPIDoc, file string) error {
	data, err := os.ReadFile(file)
	if os.IsNotExist(err) {
		// Isolated renderer tests pass a temporary bundled spec without the
		// repository-level component bundle. They cannot declare an external
		// tool input, so there is nothing to merge.
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", file, err)
	}
	var components struct {
		Components struct {
			Schemas map[string]any `yaml:"schemas"`
		} `yaml:"components"`
	}
	if err := yaml.Unmarshal(data, &components); err != nil {
		return fmt.Errorf("parse %s: %w", file, err)
	}
	maps.Copy(doc.Components.Schemas, components.Components.Schemas)
	return nil
}

func collectOperationTools(doc *openAPIDoc) ([]toolDecl, error) {
	var out []toolDecl
	resolver := schemaResolver{schemas: doc.Components.Schemas, stack: map[string]bool{}, refPrefixes: operationRefPrefixes}
	for _, path := range sortedKeysOf(doc.Paths) {
		pathItem, ok := doc.Paths[path].(map[string]any)
		if !ok {
			continue
		}
		pathParams := toSlice(pathItem["parameters"])
		for _, method := range []string{"get", "post", "put", "patch", "delete"} {
			rawOp, ok := pathItem[method]
			if !ok {
				continue
			}
			op, ok := rawOp.(map[string]any)
			if !ok {
				continue
			}
			where := fmt.Sprintf("%s %s", strings.ToUpper(method), path)
			specs, err := parseActionSpecs(op["x-agent-tool"])
			if err != nil {
				return nil, fmt.Errorf("%s: %w", where, err)
			}
			if len(specs) == 0 {
				continue
			}
			params := append([]any{}, pathParams...)
			params = append(params, toSlice(op["parameters"])...)
			bodySchema, err := requestBodySchema(resolver, op)
			if err != nil {
				return nil, fmt.Errorf("%s body: %w", where, err)
			}
			for _, spec := range specs {
				toolBodySchema := bodySchema
				if spec.Input != nil {
					toolBodySchema, err = resolver.resolve(spec.Input)
					if err != nil {
						return nil, fmt.Errorf("%s tool input: %w", where, err)
					}
				}
				pkg, ok := domainPackages[spec.Tool]
				if !ok {
					return nil, fmt.Errorf("%s: tool %q has no package mapping", where, spec.Tool)
				}
				schema, err := paramsInputSchema(resolver, params, spec.resourceOrFamily())
				if err != nil {
					return nil, fmt.Errorf("%s params: %w", where, err)
				}
				var itemSchema map[string]any
				switch {
				case spec.Batch != "":
					itemSchema = cloneMap(toolBodySchema)
					for field := range identityFields {
						deleteProperty(itemSchema, field)
					}
					addProperties(itemSchema, spec.Add)
					schema = batchInputSchema(spec.Batch, itemSchema)
				default:
					if spec.useBody() && toolBodySchema != nil {
						mergeObjectSchema(schema, toolBodySchema)
					}
					addProperties(schema, spec.Add)
				}
				for _, name := range append(sortedKeysOf(spec.Fixed), spec.Omit...) {
					deleteProperty(schema, name)
					deleteProperty(itemSchema, name)
				}
				renameProperties(schema, spec.Rename)
				renameProperties(itemSchema, spec.Rename)
				applyRestrictions(schema, spec.Restrict)
				applyRequired(schema, spec.Require)
				applyOptional(schema, spec.Optional)
				applyPreserveEmpty(schema, spec.PreserveEmpty)
				name, pluginID, namespace, localName, err := generatedToolIdentity(pkg, spec.Tool, spec.Resource, spec.Action, spec.NameOverride)
				if err != nil {
					return nil, fmt.Errorf("%s: %w", where, err)
				}
				out = append(out, toolDecl{
					Family:         spec.Tool,
					Resource:       spec.Resource,
					Action:         spec.Action,
					Name:           name,
					PluginID:       pluginID,
					Namespace:      namespace,
					LocalName:      localName,
					Description:    operationDescription(spec, op),
					Schema:         schema,
					Required:       stringSlice(schema["required"]),
					Batch:          spec.Batch,
					ItemSchema:     itemSchema,
					Package:        pkg,
					SourceLocation: fmt.Sprintf("%s (x-agent-tool %s/%s)", where, spec.Tool, spec.Action),
				})
			}
		}
	}
	return out, nil
}

// operationDescription falls back to the operation summary: an annotation that
// adds nothing to what the endpoint already says should not have to repeat it.
// Split families keep their model-facing prose in the hand-written adapter,
// where it sits next to the handler it describes.
func operationDescription(spec actionSpec, op map[string]any) string {
	if spec.Description != "" {
		return spec.Description
	}
	if summary, _ := op["summary"].(string); summary != "" {
		return summary
	}
	desc, _ := op["description"].(string)
	return desc
}

func (s actionSpec) resourceOrFamily() string {
	if s.Resource != "" {
		return s.Resource
	}
	return s.Tool
}

func parseActionSpecs(raw any) ([]actionSpec, error) {
	if raw == nil {
		return nil, nil
	}
	items, ok := raw.([]any)
	if !ok {
		items = []any{raw}
	}
	specs := make([]actionSpec, 0, len(items))
	for _, item := range items {
		spec, err := decodeStrict[actionSpec](item)
		if err != nil {
			return nil, fmt.Errorf("x-agent-tool: %w", err)
		}
		if spec.Tool == "" || spec.Action == "" {
			return nil, fmt.Errorf("x-agent-tool requires tool and action")
		}
		specs = append(specs, spec)
	}
	return specs, nil
}

// decodeStrict re-encodes a parsed YAML node and decodes it with KnownFields,
// so a mistyped modifier ("resources", "renames") fails the build instead of
// being silently ignored and shipping a schema nobody asked for.
func decodeStrict[T any](raw any) (T, error) {
	var out T
	data, err := yaml.Marshal(raw)
	if err != nil {
		return out, err
	}
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(true)
	if err := dec.Decode(&out); err != nil {
		return out, err
	}
	return out, nil
}

// standaloneFile is one api/spec/agent-tools/<domain>.yaml. family and package
// are file-level defaults; a tool may override either.
type standaloneFile struct {
	Family  string           `yaml:"family"`
	Package string           `yaml:"package"`
	Tools   []standaloneTool `yaml:"tools"`
}

type standaloneTool struct {
	Family       string   `yaml:"family"`
	Package      string   `yaml:"package"`
	Resource     string   `yaml:"resource"`
	Action       string   `yaml:"action"`
	NameOverride string   `yaml:"name_override"`
	Description  string   `yaml:"description"`
	Input        any      `yaml:"input"`
	Required     []string `yaml:"required"`
	Batch        string   `yaml:"batch"`
}

// collectStandaloneTools reads the declaration-only source. A missing
// directory is not an error: a checkout with no such tools should not have to
// carry an empty directory to build.
func collectStandaloneTools(dir string, doc *openAPIDoc) ([]toolDecl, error) {
	entries, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return nil, err
	}
	sort.Strings(entries)
	resolver := schemaResolver{schemas: doc.Components.Schemas, stack: map[string]bool{}, refPrefixes: bundledRefPrefixes}
	var out []toolDecl
	for _, file := range entries {
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}
		var raw any
		if err := yaml.Unmarshal(data, &raw); err != nil {
			return nil, fmt.Errorf("%s: %w", file, err)
		}
		decl, err := decodeStrict[standaloneFile](raw)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", file, err)
		}
		for i, tool := range decl.Tools {
			family := firstNonEmpty(tool.Family, decl.Family)
			pkgPath := firstNonEmpty(tool.Package, decl.Package)
			where := fmt.Sprintf("%s#%d (%s/%s)", file, i, family, tool.Action)
			if family == "" || tool.Action == "" {
				return nil, fmt.Errorf("%s: family and action are required", where)
			}
			if pkgPath == "" {
				return nil, fmt.Errorf("%s: package is required", where)
			}
			schema, err := resolver.resolve(tool.Input)
			if err != nil {
				return nil, fmt.Errorf("%s input: %w", where, err)
			}
			schema = cloneMap(schema)
			if schema["type"] == nil {
				schema["type"] = "object"
			}
			if schema["properties"] == nil {
				schema["properties"] = map[string]any{}
			}
			var itemSchema map[string]any
			if tool.Batch != "" {
				itemSchema = schema
				schema = batchInputSchema(tool.Batch, itemSchema)
			}
			for _, name := range tool.Required {
				addRequired(schema, name)
			}
			pkg := domainPackage{Root: "internal", Dir: pkgPath, Package: path.Base(pkgPath), Split: true}
			if mapped, ok := domainPackages[family]; ok && mapped.Dir == pkgPath {
				pkg = mapped
			}
			name, pluginID, namespace, localName, err := generatedToolIdentity(pkg, family, tool.Resource, tool.Action, tool.NameOverride)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", where, err)
			}
			out = append(out, toolDecl{
				Family:      family,
				Resource:    tool.Resource,
				Action:      tool.Action,
				Name:        name,
				PluginID:    pluginID,
				Namespace:   namespace,
				LocalName:   localName,
				Description: tool.Description,
				Schema:      schema,
				Required:    stringSlice(schema["required"]),
				Batch:       tool.Batch,
				ItemSchema:  itemSchema,
				Declared:    true,
				// A declaration-only family is split by construction: there is
				// no union to preserve, and one tool per action is the rule.
				Package:        pkg,
				SourceLocation: where,
			})
		}
	}
	return out, nil
}

var (
	// providerToolNameRE is the intersection of what OpenAI-compatible and
	// Anthropic providers accept for a function name.
	providerToolNameRE = regexp.MustCompile(`^[a-zA-Z0-9_-]+$`)
	propertyNameRE     = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
)

const maxProviderToolNameLen = 64

// validate checks the whole declaration set at once and reports every
// violation with its source, so a spec author fixes them in one pass instead of
// rediscovering the next one on the next build.
func validate(decls []toolDecl) error {
	var problems []string
	report := func(decl toolDecl, format string, args ...any) {
		problems = append(problems, fmt.Sprintf("%s: %s", decl.SourceLocation, fmt.Sprintf(format, args...)))
	}
	seenAction := map[string]string{}
	type dirOwner struct {
		family string
		pkg    domainPackage
	}
	seenDir := map[string]dirOwner{}
	// providerNames is what the model actually sees: one name per split tool,
	// one name per union family.
	providerNames := map[string][]toolDecl{}
	seenPluginNamespaces := map[string]string{}
	seenPluginIDs := map[string]string{}
	for _, decl := range decls {
		if decl.Description == "" {
			report(decl, "tool has no description")
		}
		pkg := decl.Package
		if (pkg.PluginID == "") != (pkg.Namespace == "") {
			report(decl, "plugin package mapping must provide both plugin ID and namespace")
		}
		if pkg.PluginID == "" {
			if decl.PluginID != "" || decl.Namespace != "" || decl.LocalName != "" {
				report(decl, "core tool must not carry plugin identity metadata")
			}
		} else {
			if decl.PluginID != pkg.PluginID || decl.Namespace != pkg.Namespace || decl.LocalName == "" {
				report(decl, "generated plugin metadata does not match its authored package mapping")
			}
			if !providerToolNameRE.MatchString(pkg.Namespace) || strings.Contains(pkg.Namespace, "__") {
				report(decl, "plugin namespace %q must use provider-safe characters and cannot contain __", pkg.Namespace)
			}
			if !providerToolNameRE.MatchString(decl.LocalName) {
				report(decl, "local tool name %q must match %s", decl.LocalName, providerToolNameRE)
			}
			expectedName := pkg.Namespace + "__" + decl.LocalName
			if decl.Name != expectedName {
				report(decl, "exported plugin tool name %q does not match namespace/local metadata, want %q", decl.Name, expectedName)
			}
			if prior, ok := seenPluginNamespaces[pkg.Namespace]; ok && prior != pkg.PluginID {
				report(decl, "plugin namespace %q is already authored by plugin %q", pkg.Namespace, prior)
			} else {
				seenPluginNamespaces[pkg.Namespace] = pkg.PluginID
			}
			if prior, ok := seenPluginIDs[pkg.PluginID]; ok && prior != pkg.Namespace {
				report(decl, "plugin %q is already authored with namespace %q", pkg.PluginID, prior)
			} else {
				seenPluginIDs[pkg.PluginID] = pkg.Namespace
			}
		}
		dirKey := outputDirKey(decl.Package)
		if other, ok := seenDir[dirKey]; ok && other.family != decl.Family {
			if !other.pkg.PrefixGeneratedSymbols || !decl.Package.PrefixGeneratedSymbols {
				report(decl, "package %q is already generated for family %q; all families sharing a package must prefix generated symbols", decl.Package.Dir, other.family)
			}
		} else {
			seenDir[dirKey] = dirOwner{family: decl.Family, pkg: decl.Package}
		}
		actionKey := decl.Family + "/" + decl.Action
		if other, ok := seenAction[actionKey]; ok {
			report(decl, "action %q is already declared at %s", actionKey, other)
		}
		seenAction[actionKey] = decl.SourceLocation
		name := decl.Family
		if decl.Package.Split {
			name = decl.Name
		}
		providerNames[name] = append(providerNames[name], decl)
		for _, prop := range sortedPropertyNames(decl.Schema) {
			if !propertyNameRE.MatchString(prop) {
				report(decl, "property %q must match %s (snake_case, no camelCase ids)", prop, propertyNameRE)
			}
		}
		for _, prop := range sortedPropertyNames(decl.ItemSchema) {
			if !propertyNameRE.MatchString(prop) {
				report(decl, "batch item property %q must match %s", prop, propertyNameRE)
			}
		}
		// A required entry with no property behind it is a schema no argument
		// can satisfy: the provider refuses to call, and the model has no field
		// to supply. Usually a typo, or a `required` naming a field the $ref
		// does not have.
		props := propertyMap(decl.Schema)
		for _, name := range decl.Required {
			if _, ok := props[name]; !ok {
				report(decl, "required field %q is not a property of this tool; the schema cannot be satisfied", name)
			}
		}
		itemProps := propertyMap(decl.ItemSchema)
		for _, name := range stringSlice(decl.ItemSchema["required"]) {
			if _, ok := itemProps[name]; !ok {
				report(decl, "required batch item field %q is not a property of the item", name)
			}
		}
		if decl.Package.Split {
			if _, ok := propertyMap(decl.Schema)["action"]; ok {
				report(decl, "split tool schema must not carry an `action` property; the tool name carries the action")
			}
		}
	}
	for _, name := range sortedKeysOf(providerNames) {
		owners := providerNames[name]
		first := owners[0]
		if !providerToolNameRE.MatchString(name) || len(name) > maxProviderToolNameLen {
			report(first, "tool name %q must match %s and be at most %d characters", name, providerToolNameRE, maxProviderToolNameLen)
		}
		// A union family legitimately owns one name across all its actions; two
		// different families reaching for the same name is the collision that
		// silently shadows a tool at registration.
		for _, other := range owners[1:] {
			if other.Family != first.Family || first.Package.Split {
				report(other, "tool name %q is already declared at %s", name, first.SourceLocation)
			}
		}
	}
	if len(problems) == 0 {
		return nil
	}
	sort.Strings(problems)
	return fmt.Errorf("invalid agent tool declarations:\n  %s", strings.Join(problems, "\n  "))
}

func groupByOutput(decls []toolDecl) map[string][]toolDecl {
	out := map[string][]toolDecl{}
	for _, decl := range decls {
		key := decl.Family + "\x00" + outputDirKey(decl.Package)
		out[key] = append(out[key], decl)
	}
	for _, group := range out {
		sort.Slice(group, func(i, j int) bool { return group[i].Action < group[j].Action })
	}
	return out
}

func outputDirKey(pkg domainPackage) string {
	root := pkg.Root
	if root == "" {
		root = "internal"
	}
	return root + "\x00" + pkg.Dir
}

// toolName is the model-facing name: family_resource_action, with the resource
// dropped when it repeats the family. name_override exists for the rare case
// where the object is the payload rather than the resource being created
// (share_create_artifact); see rules/agent-tools.md §4.
func toolName(family, resource, action, override string) string {
	if override != "" {
		return override
	}
	parts := []string{family}
	if resource != "" && resource != family {
		parts = append(parts, resource)
	}
	return strings.Join(append(parts, action), "_")
}

// generatedToolIdentity is the only place where a generated plugin tool gets
// its exported name. The package mapping is authored at the generator
// composition root, while local names remain the operation's stable family
// grammar. Core tools intentionally keep the historical name and have no
// plugin identity metadata.
func generatedToolIdentity(pkg domainPackage, family, resource, action, override string) (name, pluginID, namespace, localName string, err error) {
	legacyName := toolName(family, resource, action, override)
	if pkg.PluginID == "" && pkg.Namespace == "" {
		return legacyName, "", "", "", nil
	}
	if pkg.PluginID == "" || pkg.Namespace == "" {
		return "", "", "", "", fmt.Errorf("plugin package mapping must provide both plugin ID and namespace")
	}
	localName = override
	if localName == "" {
		parts := make([]string, 0, 2)
		if resource != "" && resource != family {
			parts = append(parts, resource)
		}
		parts = append(parts, action)
		localName = strings.Join(parts, "_")
	}
	name = pkg.Namespace + "__" + localName
	return name, pkg.PluginID, pkg.Namespace, localName, nil
}

func paramsInputSchema(resolver schemaResolver, params []any, resource string) (map[string]any, error) {
	schema := map[string]any{"type": "object", "properties": map[string]any{}}
	for _, raw := range params {
		param, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		name, _ := param["name"].(string)
		if name == "" || identityFields[name] {
			continue
		}
		field := toolFieldName(name, resource)
		ps, _ := param["schema"].(map[string]any)
		resolved, err := resolver.resolve(ps)
		if err != nil {
			return nil, err
		}
		props := schema["properties"].(map[string]any)
		props[field] = resolved
		if required, _ := param["required"].(bool); required {
			addRequired(schema, field)
		}
	}
	return schema, nil
}

func requestBodySchema(resolver schemaResolver, op map[string]any) (map[string]any, error) {
	rb, ok := op["requestBody"].(map[string]any)
	if !ok {
		return nil, nil
	}
	content, ok := rb["content"].(map[string]any)
	if !ok {
		return nil, nil
	}
	jsonContent, ok := content["application/json"].(map[string]any)
	if !ok {
		return nil, nil
	}
	rawSchema, ok := jsonContent["schema"].(map[string]any)
	if !ok {
		return nil, nil
	}
	resolved, err := resolver.resolve(rawSchema)
	if err != nil {
		return nil, err
	}
	return resolved, nil
}

func batchInputSchema(field string, item map[string]any) map[string]any {
	return map[string]any{
		"type":     "object",
		"required": []any{field},
		"properties": map[string]any{
			field: map[string]any{"type": "array", "items": item, "minItems": 1, "maxItems": 20},
		},
	}
}

func mergeObjectSchema(dst, src map[string]any) {
	props, _ := src["properties"].(map[string]any)
	for name, prop := range props {
		if identityFields[name] {
			continue
		}
		dst["properties"].(map[string]any)[name] = prop
	}
	for _, req := range stringSlice(src["required"]) {
		if !identityFields[req] {
			addRequired(dst, req)
		}
	}
}

type schemaResolver struct {
	schemas map[string]any
	stack   map[string]bool
	// refPrefixes are the $ref spellings this resolver accepts. An operation
	// annotation is read from the assembled bundle but written next to a spec
	// that uses the relative spelling, so it takes both; a declaration file is
	// resolved only against the bundle, and letting it reach for a relative
	// path would resolve against a directory that has nothing to do with it.
	refPrefixes []string
}

var (
	bundledRefPrefixes   = []string{"#/components/schemas/"}
	operationRefPrefixes = []string{"#/components/schemas/", "../../components.yaml#/components/schemas/"}
)

func (r schemaResolver) resolve(v any) (map[string]any, error) {
	resolved, err := r.resolveAny(v)
	if err != nil {
		return nil, err
	}
	m, ok := resolved.(map[string]any)
	if !ok {
		return map[string]any{}, nil
	}
	return m, nil
}

func (r schemaResolver) resolveAny(v any) (any, error) {
	switch x := v.(type) {
	case map[string]any:
		return r.resolveMap(x)
	case []any:
		out := make([]any, len(x))
		for i, item := range x {
			resolved, err := r.resolveAny(item)
			if err != nil {
				return nil, err
			}
			out[i] = resolved
		}
		return out, nil
	default:
		return x, nil
	}
}

func (r schemaResolver) resolveMap(m map[string]any) (map[string]any, error) {
	if ref, ok := m["$ref"].(string); ok {
		base, err := r.resolveRef(ref)
		if err != nil {
			return nil, err
		}
		for _, key := range sortedKeysOf(m) {
			if key == "$ref" {
				continue
			}
			resolved, err := r.resolveAny(m[key])
			if err != nil {
				return nil, err
			}
			base[key] = resolved
		}
		return base, nil
	}
	merged := map[string]any{}
	if allOf, ok := m["allOf"].([]any); ok {
		for _, item := range allOf {
			resolved, err := r.resolve(item)
			if err != nil {
				return nil, err
			}
			mergeSchema(merged, resolved)
		}
	}
	for _, key := range sortedKeysOf(m) {
		if key == "allOf" {
			continue
		}
		resolved, err := r.resolveAny(m[key])
		if err != nil {
			return nil, err
		}
		if existing, ok := merged[key].(map[string]any); ok {
			if overlay, ok := resolved.(map[string]any); ok {
				mergeSchema(existing, overlay)
				continue
			}
		}
		merged[key] = resolved
	}
	return merged, nil
}

func (r schemaResolver) resolveRef(ref string) (map[string]any, error) {
	name := ""
	for _, prefix := range r.refPrefixes {
		if after, ok := strings.CutPrefix(ref, prefix); ok {
			name = after
			break
		}
	}
	if name == "" {
		return nil, fmt.Errorf("unsupported ref %q: allowed prefixes are %s", ref, strings.Join(r.refPrefixes, ", "))
	}
	if r.stack[name] {
		return nil, fmt.Errorf("cyclic schema ref %q", ref)
	}
	schema, ok := r.schemas[name]
	if !ok {
		return nil, fmt.Errorf("schema %q not found", name)
	}
	r.stack[name] = true
	resolved, err := r.resolve(schema)
	delete(r.stack, name)
	if err != nil {
		return nil, err
	}
	return cloneMap(resolved), nil
}

func renderTool(family string, pkg domainPackage, decls []toolDecl) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by go run ./internal/tools/toolgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", pkg.Package)
	out.WriteString("import (\n\t\"context\"\n\t\"fmt\"\n\n")
	if pkg.Split {
		out.WriteString("\t\"github.com/CherryHQ/stella/pkg/toolmeta\"\n")
	}
	out.WriteString("\t\"github.com/CherryHQ/stella/pkg/tools\"\n)\n\n")
	if pkg.Split {
		if err := renderSplitSchemas(&out, family, pkg, decls); err != nil {
			return nil, err
		}
	} else {
		fmt.Fprintf(&out, "const %s = %q\n\n", generatedSymbol(pkg, family, "ToolName"), family)
		schemaJSON, err := json.MarshalIndent(toolSchema(decls), "", "  ")
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "func %s() map[string]any {\n", generatedSymbol(pkg, family, "InputSchema"))
		fmt.Fprintf(&out, "\treturn tools.MustInputSchema(%s)\n", generatedSymbol(pkg, family, "InputSchemaJSON"))
		out.WriteString("}\n\n")
		fmt.Fprintf(&out, "const %s = `", generatedSymbol(pkg, family, "InputSchemaJSON"))
		out.Write(schemaJSON)
		out.WriteString("`\n\n")
	}
	fmt.Fprintf(&out, "type %s interface {\n", generatedSymbol(pkg, family, "Handler"))
	for _, decl := range decls {
		fmt.Fprintf(&out, "\t%s(context.Context, %s) (any, error)\n", exportName(decl.Action), inputTypeName(decl))
	}
	out.WriteString("}\n\n")
	for _, decl := range decls {
		if decl.Batch != "" {
			fmt.Fprintf(&out, "type %s struct {\n", itemTypeName(decl))
			required := requiredSet(stringSlice(decl.ItemSchema["required"]))
			for _, prop := range sortedPropertyNames(decl.ItemSchema) {
				fieldName := exportName(camel(prop))
				fmt.Fprintf(&out, "\t%s %s `json:\"%s,omitempty\"`\n", fieldName, goType(propertyMap(decl.ItemSchema)[prop], required[prop]), prop)
			}
			out.WriteString("}\n\n")
		}
		fmt.Fprintf(&out, "type %s struct {\n", inputTypeName(decl))
		if decl.Batch != "" {
			fmt.Fprintf(&out, "\tItems []%s `json:\"%s,omitempty\"`\n", itemTypeName(decl), decl.Batch)
		} else {
			required := requiredSet(decl.Required)
			for _, prop := range sortedPropertyNames(decl.Schema) {
				fieldName := exportName(camel(prop))
				fmt.Fprintf(&out, "\t%s %s `json:\"%s,omitempty\"`\n", fieldName, goType(propertyMap(decl.Schema)[prop], required[prop]), prop)
			}
		}
		out.WriteString("}\n\n")
	}
	// A split tool's schema is exact, so an argument it does not declare is a
	// mistake worth reporting; a union tool's hoisted schema legitimately
	// carries every action's fields and must keep decoding leniently.
	decode := "DecodeInput"
	if pkg.Split {
		decode = "DecodeInputStrict"
	}
	fmt.Fprintf(&out, "func %s(ctx context.Context, h %s, action string, args map[string]any) (any, error) {\n", generatedSymbol(pkg, family, "Dispatch"), generatedSymbol(pkg, family, "Handler"))
	out.WriteString("\tswitch action {\n")
	for _, decl := range decls {
		fmt.Fprintf(&out, "\tcase %q:\n", decl.Action)
		fmt.Fprintf(&out, "\t\tvar in %s\n", inputTypeName(decl))
		fmt.Fprintf(&out, "\t\tif err := tools.%s(args, &in, %#v); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", decode, decl.Required)
		fmt.Fprintf(&out, "\t\treturn h.%s(ctx, in)\n", exportName(decl.Action))
	}
	out.WriteString("\tdefault:\n")
	fmt.Fprintf(&out, "\t\treturn nil, fmt.Errorf(\"unknown %s action %%q\", action)\n", family)
	out.WriteString("\t}\n}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated %s: %w\n%s", family, err, out.String())
	}
	return formatted, nil
}

// renderSplitSchemas emits one exact schema per action plus the registry the
// package uses to build one Tool per action. Each schema carries only its own
// action's fields and its own `required`, so a wrong parameter is rejected by
// the provider instead of being silently dropped by DecodeInput.
func renderSplitSchemas(out *bytes.Buffer, family string, pkg domainPackage, decls []toolDecl) error {
	toolPrefix := generatedSymbol(pkg, family, "ToolPrefix")
	actionTool := generatedSymbol(pkg, family, "ActionTool")
	actionTools := generatedSymbol(pkg, family, "ActionTools")
	toolNames := generatedSymbol(pkg, family, "ToolNames")
	fmt.Fprintf(out, "// %s is the family every generated %s tool name starts with.\n", toolPrefix, family)
	fmt.Fprintf(out, "const %s = %q\n\n", toolPrefix, family)
	fmt.Fprintf(out, "// %s describes one generated tool: an exact schema bound to one action.\n", actionTool)
	fmt.Fprintf(out, "type %s = toolmeta.ActionTool\n\n", actionTool)
	fmt.Fprintf(out, "// %s lists every generated tool in a stable order.\n", actionTools)
	fmt.Fprintf(out, "func %s() []%s {\n\treturn []%s{\n", actionTools, actionTool, actionTool)
	for _, decl := range decls {
		schemaJSON, err := json.MarshalIndent(actionSchema(decl), "", "  ")
		if err != nil {
			return err
		}
		fmt.Fprintf(out, "\t\t{Name: %q, ", decl.Name)
		if decl.PluginID != "" {
			fmt.Fprintf(out, "PluginID: %q, Namespace: %q, LocalName: %q, ", decl.PluginID, decl.Namespace, decl.LocalName)
		}
		fmt.Fprintf(out, "Family: %q, ", decl.Family)
		if decl.Resource != "" {
			fmt.Fprintf(out, "Resource: %q, ", decl.Resource)
		}
		fmt.Fprintf(out, "Action: %q, ", decl.Action)
		// An HTTP summary is written for API readers, so only a declared
		// description is good enough to put in front of a model; an
		// operation-backed family keeps its prose in the adapter.
		if decl.Declared && decl.Description != "" {
			fmt.Fprintf(out, "Description: %q, ", decl.Description)
		}
		fmt.Fprintf(out, "InputSchemaJSON: `%s`},\n", schemaJSON)
	}
	out.WriteString("\t}\n}\n\n")
	fmt.Fprintf(out, "// %s lists every generated tool name, for callers that gate on names.\n", toolNames)
	fmt.Fprintf(out, "func %s() []string {\n\tnames := make([]string, 0, len(%s()))\n", toolNames, actionTools)
	fmt.Fprintf(out, "\tfor _, spec := range %s() {\n\t\tnames = append(names, spec.Name)\n\t}\n\treturn names\n}\n\n", actionTools)
	return nil
}

// actionSchema is one action's exact input: its own properties and its own
// required list, with no `action` discriminator because the tool name carries
// it. additionalProperties:false is what makes the split worth doing — without
// it the provider still accepts a field the tool has no idea what to do with.
// A batch action already carries its batch field in Schema, so both shapes take
// the same path; the item object is sealed too.
func actionSchema(decl toolDecl) map[string]any {
	properties := map[string]any{}
	for name, raw := range propertyMap(decl.Schema) {
		if name == "action" {
			continue
		}
		// This marker affects Go's presence-aware input type only. It is not a
		// provider-facing JSON Schema keyword, so strip it before publishing the
		// otherwise standard nullable schema.
		if property, ok := raw.(map[string]any); ok {
			property = cloneMap(property)
			delete(property, "x-stella-preserve-empty")
			properties[name] = property
			continue
		}
		properties[name] = raw
	}
	required := make([]any, 0, len(decl.Required))
	for _, name := range decl.Required {
		required = append(required, name)
	}
	schema := map[string]any{"type": "object", "properties": properties, "additionalProperties": false}
	if len(required) > 0 {
		schema["required"] = required
	}
	sealItemObjects(schema)
	return schema
}

// sealItemObjects adds additionalProperties:false to array item objects one
// level down (the batch shape). A property that declares its own
// additionalProperties — a free-form metadata map — is left exactly as it is.
func sealItemObjects(schema map[string]any) {
	for _, raw := range propertyMap(schema) {
		prop, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		item, ok := prop["items"].(map[string]any)
		if !ok {
			continue
		}
		if _, declared := item["additionalProperties"]; !declared && item["properties"] != nil {
			item["additionalProperties"] = false
		}
	}
}

func propertyMap(schema map[string]any) map[string]any {
	props, _ := schema["properties"].(map[string]any)
	return props
}

func toolSchema(decls []toolDecl) map[string]any {
	enum := make([]any, 0, len(decls))
	for _, decl := range decls {
		enum = append(enum, decl.Action)
	}
	// Hoist the union of every action's fields into the top-level `properties` so
	// a model sees all possible parameters up front. The schema must stay a plain
	// object: OpenAI-compatible providers reject function schemas that carry
	// oneOf/anyOf/allOf/enum/const/not at the top level, so per-action
	// requiredness and constraints cannot be expressed structurally — they ride
	// in generated descriptions for the model and Dispatch/DecodeInput enforce
	// them at runtime. Top-level `required` stays [action] only.
	properties := hoistProperties(decls)
	actionProp := map[string]any{"type": "string", "enum": enum}
	if desc := actionRequiredDescription(decls); desc != "" {
		actionProp["description"] = desc
	}
	properties["action"] = actionProp
	return map[string]any{
		"type":       "object",
		"required":   []any{"action"},
		"properties": properties,
	}
}

// actionRequiredDescription lists each action's required parameters (the exact
// lists DecodeInput enforces) so the model sees them despite the flattened
// top-level `required` staying [action] only.
func actionRequiredDescription(decls []toolDecl) string {
	parts := make([]string, 0, len(decls))
	for _, decl := range decls {
		if len(decl.Required) == 0 {
			continue
		}
		parts = append(parts, fmt.Sprintf("%s(%s)", decl.Action, strings.Join(decl.Required, ", ")))
	}
	if len(parts) == 0 {
		return ""
	}
	return "Required parameters by action: " + strings.Join(parts, "; ") + "."
}

// propVariant is one action's schema for a shared field name.
type propVariant struct {
	action string
	schema map[string]any
}

// hoistProperties merges the field schemas across every action (excluding
// `action`, handled separately). When actions agree on a field's schema it is
// copied verbatim; when they disagree the hoisted copy is loosened to type +
// description only, so the top-level descriptor can never contradict what the
// action's Dispatch decoding actually accepts.
func hoistProperties(decls []toolDecl) map[string]any {
	variants := map[string][]propVariant{}
	var order []string
	for _, decl := range decls {
		for name, raw := range propertyMap(decl.Schema) {
			if name == "action" {
				continue
			}
			ps, _ := raw.(map[string]any)
			if _, seen := variants[name]; !seen {
				order = append(order, name)
			}
			variants[name] = append(variants[name], propVariant{action: decl.Action, schema: ps})
		}
	}
	sort.Strings(order)
	out := map[string]any{}
	for _, name := range order {
		vs := variants[name]
		identical := true
		for _, v := range vs[1:] {
			if !schemaEqual(vs[0].schema, v.schema) {
				identical = false
				break
			}
		}
		if identical {
			out[name] = cloneMap(vs[0].schema)
		} else {
			out[name] = loosenProperty(vs)
		}
	}
	return out
}

// loosenProperty reduces a set of divergent field schemas to a conflict-free
// descriptor. `type` is kept only when every variant agrees on it — otherwise it
// is dropped and the description names each action's expected type instead
// (e.g. `inputs` is an object for one action and an array for another), since
// the flattened schema cannot express per-action shapes structurally.
// Enum/const/format and other per-action constraints are dropped here;
// Dispatch/DecodeInput and the backing service validation gate a call.
func loosenProperty(vs []propVariant) map[string]any {
	out := map[string]any{}
	unanimous := true
	if sharedType, ok := vs[0].schema["type"]; ok {
		for _, v := range vs[1:] {
			if t, has := v.schema["type"]; !has || t != sharedType {
				unanimous = false
				break
			}
		}
		if unanimous {
			out["type"] = sharedType
		}
	} else {
		unanimous = false
	}
	var desc string
	for _, v := range vs {
		if d, ok := v.schema["description"].(string); ok {
			desc = d
			break
		}
	}
	if !unanimous {
		parts := make([]string, 0, len(vs))
		for _, v := range vs {
			t, _ := v.schema["type"].(string)
			if t == "" {
				t = "any"
			}
			parts = append(parts, v.action+": "+t)
		}
		note := "Type depends on action — " + strings.Join(parts, "; ") + "."
		if desc != "" {
			desc += " " + note
		} else {
			desc = note
		}
	}
	if desc != "" {
		out["description"] = desc
	}
	return out
}

func schemaEqual(a, b map[string]any) bool {
	ab, err1 := json.Marshal(a)
	bb, err2 := json.Marshal(b)
	if err1 != nil || err2 != nil {
		return false
	}
	return bytes.Equal(ab, bb)
}

func goType(schema any, required bool) string {
	m, _ := schema.(map[string]any)
	t, _ := m["type"].(string)
	switch t {
	case "string":
		// preserve_empty marks the few patch fields where an explicit empty string
		// differs from omission. Do not make all nullable OpenAPI strings pointers:
		// nullable describes HTTP transport, while this marker is model-tool input
		// presence and would otherwise change unrelated generated adapters.
		if !required && m["x-stella-preserve-empty"] == true {
			return "*string"
		}
		return "string"
	case "boolean":
		if required {
			return "bool"
		}
		return "*bool"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "array":
		return "[]any"
	case "object":
		if value, ok := m["additionalProperties"].(map[string]any); ok && value["additionalProperties"] == false {
			return "map[string]" + closedObjectType(value)
		}
	}
	return "map[string]any"
}

// closedObjectType keeps a recursively sealed OpenAPI object concrete in the
// generated input. map[string]any would make json.Decoder's DisallowUnknownFields
// stop at the map boundary, letting forbidden nested fields reach Code Mode IO.
func closedObjectType(schema map[string]any) string {
	required := requiredSet(stringSlice(schema["required"]))
	var out strings.Builder
	out.WriteString("struct {\n")
	for _, prop := range sortedPropertyNames(schema) {
		fieldSchema := propertyMap(schema)[prop]
		fmt.Fprintf(&out, "\t%s %s `json:\"%s,omitempty\"`\n", exportName(camel(prop)), closedObjectFieldType(fieldSchema, required[prop]), prop)
	}
	out.WriteString("}")
	return out.String()
}

func closedObjectFieldType(schema any, required bool) string {
	m, _ := schema.(map[string]any)
	if m["type"] == "object" && m["additionalProperties"] == false {
		return closedObjectType(m)
	}
	if m["type"] == "array" {
		return "[]" + closedObjectFieldType(m["items"], true)
	}
	return goType(schema, required)
}

// generatedSymbol gives families that share a package a namespace without
// changing legacy generated APIs. Prefix every generated top-level symbol, not
// just inputs: ActionTools and Dispatch collide just as surely as UpdateInput.
func generatedSymbol(pkg domainPackage, family, name string) string {
	if pkg.PrefixGeneratedSymbols {
		return exportName(family) + name
	}
	return name
}

// inputTypeName is the generated Go input type for one tool. Standalone
// declarations and explicitly prefixed operation families carry their family
// name so they can coexist with hand-written or sibling-family types.
func inputTypeName(decl toolDecl) string {
	if decl.Declared || decl.Package.PrefixGeneratedSymbols {
		return exportName(decl.Family) + exportName(decl.Action) + "Input"
	}
	name := exportName(decl.Action) + "Input"
	if fallback := generatedNameFallbacks[decl.Family][name]; fallback != "" {
		return fallback
	}
	return name
}

func itemTypeName(decl toolDecl) string {
	return strings.TrimSuffix(inputTypeName(decl), "Input") + "Item"
}

func sortedPropertyNames(schema map[string]any) []string {
	props := propertyMap(schema)
	keys := make([]string, 0, len(props))
	for k := range props {
		if k != "action" {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	return keys
}

// toolFieldName maps an OpenAPI parameter name to its tool property name. A
// path parameter naming the tool's own resource ({jobId} on a job tool) becomes
// the model-friendly `id`; any other {xId}/{x_id} becomes `x_id`. This is a
// rule rather than a per-name table so the next domain needs no entry —
// see rules/agent-tools.md §4.
func toolFieldName(name, resource string) string {
	base, ok := trimIDSuffix(name)
	if !ok {
		return name
	}
	if base == "" || base == resource {
		return "id"
	}
	return base + "_id"
}

// trimIDSuffix splits an identifier parameter into its subject: "jobId" and
// "job_id" both yield "job", "id" yields "", and a name that merely ends in the
// letters "id" ("uid") is not an identifier parameter at all.
func trimIDSuffix(name string) (string, bool) {
	if name == "id" {
		return "", true
	}
	if base, ok := strings.CutSuffix(name, "_id"); ok && base != "" {
		return snakeCase(base), true
	}
	if base, ok := strings.CutSuffix(name, "Id"); ok && base != "" {
		return snakeCase(base), true
	}
	return "", false
}

func snakeCase(s string) string {
	var out strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				out.WriteByte('_')
			}
			out.WriteRune(r - 'A' + 'a')
			continue
		}
		out.WriteRune(r)
	}
	return out.String()
}

func addProperties(schema map[string]any, additions map[string]any) {
	if len(additions) == 0 {
		return
	}
	props, _ := schema["properties"].(map[string]any)
	if props == nil {
		props = map[string]any{}
		schema["properties"] = props
	}
	for name, property := range additions {
		props[name] = cloneValue(property)
	}
}

func applyRestrictions(schema map[string]any, restrict map[string][]any) {
	props := propertyMap(schema)
	for name, allowed := range restrict {
		prop, ok := props[name].(map[string]any)
		if !ok {
			continue
		}
		values := make([]any, len(allowed))
		copy(values, allowed)
		prop["enum"] = values
		if len(values) > 0 {
			prop["default"] = values[0]
		}
	}
}

func applyRequired(schema map[string]any, fields []string) {
	props := propertyMap(schema)
	for _, field := range fields {
		if _, ok := props[field]; ok {
			addRequired(schema, field)
		}
	}
}

func applyOptional(schema map[string]any, fields []string) {
	for _, field := range fields {
		removeRequired(schema, field)
	}
}

// applyPreserveEmpty keeps omission distinct from an explicit empty string in
// a generated tool input. nullable makes the model-facing schema honest, while
// the private extension directs Go generation without leaking that concern into
// the HTTP OpenAPI contract.
func applyPreserveEmpty(schema map[string]any, fields []string) {
	for _, field := range fields {
		property, ok := propertyMap(schema)[field].(map[string]any)
		if !ok {
			continue
		}
		property["nullable"] = true
		property["x-stella-preserve-empty"] = true
	}
}

// renameProperties renames a tool property without touching the HTTP contract.
// It runs before restrict/require so those modifiers name the property as the
// model sees it, and the generated Go field follows from the new name.
func renameProperties(schema map[string]any, rename map[string]string) {
	if schema == nil || len(rename) == 0 {
		return
	}
	props := propertyMap(schema)
	required := requiredSet(stringSlice(schema["required"]))
	for _, from := range sortedKeysOf(rename) {
		to := rename[from]
		prop, ok := props[from]
		if !ok {
			continue
		}
		delete(props, from)
		props[to] = prop
		if required[from] {
			removeRequired(schema, from)
			addRequired(schema, to)
		}
	}
}

func deleteProperty(schema map[string]any, name string) {
	if schema == nil {
		return
	}
	delete(propertyMap(schema), name)
	removeRequired(schema, name)
}

func removeRequired(schema map[string]any, name string) {
	req := stringSlice(schema["required"])
	filtered := make([]any, 0, len(req))
	for _, item := range req {
		if item != name {
			filtered = append(filtered, item)
		}
	}
	if len(filtered) == 0 {
		delete(schema, "required")
	} else {
		schema["required"] = filtered
	}
}

func addRequired(schema map[string]any, name string) {
	seen := map[string]bool{}
	items := stringSlice(schema["required"])
	for _, item := range items {
		seen[item] = true
	}
	if !seen[name] {
		items = append(items, name)
		sort.Strings(items)
	}
	out := make([]any, len(items))
	for i, item := range items {
		out[i] = item
	}
	schema["required"] = out
}

func requiredSet(items []string) map[string]bool {
	out := make(map[string]bool, len(items))
	for _, item := range items {
		out[item] = true
	}
	return out
}

func stringSlice(v any) []string {
	items, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func toSlice(v any) []any {
	items, _ := v.([]any)
	return items
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if v != "" {
			return v
		}
	}
	return ""
}

func mergeSchema(dst, src map[string]any) {
	for k, v := range src {
		if dk, ok := dst[k].(map[string]any); ok {
			if sk, ok := v.(map[string]any); ok {
				mergeSchema(dk, sk)
				continue
			}
		}
		dst[k] = v
	}
}

func cloneValue(value any) any {
	switch value := value.(type) {
	case map[string]any:
		return cloneMap(value)
	case []any:
		items := make([]any, len(value))
		for i, item := range value {
			items[i] = cloneValue(item)
		}
		return items
	default:
		return value
	}
}

func cloneMap(in map[string]any) map[string]any {
	if in == nil {
		return nil
	}
	out := make(map[string]any, len(in))
	for key, value := range in {
		out[key] = cloneValue(value)
	}
	return out
}

func sortedKeysOf[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func exportName(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func camel(s string) string { return exportName(s) }
