// Code generated by go run ./internal/tools/toolgen; DO NOT EDIT.

package scheduler

import (
	"context"
	"fmt"

	"github.com/CherryHQ/stella/pkg/toolmeta"
	"github.com/CherryHQ/stella/pkg/tools"
)

// ToolPrefix is the family every generated scheduler tool name starts with.
const ToolPrefix = "scheduler"

// ActionTool describes one generated tool: an exact schema bound to one action.
type ActionTool = toolmeta.ActionTool

// ActionTools lists every generated tool in a stable order.
func ActionTools() []ActionTool {
	return []ActionTool{
		{Name: "scheduler__job_create", PluginID: "system/scheduler", Namespace: "scheduler", LocalName: "job_create", Family: "scheduler", Resource: "job", Action: "create", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "at": {
      "type": "string"
    },
    "cron": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "every": {
      "type": "string"
    },
    "idempotency_key": {
      "description": "Optional key; repeated creates by the same user with the same key return the existing job.",
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "session_mode": {
      "type": "string"
    },
    "template_key": {
      "description": "Optional. When set, create a subscription instance for this template. name/message are filled from the template; schedule fields may override defaults.",
      "type": "string"
    }
  },
  "type": "object"
}`},
		{Name: "scheduler__job_delete", PluginID: "system/scheduler", Namespace: "scheduler", LocalName: "job_delete", Family: "scheduler", Resource: "job", Action: "delete", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "scheduler__job_get", PluginID: "system/scheduler", Namespace: "scheduler", LocalName: "job_get", Family: "scheduler", Resource: "job", Action: "get", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "scheduler__job_list", PluginID: "system/scheduler", Namespace: "scheduler", LocalName: "job_list", Family: "scheduler", Resource: "job", Action: "list", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {},
  "type": "object"
}`},
		{Name: "scheduler__job_pause", PluginID: "system/scheduler", Namespace: "scheduler", LocalName: "job_pause", Family: "scheduler", Resource: "job", Action: "pause", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "scheduler__job_resume", PluginID: "system/scheduler", Namespace: "scheduler", LocalName: "job_resume", Family: "scheduler", Resource: "job", Action: "resume", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "scheduler__job_update", PluginID: "system/scheduler", Namespace: "scheduler", LocalName: "job_update", Family: "scheduler", Resource: "job", Action: "update", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "at": {
      "type": "string"
    },
    "cron": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "every": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "idempotency_key": {
      "description": "Optional key; repeated creates by the same user with the same key return the existing job.",
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "session_mode": {
      "type": "string"
    },
    "template_key": {
      "description": "Optional. When set, create a subscription instance for this template. name/message are filled from the template; schedule fields may override defaults.",
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
	}
}

// ToolNames lists every generated tool name, for callers that gate on names.
func ToolNames() []string {
	names := make([]string, 0, len(ActionTools()))
	for _, spec := range ActionTools() {
		names = append(names, spec.Name)
	}
	return names
}

type Handler interface {
	Create(context.Context, CreateInput) (any, error)
	Delete(context.Context, DeleteInput) (any, error)
	Get(context.Context, GetInput) (any, error)
	List(context.Context, ListInput) (any, error)
	Pause(context.Context, PauseInput) (any, error)
	Resume(context.Context, ResumeInput) (any, error)
	Update(context.Context, UpdateInput) (any, error)
}

type CreateInput struct {
	At             string `json:"at,omitempty"`
	Cron           string `json:"cron,omitempty"`
	Enabled        *bool  `json:"enabled,omitempty"`
	Every          string `json:"every,omitempty"`
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	Message        string `json:"message,omitempty"`
	Name           string `json:"name,omitempty"`
	SessionMode    string `json:"session_mode,omitempty"`
	TemplateKey    string `json:"template_key,omitempty"`
}

type DeleteInput struct {
	Id string `json:"id,omitempty"`
}

type GetInput struct {
	Id string `json:"id,omitempty"`
}

type ListInput struct {
}

type PauseInput struct {
	Id string `json:"id,omitempty"`
}

type ResumeInput struct {
	Id string `json:"id,omitempty"`
}

type UpdateInput struct {
	At             string `json:"at,omitempty"`
	Cron           string `json:"cron,omitempty"`
	Enabled        *bool  `json:"enabled,omitempty"`
	Every          string `json:"every,omitempty"`
	Id             string `json:"id,omitempty"`
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	Message        string `json:"message,omitempty"`
	Name           string `json:"name,omitempty"`
	SessionMode    string `json:"session_mode,omitempty"`
	TemplateKey    string `json:"template_key,omitempty"`
}

func Dispatch(ctx context.Context, h Handler, action string, args map[string]any) (any, error) {
	switch action {
	case "create":
		var in CreateInput
		if err := tools.DecodeInputStrict(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.Create(ctx, in)
	case "delete":
		var in DeleteInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Delete(ctx, in)
	case "get":
		var in GetInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Get(ctx, in)
	case "list":
		var in ListInput
		if err := tools.DecodeInputStrict(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.List(ctx, in)
	case "pause":
		var in PauseInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Pause(ctx, in)
	case "resume":
		var in ResumeInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Resume(ctx, in)
	case "update":
		var in UpdateInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Update(ctx, in)
	default:
		return nil, fmt.Errorf("unknown scheduler action %q", action)
	}
}
