package toolmeta

import (
	"slices"
	"testing"
)

// builtinInventory is every fixed model-facing tool this build registers, with
// the file that defines its name. "Fixed" excludes the two families whose names
// are only known at runtime — MCP servers and plugins — which HandWritten
// covers by prefix instead.
//
// The guard it powers is one sentence: a builtin is either generated by
// toolgen, or an accepted exception. A tool that is neither means someone
// hand-wrote a schema that toolgen could have owned, and this test is where
// that shows up.
var builtinInventory = []struct {
	name      string
	generated bool
	source    string
}{
	{"bash", false, "internal/agent/sandbox/bash.go"},
	{"view_image", false, "internal/agent/sandbox/view_image.go"},
	{"notify", false, "internal/notify/tool.go"},
	{"goal_control", false, "internal/goal/executor.go"},
	{"code", false, "pkg/agent/code_strategy.go"},

	{"goal_cancel", true, "internal/goal/tool_gen.go"},
	{"goal_create", true, "internal/goal/tool_gen.go"},
	{"goal_get", true, "internal/goal/tool_gen.go"},
	{"goal_list", true, "internal/goal/tool_gen.go"},
	{"scheduler_job_create", true, "internal/scheduler/tool_gen.go"},
	{"scheduler_job_delete", true, "internal/scheduler/tool_gen.go"},
	{"scheduler_job_get", true, "internal/scheduler/tool_gen.go"},
	{"scheduler_job_list", true, "internal/scheduler/tool_gen.go"},
	{"scheduler_job_pause", true, "internal/scheduler/tool_gen.go"},
	{"scheduler_job_resume", true, "internal/scheduler/tool_gen.go"},
	{"scheduler_job_update", true, "internal/scheduler/tool_gen.go"},
	{"workflow_get", true, "internal/workflow/tool_gen.go"},
	{"workflow_list", true, "internal/workflow/tool_gen.go"},
	{"workflow_run", true, "internal/workflow/tool_gen.go"},
	{"workflow_save", true, "internal/workflow/tool_gen.go"},
	{"oauth_connect", true, "internal/connections/tool_gen.go"},
	{"oauth_disconnect", true, "internal/connections/tool_gen.go"},
	{"oauth_flow_status", true, "internal/connections/tool_gen.go"},
	{"oauth_list", true, "internal/connections/tool_gen.go"},
	{"email_account_list", true, "plugins/email/tool_email_gen.go"},
	{"email_message_list", true, "plugins/email/tool_email_gen.go"},
	{"email_message_read", true, "plugins/email/tool_email_gen.go"},
	{"email_message_send", true, "plugins/email/tool_email_gen.go"},
	{"share_create_article", true, "internal/share/tool_gen.go"},
	{"share_create_artifact", true, "internal/share/tool_gen.go"},
	{"share_list", true, "internal/share/tool_gen.go"},
	{"share_revoke", true, "internal/share/tool_gen.go"},
	{"vault_secret_delete", true, "internal/vault/tool_gen.go"},
	{"vault_secret_list", true, "internal/vault/tool_gen.go"},
	{"vault_secret_set", true, "internal/vault/tool_gen.go"},
	{"recally_article_get", true, "internal/library/recally/tool_gen.go"},
	{"recally_article_list", true, "internal/library/recally/tool_gen.go"},
	{"recally_article_save", true, "internal/library/recally/tool_gen.go"},
	{"recally_digest_get", true, "internal/library/recally/tool_gen.go"},
	{"recally_digest_save", true, "internal/library/recally/tool_gen.go"},
	{"recally_entry_add", true, "internal/library/recally/tool_gen.go"},
	{"recally_entry_list", true, "internal/library/recally/tool_gen.go"},
	{"recally_entry_update", true, "internal/library/recally/tool_gen.go"},
	{"recally_feed_add", true, "internal/library/recally/tool_gen.go"},
	{"recally_feed_list", true, "internal/library/recally/tool_gen.go"},
	{"recally_feed_poll", true, "internal/library/recally/tool_gen.go"},
	{"recally_feed_remove", true, "internal/library/recally/tool_gen.go"},
	{"session_create", true, "internal/agent/session/access/tool_gen.go"},
	{"session_get", true, "internal/agent/session/access/tool_gen.go"},
	{"session_list", true, "internal/agent/session/access/tool_gen.go"},
	{"session_send", true, "internal/agent/session/access/tool_gen.go"},
	{"skill_installed_search", true, "internal/skill/tool_gen.go"},
	{"skill_load", true, "internal/skill/tool_gen.go"},
	{"library_search", true, "internal/library/tool_gen.go"},
	{"memory_read", true, "internal/memory/tool_gen.go"},
	{"memory_search", true, "internal/memory/tool_gen.go"},
	{"settings_agent_list", true, "internal/agent/tool_settings_agent_gen.go"},
	{"settings_agent_get", true, "internal/agent/tool_settings_agent_gen.go"},
	{"settings_agent_create", true, "internal/agent/tool_settings_agent_gen.go"},
	{"settings_agent_update", true, "internal/agent/tool_settings_agent_gen.go"},
	{"settings_agent_delete", true, "internal/agent/tool_settings_agent_gen.go"},
	{"settings_agent_tool_list", true, "internal/agent/tool_settings_agent_tool_gen.go"},
	{"settings_agent_tool_update", true, "internal/agent/tool_settings_agent_tool_gen.go"},
	{"settings_agent_tool_delete", true, "internal/agent/tool_settings_agent_tool_gen.go"},
	{"settings_library_file_list", true, "internal/library/tool_settings_library_gen.go"},
	{"settings_library_file_get", true, "internal/library/tool_settings_library_gen.go"},
	{"settings_library_file_upload", true, "internal/library/tool_settings_library_gen.go"},
	{"settings_library_file_delete", true, "internal/library/tool_settings_library_gen.go"},
	{"settings_skill_list", true, "internal/skill/tool_settings_skill_gen.go"},
	{"settings_skill_get", true, "internal/skill/tool_settings_skill_gen.go"},
	{"settings_skill_create", true, "internal/skill/tool_settings_skill_gen.go"},
	{"settings_skill_update", true, "internal/skill/tool_settings_skill_gen.go"},
	{"settings_skill_delete", true, "internal/skill/tool_settings_skill_gen.go"},
	{"settings_provider_list", true, "internal/controlplane/tool_settings_provider_gen.go"},
	{"settings_provider_get", true, "internal/controlplane/tool_settings_provider_gen.go"},
	{"settings_provider_create", true, "internal/controlplane/tool_settings_provider_gen.go"},
	{"settings_provider_update", true, "internal/controlplane/tool_settings_provider_gen.go"},
	{"settings_provider_delete", true, "internal/controlplane/tool_settings_provider_gen.go"},
	{"settings_default_model_get", true, "internal/controlplane/tool_settings_default_model_gen.go"},
	{"settings_default_model_update", true, "internal/controlplane/tool_settings_default_model_gen.go"},
	{"settings_embedding_setting_get", true, "internal/controlplane/tool_settings_embedding_setting_gen.go"},
	{"settings_embedding_setting_update", true, "internal/controlplane/tool_settings_embedding_setting_gen.go"},
	{"settings_plugin_list", true, "internal/controlplane/tool_settings_plugin_gen.go"},
	{"settings_plugin_enable", true, "internal/controlplane/tool_settings_plugin_gen.go"},
	{"settings_plugin_disable", true, "internal/controlplane/tool_settings_plugin_gen.go"},
	{"settings_mcp_server_list", true, "internal/mcp/tool_settings_mcp_gen.go"},
	{"settings_mcp_server_get", true, "internal/mcp/tool_settings_mcp_gen.go"},
	{"settings_mcp_server_create", true, "internal/mcp/tool_settings_mcp_gen.go"},
	{"settings_mcp_server_update", true, "internal/mcp/tool_settings_mcp_gen.go"},
	{"settings_mcp_server_delete", true, "internal/mcp/tool_settings_mcp_gen.go"},
	{"settings_mcp_server_probe", true, "internal/mcp/tool_settings_mcp_gen.go"},
}

func TestEveryBuiltinIsGeneratedOrAnAcceptedException(t *testing.T) {
	for _, tool := range builtinInventory {
		if got := HandWritten(tool.name); got == tool.generated {
			if tool.generated {
				t.Errorf("HandWritten(%q) = true, but %s generates it", tool.name, tool.source)
				continue
			}
			t.Errorf("HandWritten(%q) = false, but %s hand-writes it: generate it, or add it to handWritten with a reason", tool.name, tool.source)
		}
	}
}

// The exception lists are closed, and the closure is the point: HandWritten
// must not quietly grow a second mechanism now that pendingSplit is gone.
// Update these literals in the same commit that changes the maps, so the diff
// shows what was accepted.
func TestExceptionListsAreExactlyWhatTheRuleDocuments(t *testing.T) {
	assertKeys(t, "handWritten", handWritten, []string{"bash", "code", "goal_control", "notify", "view_image"})
}

func assertKeys(t *testing.T, label string, set map[string]bool, want []string) {
	t.Helper()
	got := make([]string, 0, len(set))
	for name := range set {
		got = append(got, name)
	}
	slices.Sort(got)
	if !slices.Equal(got, want) {
		t.Errorf("%s=%v, want exactly %v (see rules/agent-tools.md §2)", label, got, want)
	}
}
