/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppSchedulerRouteImport } from './routes/_app/scheduler'
import { Route as AppRecallyRouteImport } from './routes/_app/recally'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks.$taskId'
import { Route as AppSettingsWebhooksRouteImport } from './routes/_app/settings/webhooks'
import { Route as AppSettingsVisionRouteImport } from './routes/_app/settings/vision'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSettingsSkillsRouteImport } from './routes/_app/settings/skills'
import { Route as AppSettingsProvisioningRouteImport } from './routes/_app/settings/provisioning'
import { Route as AppSettingsProvidersRouteImport } from './routes/_app/settings/providers'
import { Route as AppSettingsPluginsRouteImport } from './routes/_app/settings/plugins'
import { Route as AppSettingsMcpRouteImport } from './routes/_app/settings/mcp'
import { Route as AppSettingsLibraryRouteImport } from './routes/_app/settings/library'
import { Route as AppSettingsEmbeddingRouteImport } from './routes/_app/settings/embedding'
import { Route as AppSettingsCredentialsRouteImport } from './routes/_app/settings/credentials'
import { Route as AppSettingsChannelsRouteImport } from './routes/_app/settings/channels'
import { Route as AppSettingsAgentsRouteImport } from './routes/_app/settings/agents'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsAboutRouteImport } from './routes/_app/settings/about'
import { Route as AppSessionsSplatRouteImport } from './routes/_app/sessions.$'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups.$groupId'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app/agents.$agentId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminOverviewRouteImport } from './routes/_app/admin/overview'
import { Route as AppSettingsPluginsIndexRouteImport } from './routes/_app/settings/plugins.index'
import { Route as AppAgentsAgentIdIndexRouteImport } from './routes/_app/agents.$agentId/index'
import { Route as AppSettingsUsersUserIdRouteImport } from './routes/_app/settings/users.$userId'
import { Route as AppSettingsProvidersProviderIdRouteImport } from './routes/_app/settings/providers.$providerId'
import { Route as AppSettingsPluginsPluginIdRouteImport } from './routes/_app/settings/plugins.$pluginId'
import { Route as AppSettingsCredentialsSectionRouteImport } from './routes/_app/settings/credentials.$section'
import { Route as AppSettingsChannelsChannelIdRouteImport } from './routes/_app/settings/channels.$channelId'
import { Route as AppSettingsAgentsAgentIdRouteImport } from './routes/_app/settings/agents.$agentId'
import { Route as AppAgentsAgentIdThreadsRouteImport } from './routes/_app/agents.$agentId/threads'
import { Route as AppAgentsAgentIdProfileRouteImport } from './routes/_app/agents.$agentId/profile'
import { Route as AppAgentsAgentIdMemoriesRouteImport } from './routes/_app/agents.$agentId/memories'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users.$userId'
import { Route as AppAdminResourcesSkillsRouteImport } from './routes/_app/admin/resources/skills'
import { Route as AppAdminResourcesMcpRouteImport } from './routes/_app/admin/resources/mcp'
import { Route as AppAdminResourcesLibraryRouteImport } from './routes/_app/admin/resources/library'
import { Route as AppAdminResourcesCredentialsRouteImport } from './routes/_app/admin/resources/credentials'
import { Route as AppAdminIntegrationsPluginsRouteImport } from './routes/_app/admin/integrations/plugins'
import { Route as AppAdminAiVisionRouteImport } from './routes/_app/admin/ai/vision'
import { Route as AppAdminAiProvidersRouteImport } from './routes/_app/admin/ai/providers'
import { Route as AppAdminAiModelsRouteImport } from './routes/_app/admin/ai/models'
import { Route as AppAdminAiEmbeddingRouteImport } from './routes/_app/admin/ai/embedding'
import { Route as AppAdminAccessProvisioningRouteImport } from './routes/_app/admin/access/provisioning'
import { Route as AppAgentsAgentIdWorkflowsIndexRouteImport } from './routes/_app/agents.$agentId/workflows/index'
import { Route as AppAgentsAgentIdSkillsIndexRouteImport } from './routes/_app/agents.$agentId/skills/index'
import { Route as AppAgentsAgentIdLibraryIndexRouteImport } from './routes/_app/agents.$agentId/library/index'
import { Route as AppAgentsAgentIdGoalsIndexRouteImport } from './routes/_app/agents.$agentId/goals/index'
import { Route as AppSettingsAgentsAgentIdTabRouteImport } from './routes/_app/settings/agents.$agentId.$tab'
import { Route as AppAgentsAgentIdWorkflowsWorkflowIdRouteImport } from './routes/_app/agents.$agentId/workflows/$workflowId'
import { Route as AppAgentsAgentIdSkillsSkillIdRouteImport } from './routes/_app/agents.$agentId/skills/$skillId'
import { Route as AppAgentsAgentIdSessionsSessionIdRouteImport } from './routes/_app/agents.$agentId/sessions.$sessionId'
import { Route as AppAgentsAgentIdGoalsNewRouteImport } from './routes/_app/agents.$agentId/goals/new'
import { Route as AppAgentsAgentIdGoalsAllRouteImport } from './routes/_app/agents.$agentId/goals/all'
import { Route as AppAgentsAgentIdGoalsGoalIdRouteImport } from './routes/_app/agents.$agentId/goals/$goalId'
import { Route as AppAdminIntegrationsPluginsPluginIdRouteImport } from './routes/_app/admin/integrations/plugins.$pluginId'
import { Route as AppAdminAiProvidersProviderIdRouteImport } from './routes/_app/admin/ai/providers.$providerId'
import { Route as AppAgentsAgentIdProjectsProjectIdIndexRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/index'
import { Route as AppAgentsAgentIdSkillsScopeSkillIdRouteImport } from './routes/_app/agents.$agentId/skills/$scope.$skillId'
import { Route as AppAgentsAgentIdProjectsProjectIdTasksRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/tasks'
import { Route as AppAgentsAgentIdProjectsProjectIdProfileRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/profile'
import { Route as AppAgentsAgentIdProjectsProjectIdMemoriesRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/memories'
import { Route as AppAgentsAgentIdGoalsSchedulesScheduleIdRouteImport } from './routes/_app/agents.$agentId/goals/schedules.$scheduleId'
import { Route as AppAgentsAgentIdProjectsProjectIdSkillsIndexRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/skills/index'
import { Route as AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/sessions.$sessionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_app.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs/$.lazy').then((d) => d.Route))
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/settings.lazy').then((d) => d.Route))
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any)
const AppRecallyRoute = AppRecallyRouteImport.update({
  id: '/recally',
  path: '/recally',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/recally.lazy').then((d) => d.Route))
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/admin.lazy').then((d) => d.Route))
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.index.lazy').then((d) => d.Route),
)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppSettingsWebhooksRoute = AppSettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/webhooks.lazy').then((d) => d.Route),
)
const AppSettingsVisionRoute = AppSettingsVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/users.lazy').then((d) => d.Route),
)
const AppSettingsSkillsRoute = AppSettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/skills.lazy').then((d) => d.Route),
)
const AppSettingsProvisioningRoute = AppSettingsProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/provisioning.lazy').then((d) => d.Route),
)
const AppSettingsProvidersRoute = AppSettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/providers.lazy').then((d) => d.Route),
)
const AppSettingsPluginsRoute = AppSettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/plugins.lazy').then((d) => d.Route),
)
const AppSettingsMcpRoute = AppSettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/mcp.lazy').then((d) => d.Route),
)
const AppSettingsLibraryRoute = AppSettingsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/library.lazy').then((d) => d.Route),
)
const AppSettingsEmbeddingRoute = AppSettingsEmbeddingRouteImport.update({
  id: '/embedding',
  path: '/embedding',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCredentialsRoute = AppSettingsCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/credentials.lazy').then((d) => d.Route),
)
const AppSettingsChannelsRoute = AppSettingsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/channels.lazy').then((d) => d.Route),
)
const AppSettingsAgentsRoute = AppSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/agents.lazy').then((d) => d.Route),
)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/account.lazy').then((d) => d.Route),
)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/about.lazy').then((d) => d.Route),
)
const AppSessionsSplatRoute = AppSessionsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppSessionsRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/groups.$groupId.lazy').then((d) => d.Route),
)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAgentsRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.$agentId.lazy').then((d) => d.Route),
)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users.lazy').then((d) => d.Route),
)
const AppAdminOverviewRoute = AppAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/overview.lazy').then((d) => d.Route),
)
const AppSettingsPluginsIndexRoute = AppSettingsPluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsPluginsRoute,
} as any)
const AppAgentsAgentIdIndexRoute = AppAgentsAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsAgentIdRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.$agentId/index.lazy').then((d) => d.Route),
)
const AppSettingsUsersUserIdRoute = AppSettingsUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppSettingsUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/users.$userId.lazy').then((d) => d.Route),
)
const AppSettingsProvidersProviderIdRoute =
  AppSettingsProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AppSettingsProvidersRoute,
  } as any).lazy(() =>
    import('./routes/_app/settings/providers.$providerId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSettingsPluginsPluginIdRoute =
  AppSettingsPluginsPluginIdRouteImport.update({
    id: '/$pluginId',
    path: '/$pluginId',
    getParentRoute: () => AppSettingsPluginsRoute,
  } as any).lazy(() =>
    import('./routes/_app/settings/plugins.$pluginId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSettingsCredentialsSectionRoute =
  AppSettingsCredentialsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AppSettingsCredentialsRoute,
  } as any).lazy(() =>
    import('./routes/_app/settings/credentials.$section.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSettingsChannelsChannelIdRoute =
  AppSettingsChannelsChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AppSettingsChannelsRoute,
  } as any).lazy(() =>
    import('./routes/_app/settings/channels.$channelId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSettingsAgentsAgentIdRoute =
  AppSettingsAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AppSettingsAgentsRoute,
  } as any)
const AppAgentsAgentIdThreadsRoute = AppAgentsAgentIdThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AppAgentsAgentIdRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.$agentId/threads.lazy').then((d) => d.Route),
)
const AppAgentsAgentIdProfileRoute = AppAgentsAgentIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAgentsAgentIdRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.$agentId/profile.lazy').then((d) => d.Route),
)
const AppAgentsAgentIdMemoriesRoute =
  AppAgentsAgentIdMemoriesRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users.$userId.lazy').then((d) => d.Route),
)
const AppAdminResourcesSkillsRoute = AppAdminResourcesSkillsRouteImport.update({
  id: '/resources/skills',
  path: '/resources/skills',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/resources/skills.lazy').then((d) => d.Route),
)
const AppAdminResourcesMcpRoute = AppAdminResourcesMcpRouteImport.update({
  id: '/resources/mcp',
  path: '/resources/mcp',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/resources/mcp.lazy').then((d) => d.Route),
)
const AppAdminResourcesLibraryRoute =
  AppAdminResourcesLibraryRouteImport.update({
    id: '/resources/library',
    path: '/resources/library',
    getParentRoute: () => AppAdminRoute,
  } as any).lazy(() =>
    import('./routes/_app/admin/resources/library.lazy').then((d) => d.Route),
  )
const AppAdminResourcesCredentialsRoute =
  AppAdminResourcesCredentialsRouteImport.update({
    id: '/resources/credentials',
    path: '/resources/credentials',
    getParentRoute: () => AppAdminRoute,
  } as any).lazy(() =>
    import('./routes/_app/admin/resources/credentials.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAdminIntegrationsPluginsRoute =
  AppAdminIntegrationsPluginsRouteImport.update({
    id: '/integrations/plugins',
    path: '/integrations/plugins',
    getParentRoute: () => AppAdminRoute,
  } as any).lazy(() =>
    import('./routes/_app/admin/integrations/plugins.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAdminAiVisionRoute = AppAdminAiVisionRouteImport.update({
  id: '/ai/vision',
  path: '/ai/vision',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAiProvidersRoute = AppAdminAiProvidersRouteImport.update({
  id: '/ai/providers',
  path: '/ai/providers',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/ai/providers.lazy').then((d) => d.Route),
)
const AppAdminAiModelsRoute = AppAdminAiModelsRouteImport.update({
  id: '/ai/models',
  path: '/ai/models',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/ai/models.lazy').then((d) => d.Route),
)
const AppAdminAiEmbeddingRoute = AppAdminAiEmbeddingRouteImport.update({
  id: '/ai/embedding',
  path: '/ai/embedding',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAccessProvisioningRoute =
  AppAdminAccessProvisioningRouteImport.update({
    id: '/access/provisioning',
    path: '/access/provisioning',
    getParentRoute: () => AppAdminRoute,
  } as any).lazy(() =>
    import('./routes/_app/admin/access/provisioning.lazy').then((d) => d.Route),
  )
const AppAgentsAgentIdWorkflowsIndexRoute =
  AppAgentsAgentIdWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdSkillsIndexRoute =
  AppAgentsAgentIdSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdLibraryIndexRoute =
  AppAgentsAgentIdLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdGoalsIndexRoute =
  AppAgentsAgentIdGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/goals/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSettingsAgentsAgentIdTabRoute =
  AppSettingsAgentsAgentIdTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AppSettingsAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdWorkflowsWorkflowIdRoute =
  AppAgentsAgentIdWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/workflows/$workflowId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdSkillsSkillIdRoute =
  AppAgentsAgentIdSkillsSkillIdRouteImport.update({
    id: '/skills/$skillId',
    path: '/skills/$skillId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdSessionsSessionIdRoute =
  AppAgentsAgentIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/sessions.$sessionId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdGoalsNewRoute =
  AppAgentsAgentIdGoalsNewRouteImport.update({
    id: '/goals/new',
    path: '/goals/new',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/goals/new.lazy').then((d) => d.Route),
  )
const AppAgentsAgentIdGoalsAllRoute =
  AppAgentsAgentIdGoalsAllRouteImport.update({
    id: '/goals/all',
    path: '/goals/all',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/goals/all.lazy').then((d) => d.Route),
  )
const AppAgentsAgentIdGoalsGoalIdRoute =
  AppAgentsAgentIdGoalsGoalIdRouteImport.update({
    id: '/goals/$goalId',
    path: '/goals/$goalId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/goals/$goalId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAdminIntegrationsPluginsPluginIdRoute =
  AppAdminIntegrationsPluginsPluginIdRouteImport.update({
    id: '/$pluginId',
    path: '/$pluginId',
    getParentRoute: () => AppAdminIntegrationsPluginsRoute,
  } as any).lazy(() =>
    import('./routes/_app/admin/integrations/plugins.$pluginId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAdminAiProvidersProviderIdRoute =
  AppAdminAiProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AppAdminAiProvidersRoute,
  } as any).lazy(() =>
    import('./routes/_app/admin/ai/providers.$providerId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdProjectsProjectIdIndexRoute =
  AppAgentsAgentIdProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/projects.$projectId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdSkillsScopeSkillIdRoute =
  AppAgentsAgentIdSkillsScopeSkillIdRouteImport.update({
    id: '/skills/$scope/$skillId',
    path: '/skills/$scope/$skillId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdProjectsProjectIdTasksRoute =
  AppAgentsAgentIdProjectsProjectIdTasksRouteImport.update({
    id: '/projects/$projectId/tasks',
    path: '/projects/$projectId/tasks',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdProjectsProjectIdProfileRoute =
  AppAgentsAgentIdProjectsProjectIdProfileRouteImport.update({
    id: '/projects/$projectId/profile',
    path: '/projects/$projectId/profile',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/projects.$projectId/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdProjectsProjectIdMemoriesRoute =
  AppAgentsAgentIdProjectsProjectIdMemoriesRouteImport.update({
    id: '/projects/$projectId/memories',
    path: '/projects/$projectId/memories',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdGoalsSchedulesScheduleIdRoute =
  AppAgentsAgentIdGoalsSchedulesScheduleIdRouteImport.update({
    id: '/goals/schedules/$scheduleId',
    path: '/goals/schedules/$scheduleId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/goals/schedules.$scheduleId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute =
  AppAgentsAgentIdProjectsProjectIdSkillsIndexRouteImport.update({
    id: '/projects/$projectId/skills/',
    path: '/projects/$projectId/skills/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any)
const AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute =
  AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRouteImport.update({
    id: '/projects/$projectId/sessions/$sessionId',
    path: '/projects/$projectId/sessions/$sessionId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/projects.$projectId/sessions.$sessionId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agents': typeof AppAgentsRouteWithChildren
  '/inbox': typeof AppInboxRoute
  '/recally': typeof AppRecallyRoute
  '/scheduler': typeof AppSchedulerRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/s/$token': typeof STokenRoute
  '/admin/overview': typeof AppAdminOverviewRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/sessions/$': typeof AppSessionsSplatRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/agents': typeof AppSettingsAgentsRouteWithChildren
  '/settings/channels': typeof AppSettingsChannelsRouteWithChildren
  '/settings/credentials': typeof AppSettingsCredentialsRouteWithChildren
  '/settings/embedding': typeof AppSettingsEmbeddingRoute
  '/settings/library': typeof AppSettingsLibraryRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/plugins': typeof AppSettingsPluginsRouteWithChildren
  '/settings/providers': typeof AppSettingsProvidersRouteWithChildren
  '/settings/provisioning': typeof AppSettingsProvisioningRoute
  '/settings/skills': typeof AppSettingsSkillsRoute
  '/settings/users': typeof AppSettingsUsersRouteWithChildren
  '/settings/vision': typeof AppSettingsVisionRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/admin/access/provisioning': typeof AppAdminAccessProvisioningRoute
  '/admin/ai/embedding': typeof AppAdminAiEmbeddingRoute
  '/admin/ai/models': typeof AppAdminAiModelsRoute
  '/admin/ai/providers': typeof AppAdminAiProvidersRouteWithChildren
  '/admin/ai/vision': typeof AppAdminAiVisionRoute
  '/admin/integrations/plugins': typeof AppAdminIntegrationsPluginsRouteWithChildren
  '/admin/resources/credentials': typeof AppAdminResourcesCredentialsRoute
  '/admin/resources/library': typeof AppAdminResourcesLibraryRoute
  '/admin/resources/mcp': typeof AppAdminResourcesMcpRoute
  '/admin/resources/skills': typeof AppAdminResourcesSkillsRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/agents/$agentId/memories': typeof AppAgentsAgentIdMemoriesRoute
  '/agents/$agentId/profile': typeof AppAgentsAgentIdProfileRoute
  '/agents/$agentId/threads': typeof AppAgentsAgentIdThreadsRoute
  '/settings/agents/$agentId': typeof AppSettingsAgentsAgentIdRouteWithChildren
  '/settings/channels/$channelId': typeof AppSettingsChannelsChannelIdRoute
  '/settings/credentials/$section': typeof AppSettingsCredentialsSectionRoute
  '/settings/plugins/$pluginId': typeof AppSettingsPluginsPluginIdRoute
  '/settings/providers/$providerId': typeof AppSettingsProvidersProviderIdRoute
  '/settings/users/$userId': typeof AppSettingsUsersUserIdRoute
  '/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/settings/plugins/': typeof AppSettingsPluginsIndexRoute
  '/admin/ai/providers/$providerId': typeof AppAdminAiProvidersProviderIdRoute
  '/admin/integrations/plugins/$pluginId': typeof AppAdminIntegrationsPluginsPluginIdRoute
  '/agents/$agentId/goals/$goalId': typeof AppAgentsAgentIdGoalsGoalIdRoute
  '/agents/$agentId/goals/all': typeof AppAgentsAgentIdGoalsAllRoute
  '/agents/$agentId/goals/new': typeof AppAgentsAgentIdGoalsNewRoute
  '/agents/$agentId/sessions/$sessionId': typeof AppAgentsAgentIdSessionsSessionIdRoute
  '/agents/$agentId/skills/$skillId': typeof AppAgentsAgentIdSkillsSkillIdRoute
  '/agents/$agentId/workflows/$workflowId': typeof AppAgentsAgentIdWorkflowsWorkflowIdRoute
  '/settings/agents/$agentId/$tab': typeof AppSettingsAgentsAgentIdTabRoute
  '/agents/$agentId/goals/': typeof AppAgentsAgentIdGoalsIndexRoute
  '/agents/$agentId/library/': typeof AppAgentsAgentIdLibraryIndexRoute
  '/agents/$agentId/skills/': typeof AppAgentsAgentIdSkillsIndexRoute
  '/agents/$agentId/workflows/': typeof AppAgentsAgentIdWorkflowsIndexRoute
  '/agents/$agentId/goals/schedules/$scheduleId': typeof AppAgentsAgentIdGoalsSchedulesScheduleIdRoute
  '/agents/$agentId/projects/$projectId/memories': typeof AppAgentsAgentIdProjectsProjectIdMemoriesRoute
  '/agents/$agentId/projects/$projectId/profile': typeof AppAgentsAgentIdProjectsProjectIdProfileRoute
  '/agents/$agentId/projects/$projectId/tasks': typeof AppAgentsAgentIdProjectsProjectIdTasksRoute
  '/agents/$agentId/skills/$scope/$skillId': typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  '/agents/$agentId/projects/$projectId/': typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  '/agents/$agentId/projects/$projectId/sessions/$sessionId': typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
  '/agents/$agentId/projects/$projectId/skills/': typeof AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/inbox': typeof AppInboxRoute
  '/recally': typeof AppRecallyRoute
  '/scheduler': typeof AppSchedulerRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/tasks': typeof AppTasksRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/s/$token': typeof STokenRoute
  '/admin/overview': typeof AppAdminOverviewRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/sessions/$': typeof AppSessionsSplatRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/agents': typeof AppSettingsAgentsRouteWithChildren
  '/settings/channels': typeof AppSettingsChannelsRouteWithChildren
  '/settings/credentials': typeof AppSettingsCredentialsRouteWithChildren
  '/settings/embedding': typeof AppSettingsEmbeddingRoute
  '/settings/library': typeof AppSettingsLibraryRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/providers': typeof AppSettingsProvidersRouteWithChildren
  '/settings/provisioning': typeof AppSettingsProvisioningRoute
  '/settings/skills': typeof AppSettingsSkillsRoute
  '/settings/users': typeof AppSettingsUsersRouteWithChildren
  '/settings/vision': typeof AppSettingsVisionRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/agents': typeof AppAgentsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/admin/access/provisioning': typeof AppAdminAccessProvisioningRoute
  '/admin/ai/embedding': typeof AppAdminAiEmbeddingRoute
  '/admin/ai/models': typeof AppAdminAiModelsRoute
  '/admin/ai/providers': typeof AppAdminAiProvidersRouteWithChildren
  '/admin/ai/vision': typeof AppAdminAiVisionRoute
  '/admin/integrations/plugins': typeof AppAdminIntegrationsPluginsRouteWithChildren
  '/admin/resources/credentials': typeof AppAdminResourcesCredentialsRoute
  '/admin/resources/library': typeof AppAdminResourcesLibraryRoute
  '/admin/resources/mcp': typeof AppAdminResourcesMcpRoute
  '/admin/resources/skills': typeof AppAdminResourcesSkillsRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/agents/$agentId/memories': typeof AppAgentsAgentIdMemoriesRoute
  '/agents/$agentId/profile': typeof AppAgentsAgentIdProfileRoute
  '/agents/$agentId/threads': typeof AppAgentsAgentIdThreadsRoute
  '/settings/agents/$agentId': typeof AppSettingsAgentsAgentIdRouteWithChildren
  '/settings/channels/$channelId': typeof AppSettingsChannelsChannelIdRoute
  '/settings/credentials/$section': typeof AppSettingsCredentialsSectionRoute
  '/settings/plugins/$pluginId': typeof AppSettingsPluginsPluginIdRoute
  '/settings/providers/$providerId': typeof AppSettingsProvidersProviderIdRoute
  '/settings/users/$userId': typeof AppSettingsUsersUserIdRoute
  '/agents/$agentId': typeof AppAgentsAgentIdIndexRoute
  '/settings/plugins': typeof AppSettingsPluginsIndexRoute
  '/admin/ai/providers/$providerId': typeof AppAdminAiProvidersProviderIdRoute
  '/admin/integrations/plugins/$pluginId': typeof AppAdminIntegrationsPluginsPluginIdRoute
  '/agents/$agentId/goals/$goalId': typeof AppAgentsAgentIdGoalsGoalIdRoute
  '/agents/$agentId/goals/all': typeof AppAgentsAgentIdGoalsAllRoute
  '/agents/$agentId/goals/new': typeof AppAgentsAgentIdGoalsNewRoute
  '/agents/$agentId/sessions/$sessionId': typeof AppAgentsAgentIdSessionsSessionIdRoute
  '/agents/$agentId/skills/$skillId': typeof AppAgentsAgentIdSkillsSkillIdRoute
  '/agents/$agentId/workflows/$workflowId': typeof AppAgentsAgentIdWorkflowsWorkflowIdRoute
  '/settings/agents/$agentId/$tab': typeof AppSettingsAgentsAgentIdTabRoute
  '/agents/$agentId/goals': typeof AppAgentsAgentIdGoalsIndexRoute
  '/agents/$agentId/library': typeof AppAgentsAgentIdLibraryIndexRoute
  '/agents/$agentId/skills': typeof AppAgentsAgentIdSkillsIndexRoute
  '/agents/$agentId/workflows': typeof AppAgentsAgentIdWorkflowsIndexRoute
  '/agents/$agentId/goals/schedules/$scheduleId': typeof AppAgentsAgentIdGoalsSchedulesScheduleIdRoute
  '/agents/$agentId/projects/$projectId/memories': typeof AppAgentsAgentIdProjectsProjectIdMemoriesRoute
  '/agents/$agentId/projects/$projectId/profile': typeof AppAgentsAgentIdProjectsProjectIdProfileRoute
  '/agents/$agentId/projects/$projectId/tasks': typeof AppAgentsAgentIdProjectsProjectIdTasksRoute
  '/agents/$agentId/skills/$scope/$skillId': typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  '/agents/$agentId/projects/$projectId': typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  '/agents/$agentId/projects/$projectId/sessions/$sessionId': typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
  '/agents/$agentId/projects/$projectId/skills': typeof AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/agents': typeof AppAgentsRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/recally': typeof AppRecallyRoute
  '/_app/scheduler': typeof AppSchedulerRoute
  '/_app/sessions': typeof AppSessionsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/s/$token': typeof STokenRoute
  '/_app/admin/overview': typeof AppAdminOverviewRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/sessions/$': typeof AppSessionsSplatRoute
  '/_app/settings/about': typeof AppSettingsAboutRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/agents': typeof AppSettingsAgentsRouteWithChildren
  '/_app/settings/channels': typeof AppSettingsChannelsRouteWithChildren
  '/_app/settings/credentials': typeof AppSettingsCredentialsRouteWithChildren
  '/_app/settings/embedding': typeof AppSettingsEmbeddingRoute
  '/_app/settings/library': typeof AppSettingsLibraryRoute
  '/_app/settings/mcp': typeof AppSettingsMcpRoute
  '/_app/settings/plugins': typeof AppSettingsPluginsRouteWithChildren
  '/_app/settings/providers': typeof AppSettingsProvidersRouteWithChildren
  '/_app/settings/provisioning': typeof AppSettingsProvisioningRoute
  '/_app/settings/skills': typeof AppSettingsSkillsRoute
  '/_app/settings/users': typeof AppSettingsUsersRouteWithChildren
  '/_app/settings/vision': typeof AppSettingsVisionRoute
  '/_app/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/admin/access/provisioning': typeof AppAdminAccessProvisioningRoute
  '/_app/admin/ai/embedding': typeof AppAdminAiEmbeddingRoute
  '/_app/admin/ai/models': typeof AppAdminAiModelsRoute
  '/_app/admin/ai/providers': typeof AppAdminAiProvidersRouteWithChildren
  '/_app/admin/ai/vision': typeof AppAdminAiVisionRoute
  '/_app/admin/integrations/plugins': typeof AppAdminIntegrationsPluginsRouteWithChildren
  '/_app/admin/resources/credentials': typeof AppAdminResourcesCredentialsRoute
  '/_app/admin/resources/library': typeof AppAdminResourcesLibraryRoute
  '/_app/admin/resources/mcp': typeof AppAdminResourcesMcpRoute
  '/_app/admin/resources/skills': typeof AppAdminResourcesSkillsRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/agents/$agentId/memories': typeof AppAgentsAgentIdMemoriesRoute
  '/_app/agents/$agentId/profile': typeof AppAgentsAgentIdProfileRoute
  '/_app/agents/$agentId/threads': typeof AppAgentsAgentIdThreadsRoute
  '/_app/settings/agents/$agentId': typeof AppSettingsAgentsAgentIdRouteWithChildren
  '/_app/settings/channels/$channelId': typeof AppSettingsChannelsChannelIdRoute
  '/_app/settings/credentials/$section': typeof AppSettingsCredentialsSectionRoute
  '/_app/settings/plugins/$pluginId': typeof AppSettingsPluginsPluginIdRoute
  '/_app/settings/providers/$providerId': typeof AppSettingsProvidersProviderIdRoute
  '/_app/settings/users/$userId': typeof AppSettingsUsersUserIdRoute
  '/_app/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/_app/settings/plugins/': typeof AppSettingsPluginsIndexRoute
  '/_app/admin/ai/providers/$providerId': typeof AppAdminAiProvidersProviderIdRoute
  '/_app/admin/integrations/plugins/$pluginId': typeof AppAdminIntegrationsPluginsPluginIdRoute
  '/_app/agents/$agentId/goals/$goalId': typeof AppAgentsAgentIdGoalsGoalIdRoute
  '/_app/agents/$agentId/goals/all': typeof AppAgentsAgentIdGoalsAllRoute
  '/_app/agents/$agentId/goals/new': typeof AppAgentsAgentIdGoalsNewRoute
  '/_app/agents/$agentId/sessions/$sessionId': typeof AppAgentsAgentIdSessionsSessionIdRoute
  '/_app/agents/$agentId/skills/$skillId': typeof AppAgentsAgentIdSkillsSkillIdRoute
  '/_app/agents/$agentId/workflows/$workflowId': typeof AppAgentsAgentIdWorkflowsWorkflowIdRoute
  '/_app/settings/agents/$agentId/$tab': typeof AppSettingsAgentsAgentIdTabRoute
  '/_app/agents/$agentId/goals/': typeof AppAgentsAgentIdGoalsIndexRoute
  '/_app/agents/$agentId/library/': typeof AppAgentsAgentIdLibraryIndexRoute
  '/_app/agents/$agentId/skills/': typeof AppAgentsAgentIdSkillsIndexRoute
  '/_app/agents/$agentId/workflows/': typeof AppAgentsAgentIdWorkflowsIndexRoute
  '/_app/agents/$agentId/goals/schedules/$scheduleId': typeof AppAgentsAgentIdGoalsSchedulesScheduleIdRoute
  '/_app/agents/$agentId/projects/$projectId/memories': typeof AppAgentsAgentIdProjectsProjectIdMemoriesRoute
  '/_app/agents/$agentId/projects/$projectId/profile': typeof AppAgentsAgentIdProjectsProjectIdProfileRoute
  '/_app/agents/$agentId/projects/$projectId/tasks': typeof AppAgentsAgentIdProjectsProjectIdTasksRoute
  '/_app/agents/$agentId/skills/$scope/$skillId': typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  '/_app/agents/$agentId/projects/$projectId/': typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId': typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
  '/_app/agents/$agentId/projects/$projectId/skills/': typeof AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/inbox'
    | '/recally'
    | '/scheduler'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/docs/$'
    | '/s/$token'
    | '/admin/overview'
    | '/admin/users'
    | '/agents/$agentId'
    | '/groups/$groupId'
    | '/sessions/$'
    | '/settings/about'
    | '/settings/account'
    | '/settings/agents'
    | '/settings/channels'
    | '/settings/credentials'
    | '/settings/embedding'
    | '/settings/library'
    | '/settings/mcp'
    | '/settings/plugins'
    | '/settings/providers'
    | '/settings/provisioning'
    | '/settings/skills'
    | '/settings/users'
    | '/settings/vision'
    | '/settings/webhooks'
    | '/tasks/$taskId'
    | '/admin/'
    | '/agents/'
    | '/settings/'
    | '/admin/access/provisioning'
    | '/admin/ai/embedding'
    | '/admin/ai/models'
    | '/admin/ai/providers'
    | '/admin/ai/vision'
    | '/admin/integrations/plugins'
    | '/admin/resources/credentials'
    | '/admin/resources/library'
    | '/admin/resources/mcp'
    | '/admin/resources/skills'
    | '/admin/users/$userId'
    | '/agents/$agentId/memories'
    | '/agents/$agentId/profile'
    | '/agents/$agentId/threads'
    | '/settings/agents/$agentId'
    | '/settings/channels/$channelId'
    | '/settings/credentials/$section'
    | '/settings/plugins/$pluginId'
    | '/settings/providers/$providerId'
    | '/settings/users/$userId'
    | '/agents/$agentId/'
    | '/settings/plugins/'
    | '/admin/ai/providers/$providerId'
    | '/admin/integrations/plugins/$pluginId'
    | '/agents/$agentId/goals/$goalId'
    | '/agents/$agentId/goals/all'
    | '/agents/$agentId/goals/new'
    | '/agents/$agentId/sessions/$sessionId'
    | '/agents/$agentId/skills/$skillId'
    | '/agents/$agentId/workflows/$workflowId'
    | '/settings/agents/$agentId/$tab'
    | '/agents/$agentId/goals/'
    | '/agents/$agentId/library/'
    | '/agents/$agentId/skills/'
    | '/agents/$agentId/workflows/'
    | '/agents/$agentId/goals/schedules/$scheduleId'
    | '/agents/$agentId/projects/$projectId/memories'
    | '/agents/$agentId/projects/$projectId/profile'
    | '/agents/$agentId/projects/$projectId/tasks'
    | '/agents/$agentId/skills/$scope/$skillId'
    | '/agents/$agentId/projects/$projectId/'
    | '/agents/$agentId/projects/$projectId/sessions/$sessionId'
    | '/agents/$agentId/projects/$projectId/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/signup'
    | '/inbox'
    | '/recally'
    | '/scheduler'
    | '/sessions'
    | '/tasks'
    | '/docs/$'
    | '/s/$token'
    | '/admin/overview'
    | '/admin/users'
    | '/groups/$groupId'
    | '/sessions/$'
    | '/settings/about'
    | '/settings/account'
    | '/settings/agents'
    | '/settings/channels'
    | '/settings/credentials'
    | '/settings/embedding'
    | '/settings/library'
    | '/settings/mcp'
    | '/settings/providers'
    | '/settings/provisioning'
    | '/settings/skills'
    | '/settings/users'
    | '/settings/vision'
    | '/settings/webhooks'
    | '/tasks/$taskId'
    | '/admin'
    | '/agents'
    | '/settings'
    | '/admin/access/provisioning'
    | '/admin/ai/embedding'
    | '/admin/ai/models'
    | '/admin/ai/providers'
    | '/admin/ai/vision'
    | '/admin/integrations/plugins'
    | '/admin/resources/credentials'
    | '/admin/resources/library'
    | '/admin/resources/mcp'
    | '/admin/resources/skills'
    | '/admin/users/$userId'
    | '/agents/$agentId/memories'
    | '/agents/$agentId/profile'
    | '/agents/$agentId/threads'
    | '/settings/agents/$agentId'
    | '/settings/channels/$channelId'
    | '/settings/credentials/$section'
    | '/settings/plugins/$pluginId'
    | '/settings/providers/$providerId'
    | '/settings/users/$userId'
    | '/agents/$agentId'
    | '/settings/plugins'
    | '/admin/ai/providers/$providerId'
    | '/admin/integrations/plugins/$pluginId'
    | '/agents/$agentId/goals/$goalId'
    | '/agents/$agentId/goals/all'
    | '/agents/$agentId/goals/new'
    | '/agents/$agentId/sessions/$sessionId'
    | '/agents/$agentId/skills/$skillId'
    | '/agents/$agentId/workflows/$workflowId'
    | '/settings/agents/$agentId/$tab'
    | '/agents/$agentId/goals'
    | '/agents/$agentId/library'
    | '/agents/$agentId/skills'
    | '/agents/$agentId/workflows'
    | '/agents/$agentId/goals/schedules/$scheduleId'
    | '/agents/$agentId/projects/$projectId/memories'
    | '/agents/$agentId/projects/$projectId/profile'
    | '/agents/$agentId/projects/$projectId/tasks'
    | '/agents/$agentId/skills/$scope/$skillId'
    | '/agents/$agentId/projects/$projectId'
    | '/agents/$agentId/projects/$projectId/sessions/$sessionId'
    | '/agents/$agentId/projects/$projectId/skills'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/profile'
    | '/signup'
    | '/_app/admin'
    | '/_app/agents'
    | '/_app/inbox'
    | '/_app/recally'
    | '/_app/scheduler'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/tasks'
    | '/docs/$'
    | '/s/$token'
    | '/_app/admin/overview'
    | '/_app/admin/users'
    | '/_app/agents/$agentId'
    | '/_app/groups/$groupId'
    | '/_app/sessions/$'
    | '/_app/settings/about'
    | '/_app/settings/account'
    | '/_app/settings/agents'
    | '/_app/settings/channels'
    | '/_app/settings/credentials'
    | '/_app/settings/embedding'
    | '/_app/settings/library'
    | '/_app/settings/mcp'
    | '/_app/settings/plugins'
    | '/_app/settings/providers'
    | '/_app/settings/provisioning'
    | '/_app/settings/skills'
    | '/_app/settings/users'
    | '/_app/settings/vision'
    | '/_app/settings/webhooks'
    | '/_app/tasks/$taskId'
    | '/_app/admin/'
    | '/_app/agents/'
    | '/_app/settings/'
    | '/_app/admin/access/provisioning'
    | '/_app/admin/ai/embedding'
    | '/_app/admin/ai/models'
    | '/_app/admin/ai/providers'
    | '/_app/admin/ai/vision'
    | '/_app/admin/integrations/plugins'
    | '/_app/admin/resources/credentials'
    | '/_app/admin/resources/library'
    | '/_app/admin/resources/mcp'
    | '/_app/admin/resources/skills'
    | '/_app/admin/users/$userId'
    | '/_app/agents/$agentId/memories'
    | '/_app/agents/$agentId/profile'
    | '/_app/agents/$agentId/threads'
    | '/_app/settings/agents/$agentId'
    | '/_app/settings/channels/$channelId'
    | '/_app/settings/credentials/$section'
    | '/_app/settings/plugins/$pluginId'
    | '/_app/settings/providers/$providerId'
    | '/_app/settings/users/$userId'
    | '/_app/agents/$agentId/'
    | '/_app/settings/plugins/'
    | '/_app/admin/ai/providers/$providerId'
    | '/_app/admin/integrations/plugins/$pluginId'
    | '/_app/agents/$agentId/goals/$goalId'
    | '/_app/agents/$agentId/goals/all'
    | '/_app/agents/$agentId/goals/new'
    | '/_app/agents/$agentId/sessions/$sessionId'
    | '/_app/agents/$agentId/skills/$skillId'
    | '/_app/agents/$agentId/workflows/$workflowId'
    | '/_app/settings/agents/$agentId/$tab'
    | '/_app/agents/$agentId/goals/'
    | '/_app/agents/$agentId/library/'
    | '/_app/agents/$agentId/skills/'
    | '/_app/agents/$agentId/workflows/'
    | '/_app/agents/$agentId/goals/schedules/$scheduleId'
    | '/_app/agents/$agentId/projects/$projectId/memories'
    | '/_app/agents/$agentId/projects/$projectId/profile'
    | '/_app/agents/$agentId/projects/$projectId/tasks'
    | '/_app/agents/$agentId/skills/$scope/$skillId'
    | '/_app/agents/$agentId/projects/$projectId/'
    | '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId'
    | '/_app/agents/$agentId/projects/$projectId/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  DocsSplatRoute: typeof DocsSplatRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduler': {
      id: '/_app/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recally': {
      id: '/_app/recally'
      path: '/recally'
      fullPath: '/recally'
      preLoaderRoute: typeof AppRecallyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/settings/webhooks': {
      id: '/_app/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AppSettingsWebhooksRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/vision': {
      id: '/_app/settings/vision'
      path: '/vision'
      fullPath: '/settings/vision'
      preLoaderRoute: typeof AppSettingsVisionRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/skills': {
      id: '/_app/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof AppSettingsSkillsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/provisioning': {
      id: '/_app/settings/provisioning'
      path: '/provisioning'
      fullPath: '/settings/provisioning'
      preLoaderRoute: typeof AppSettingsProvisioningRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/providers': {
      id: '/_app/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AppSettingsProvidersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/plugins': {
      id: '/_app/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AppSettingsPluginsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/mcp': {
      id: '/_app/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AppSettingsMcpRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/library': {
      id: '/_app/settings/library'
      path: '/library'
      fullPath: '/settings/library'
      preLoaderRoute: typeof AppSettingsLibraryRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/embedding': {
      id: '/_app/settings/embedding'
      path: '/embedding'
      fullPath: '/settings/embedding'
      preLoaderRoute: typeof AppSettingsEmbeddingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/credentials': {
      id: '/_app/settings/credentials'
      path: '/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof AppSettingsCredentialsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/channels': {
      id: '/_app/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof AppSettingsChannelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/agents': {
      id: '/_app/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof AppSettingsAgentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/about': {
      id: '/_app/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/sessions/$': {
      id: '/_app/sessions/$'
      path: '/$'
      fullPath: '/sessions/$'
      preLoaderRoute: typeof AppSessionsSplatRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/overview': {
      id: '/_app/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AppAdminOverviewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/settings/plugins/': {
      id: '/_app/settings/plugins/'
      path: '/'
      fullPath: '/settings/plugins/'
      preLoaderRoute: typeof AppSettingsPluginsIndexRouteImport
      parentRoute: typeof AppSettingsPluginsRoute
    }
    '/_app/agents/$agentId/': {
      id: '/_app/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AppAgentsAgentIdIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/settings/users/$userId': {
      id: '/_app/settings/users/$userId'
      path: '/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof AppSettingsUsersUserIdRouteImport
      parentRoute: typeof AppSettingsUsersRoute
    }
    '/_app/settings/providers/$providerId': {
      id: '/_app/settings/providers/$providerId'
      path: '/$providerId'
      fullPath: '/settings/providers/$providerId'
      preLoaderRoute: typeof AppSettingsProvidersProviderIdRouteImport
      parentRoute: typeof AppSettingsProvidersRoute
    }
    '/_app/settings/plugins/$pluginId': {
      id: '/_app/settings/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/settings/plugins/$pluginId'
      preLoaderRoute: typeof AppSettingsPluginsPluginIdRouteImport
      parentRoute: typeof AppSettingsPluginsRoute
    }
    '/_app/settings/credentials/$section': {
      id: '/_app/settings/credentials/$section'
      path: '/$section'
      fullPath: '/settings/credentials/$section'
      preLoaderRoute: typeof AppSettingsCredentialsSectionRouteImport
      parentRoute: typeof AppSettingsCredentialsRoute
    }
    '/_app/settings/channels/$channelId': {
      id: '/_app/settings/channels/$channelId'
      path: '/$channelId'
      fullPath: '/settings/channels/$channelId'
      preLoaderRoute: typeof AppSettingsChannelsChannelIdRouteImport
      parentRoute: typeof AppSettingsChannelsRoute
    }
    '/_app/settings/agents/$agentId': {
      id: '/_app/settings/agents/$agentId'
      path: '/$agentId'
      fullPath: '/settings/agents/$agentId'
      preLoaderRoute: typeof AppSettingsAgentsAgentIdRouteImport
      parentRoute: typeof AppSettingsAgentsRoute
    }
    '/_app/agents/$agentId/threads': {
      id: '/_app/agents/$agentId/threads'
      path: '/threads'
      fullPath: '/agents/$agentId/threads'
      preLoaderRoute: typeof AppAgentsAgentIdThreadsRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/profile': {
      id: '/_app/agents/$agentId/profile'
      path: '/profile'
      fullPath: '/agents/$agentId/profile'
      preLoaderRoute: typeof AppAgentsAgentIdProfileRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/memories': {
      id: '/_app/agents/$agentId/memories'
      path: '/memories'
      fullPath: '/agents/$agentId/memories'
      preLoaderRoute: typeof AppAgentsAgentIdMemoriesRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/resources/skills': {
      id: '/_app/admin/resources/skills'
      path: '/resources/skills'
      fullPath: '/admin/resources/skills'
      preLoaderRoute: typeof AppAdminResourcesSkillsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/resources/mcp': {
      id: '/_app/admin/resources/mcp'
      path: '/resources/mcp'
      fullPath: '/admin/resources/mcp'
      preLoaderRoute: typeof AppAdminResourcesMcpRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/resources/library': {
      id: '/_app/admin/resources/library'
      path: '/resources/library'
      fullPath: '/admin/resources/library'
      preLoaderRoute: typeof AppAdminResourcesLibraryRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/resources/credentials': {
      id: '/_app/admin/resources/credentials'
      path: '/resources/credentials'
      fullPath: '/admin/resources/credentials'
      preLoaderRoute: typeof AppAdminResourcesCredentialsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/integrations/plugins': {
      id: '/_app/admin/integrations/plugins'
      path: '/integrations/plugins'
      fullPath: '/admin/integrations/plugins'
      preLoaderRoute: typeof AppAdminIntegrationsPluginsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai/vision': {
      id: '/_app/admin/ai/vision'
      path: '/ai/vision'
      fullPath: '/admin/ai/vision'
      preLoaderRoute: typeof AppAdminAiVisionRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai/providers': {
      id: '/_app/admin/ai/providers'
      path: '/ai/providers'
      fullPath: '/admin/ai/providers'
      preLoaderRoute: typeof AppAdminAiProvidersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai/models': {
      id: '/_app/admin/ai/models'
      path: '/ai/models'
      fullPath: '/admin/ai/models'
      preLoaderRoute: typeof AppAdminAiModelsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai/embedding': {
      id: '/_app/admin/ai/embedding'
      path: '/ai/embedding'
      fullPath: '/admin/ai/embedding'
      preLoaderRoute: typeof AppAdminAiEmbeddingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/access/provisioning': {
      id: '/_app/admin/access/provisioning'
      path: '/access/provisioning'
      fullPath: '/admin/access/provisioning'
      preLoaderRoute: typeof AppAdminAccessProvisioningRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/agents/$agentId/workflows/': {
      id: '/_app/agents/$agentId/workflows/'
      path: '/workflows'
      fullPath: '/agents/$agentId/workflows/'
      preLoaderRoute: typeof AppAgentsAgentIdWorkflowsIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/skills/': {
      id: '/_app/agents/$agentId/skills/'
      path: '/skills'
      fullPath: '/agents/$agentId/skills/'
      preLoaderRoute: typeof AppAgentsAgentIdSkillsIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/library/': {
      id: '/_app/agents/$agentId/library/'
      path: '/library'
      fullPath: '/agents/$agentId/library/'
      preLoaderRoute: typeof AppAgentsAgentIdLibraryIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/goals/': {
      id: '/_app/agents/$agentId/goals/'
      path: '/goals'
      fullPath: '/agents/$agentId/goals/'
      preLoaderRoute: typeof AppAgentsAgentIdGoalsIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/settings/agents/$agentId/$tab': {
      id: '/_app/settings/agents/$agentId/$tab'
      path: '/$tab'
      fullPath: '/settings/agents/$agentId/$tab'
      preLoaderRoute: typeof AppSettingsAgentsAgentIdTabRouteImport
      parentRoute: typeof AppSettingsAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/workflows/$workflowId': {
      id: '/_app/agents/$agentId/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/agents/$agentId/workflows/$workflowId'
      preLoaderRoute: typeof AppAgentsAgentIdWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/skills/$skillId': {
      id: '/_app/agents/$agentId/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/agents/$agentId/skills/$skillId'
      preLoaderRoute: typeof AppAgentsAgentIdSkillsSkillIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/sessions/$sessionId': {
      id: '/_app/agents/$agentId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/agents/$agentId/sessions/$sessionId'
      preLoaderRoute: typeof AppAgentsAgentIdSessionsSessionIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/goals/new': {
      id: '/_app/agents/$agentId/goals/new'
      path: '/goals/new'
      fullPath: '/agents/$agentId/goals/new'
      preLoaderRoute: typeof AppAgentsAgentIdGoalsNewRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/goals/all': {
      id: '/_app/agents/$agentId/goals/all'
      path: '/goals/all'
      fullPath: '/agents/$agentId/goals/all'
      preLoaderRoute: typeof AppAgentsAgentIdGoalsAllRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/goals/$goalId': {
      id: '/_app/agents/$agentId/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/agents/$agentId/goals/$goalId'
      preLoaderRoute: typeof AppAgentsAgentIdGoalsGoalIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/admin/integrations/plugins/$pluginId': {
      id: '/_app/admin/integrations/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/admin/integrations/plugins/$pluginId'
      preLoaderRoute: typeof AppAdminIntegrationsPluginsPluginIdRouteImport
      parentRoute: typeof AppAdminIntegrationsPluginsRoute
    }
    '/_app/admin/ai/providers/$providerId': {
      id: '/_app/admin/ai/providers/$providerId'
      path: '/$providerId'
      fullPath: '/admin/ai/providers/$providerId'
      preLoaderRoute: typeof AppAdminAiProvidersProviderIdRouteImport
      parentRoute: typeof AppAdminAiProvidersRoute
    }
    '/_app/agents/$agentId/projects/$projectId/': {
      id: '/_app/agents/$agentId/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/agents/$agentId/projects/$projectId/'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/skills/$scope/$skillId': {
      id: '/_app/agents/$agentId/skills/$scope/$skillId'
      path: '/skills/$scope/$skillId'
      fullPath: '/agents/$agentId/skills/$scope/$skillId'
      preLoaderRoute: typeof AppAgentsAgentIdSkillsScopeSkillIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/projects/$projectId/tasks': {
      id: '/_app/agents/$agentId/projects/$projectId/tasks'
      path: '/projects/$projectId/tasks'
      fullPath: '/agents/$agentId/projects/$projectId/tasks'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/projects/$projectId/profile': {
      id: '/_app/agents/$agentId/projects/$projectId/profile'
      path: '/projects/$projectId/profile'
      fullPath: '/agents/$agentId/projects/$projectId/profile'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdProfileRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/projects/$projectId/memories': {
      id: '/_app/agents/$agentId/projects/$projectId/memories'
      path: '/projects/$projectId/memories'
      fullPath: '/agents/$agentId/projects/$projectId/memories'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdMemoriesRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/goals/schedules/$scheduleId': {
      id: '/_app/agents/$agentId/goals/schedules/$scheduleId'
      path: '/goals/schedules/$scheduleId'
      fullPath: '/agents/$agentId/goals/schedules/$scheduleId'
      preLoaderRoute: typeof AppAgentsAgentIdGoalsSchedulesScheduleIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/projects/$projectId/skills/': {
      id: '/_app/agents/$agentId/projects/$projectId/skills/'
      path: '/projects/$projectId/skills'
      fullPath: '/agents/$agentId/projects/$projectId/skills/'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdSkillsIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId': {
      id: '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId'
      path: '/projects/$projectId/sessions/$sessionId'
      fullPath: '/agents/$agentId/projects/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminAiProvidersRouteChildren {
  AppAdminAiProvidersProviderIdRoute: typeof AppAdminAiProvidersProviderIdRoute
}

const AppAdminAiProvidersRouteChildren: AppAdminAiProvidersRouteChildren = {
  AppAdminAiProvidersProviderIdRoute: AppAdminAiProvidersProviderIdRoute,
}

const AppAdminAiProvidersRouteWithChildren =
  AppAdminAiProvidersRoute._addFileChildren(AppAdminAiProvidersRouteChildren)

interface AppAdminIntegrationsPluginsRouteChildren {
  AppAdminIntegrationsPluginsPluginIdRoute: typeof AppAdminIntegrationsPluginsPluginIdRoute
}

const AppAdminIntegrationsPluginsRouteChildren: AppAdminIntegrationsPluginsRouteChildren =
  {
    AppAdminIntegrationsPluginsPluginIdRoute:
      AppAdminIntegrationsPluginsPluginIdRoute,
  }

const AppAdminIntegrationsPluginsRouteWithChildren =
  AppAdminIntegrationsPluginsRoute._addFileChildren(
    AppAdminIntegrationsPluginsRouteChildren,
  )

interface AppAdminRouteChildren {
  AppAdminOverviewRoute: typeof AppAdminOverviewRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminAccessProvisioningRoute: typeof AppAdminAccessProvisioningRoute
  AppAdminAiEmbeddingRoute: typeof AppAdminAiEmbeddingRoute
  AppAdminAiModelsRoute: typeof AppAdminAiModelsRoute
  AppAdminAiProvidersRoute: typeof AppAdminAiProvidersRouteWithChildren
  AppAdminAiVisionRoute: typeof AppAdminAiVisionRoute
  AppAdminIntegrationsPluginsRoute: typeof AppAdminIntegrationsPluginsRouteWithChildren
  AppAdminResourcesCredentialsRoute: typeof AppAdminResourcesCredentialsRoute
  AppAdminResourcesLibraryRoute: typeof AppAdminResourcesLibraryRoute
  AppAdminResourcesMcpRoute: typeof AppAdminResourcesMcpRoute
  AppAdminResourcesSkillsRoute: typeof AppAdminResourcesSkillsRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminOverviewRoute: AppAdminOverviewRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminAccessProvisioningRoute: AppAdminAccessProvisioningRoute,
  AppAdminAiEmbeddingRoute: AppAdminAiEmbeddingRoute,
  AppAdminAiModelsRoute: AppAdminAiModelsRoute,
  AppAdminAiProvidersRoute: AppAdminAiProvidersRouteWithChildren,
  AppAdminAiVisionRoute: AppAdminAiVisionRoute,
  AppAdminIntegrationsPluginsRoute:
    AppAdminIntegrationsPluginsRouteWithChildren,
  AppAdminResourcesCredentialsRoute: AppAdminResourcesCredentialsRoute,
  AppAdminResourcesLibraryRoute: AppAdminResourcesLibraryRoute,
  AppAdminResourcesMcpRoute: AppAdminResourcesMcpRoute,
  AppAdminResourcesSkillsRoute: AppAdminResourcesSkillsRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAgentsAgentIdRouteChildren {
  AppAgentsAgentIdMemoriesRoute: typeof AppAgentsAgentIdMemoriesRoute
  AppAgentsAgentIdProfileRoute: typeof AppAgentsAgentIdProfileRoute
  AppAgentsAgentIdThreadsRoute: typeof AppAgentsAgentIdThreadsRoute
  AppAgentsAgentIdIndexRoute: typeof AppAgentsAgentIdIndexRoute
  AppAgentsAgentIdGoalsGoalIdRoute: typeof AppAgentsAgentIdGoalsGoalIdRoute
  AppAgentsAgentIdGoalsAllRoute: typeof AppAgentsAgentIdGoalsAllRoute
  AppAgentsAgentIdGoalsNewRoute: typeof AppAgentsAgentIdGoalsNewRoute
  AppAgentsAgentIdSessionsSessionIdRoute: typeof AppAgentsAgentIdSessionsSessionIdRoute
  AppAgentsAgentIdSkillsSkillIdRoute: typeof AppAgentsAgentIdSkillsSkillIdRoute
  AppAgentsAgentIdWorkflowsWorkflowIdRoute: typeof AppAgentsAgentIdWorkflowsWorkflowIdRoute
  AppAgentsAgentIdGoalsIndexRoute: typeof AppAgentsAgentIdGoalsIndexRoute
  AppAgentsAgentIdLibraryIndexRoute: typeof AppAgentsAgentIdLibraryIndexRoute
  AppAgentsAgentIdSkillsIndexRoute: typeof AppAgentsAgentIdSkillsIndexRoute
  AppAgentsAgentIdWorkflowsIndexRoute: typeof AppAgentsAgentIdWorkflowsIndexRoute
  AppAgentsAgentIdGoalsSchedulesScheduleIdRoute: typeof AppAgentsAgentIdGoalsSchedulesScheduleIdRoute
  AppAgentsAgentIdProjectsProjectIdMemoriesRoute: typeof AppAgentsAgentIdProjectsProjectIdMemoriesRoute
  AppAgentsAgentIdProjectsProjectIdProfileRoute: typeof AppAgentsAgentIdProjectsProjectIdProfileRoute
  AppAgentsAgentIdProjectsProjectIdTasksRoute: typeof AppAgentsAgentIdProjectsProjectIdTasksRoute
  AppAgentsAgentIdSkillsScopeSkillIdRoute: typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  AppAgentsAgentIdProjectsProjectIdIndexRoute: typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute: typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
  AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute: typeof AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute
}

const AppAgentsAgentIdRouteChildren: AppAgentsAgentIdRouteChildren = {
  AppAgentsAgentIdMemoriesRoute: AppAgentsAgentIdMemoriesRoute,
  AppAgentsAgentIdProfileRoute: AppAgentsAgentIdProfileRoute,
  AppAgentsAgentIdThreadsRoute: AppAgentsAgentIdThreadsRoute,
  AppAgentsAgentIdIndexRoute: AppAgentsAgentIdIndexRoute,
  AppAgentsAgentIdGoalsGoalIdRoute: AppAgentsAgentIdGoalsGoalIdRoute,
  AppAgentsAgentIdGoalsAllRoute: AppAgentsAgentIdGoalsAllRoute,
  AppAgentsAgentIdGoalsNewRoute: AppAgentsAgentIdGoalsNewRoute,
  AppAgentsAgentIdSessionsSessionIdRoute:
    AppAgentsAgentIdSessionsSessionIdRoute,
  AppAgentsAgentIdSkillsSkillIdRoute: AppAgentsAgentIdSkillsSkillIdRoute,
  AppAgentsAgentIdWorkflowsWorkflowIdRoute:
    AppAgentsAgentIdWorkflowsWorkflowIdRoute,
  AppAgentsAgentIdGoalsIndexRoute: AppAgentsAgentIdGoalsIndexRoute,
  AppAgentsAgentIdLibraryIndexRoute: AppAgentsAgentIdLibraryIndexRoute,
  AppAgentsAgentIdSkillsIndexRoute: AppAgentsAgentIdSkillsIndexRoute,
  AppAgentsAgentIdWorkflowsIndexRoute: AppAgentsAgentIdWorkflowsIndexRoute,
  AppAgentsAgentIdGoalsSchedulesScheduleIdRoute:
    AppAgentsAgentIdGoalsSchedulesScheduleIdRoute,
  AppAgentsAgentIdProjectsProjectIdMemoriesRoute:
    AppAgentsAgentIdProjectsProjectIdMemoriesRoute,
  AppAgentsAgentIdProjectsProjectIdProfileRoute:
    AppAgentsAgentIdProjectsProjectIdProfileRoute,
  AppAgentsAgentIdProjectsProjectIdTasksRoute:
    AppAgentsAgentIdProjectsProjectIdTasksRoute,
  AppAgentsAgentIdSkillsScopeSkillIdRoute:
    AppAgentsAgentIdSkillsScopeSkillIdRoute,
  AppAgentsAgentIdProjectsProjectIdIndexRoute:
    AppAgentsAgentIdProjectsProjectIdIndexRoute,
  AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute:
    AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute,
  AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute:
    AppAgentsAgentIdProjectsProjectIdSkillsIndexRoute,
}

const AppAgentsAgentIdRouteWithChildren =
  AppAgentsAgentIdRoute._addFileChildren(AppAgentsAgentIdRouteChildren)

interface AppAgentsRouteChildren {
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRouteWithChildren
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsAgentIdRoute: AppAgentsAgentIdRouteWithChildren,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppSessionsRouteChildren {
  AppSessionsSplatRoute: typeof AppSessionsSplatRoute
}

const AppSessionsRouteChildren: AppSessionsRouteChildren = {
  AppSessionsSplatRoute: AppSessionsSplatRoute,
}

const AppSessionsRouteWithChildren = AppSessionsRoute._addFileChildren(
  AppSessionsRouteChildren,
)

interface AppSettingsAgentsAgentIdRouteChildren {
  AppSettingsAgentsAgentIdTabRoute: typeof AppSettingsAgentsAgentIdTabRoute
}

const AppSettingsAgentsAgentIdRouteChildren: AppSettingsAgentsAgentIdRouteChildren =
  {
    AppSettingsAgentsAgentIdTabRoute: AppSettingsAgentsAgentIdTabRoute,
  }

const AppSettingsAgentsAgentIdRouteWithChildren =
  AppSettingsAgentsAgentIdRoute._addFileChildren(
    AppSettingsAgentsAgentIdRouteChildren,
  )

interface AppSettingsAgentsRouteChildren {
  AppSettingsAgentsAgentIdRoute: typeof AppSettingsAgentsAgentIdRouteWithChildren
}

const AppSettingsAgentsRouteChildren: AppSettingsAgentsRouteChildren = {
  AppSettingsAgentsAgentIdRoute: AppSettingsAgentsAgentIdRouteWithChildren,
}

const AppSettingsAgentsRouteWithChildren =
  AppSettingsAgentsRoute._addFileChildren(AppSettingsAgentsRouteChildren)

interface AppSettingsChannelsRouteChildren {
  AppSettingsChannelsChannelIdRoute: typeof AppSettingsChannelsChannelIdRoute
}

const AppSettingsChannelsRouteChildren: AppSettingsChannelsRouteChildren = {
  AppSettingsChannelsChannelIdRoute: AppSettingsChannelsChannelIdRoute,
}

const AppSettingsChannelsRouteWithChildren =
  AppSettingsChannelsRoute._addFileChildren(AppSettingsChannelsRouteChildren)

interface AppSettingsCredentialsRouteChildren {
  AppSettingsCredentialsSectionRoute: typeof AppSettingsCredentialsSectionRoute
}

const AppSettingsCredentialsRouteChildren: AppSettingsCredentialsRouteChildren =
  {
    AppSettingsCredentialsSectionRoute: AppSettingsCredentialsSectionRoute,
  }

const AppSettingsCredentialsRouteWithChildren =
  AppSettingsCredentialsRoute._addFileChildren(
    AppSettingsCredentialsRouteChildren,
  )

interface AppSettingsPluginsRouteChildren {
  AppSettingsPluginsPluginIdRoute: typeof AppSettingsPluginsPluginIdRoute
  AppSettingsPluginsIndexRoute: typeof AppSettingsPluginsIndexRoute
}

const AppSettingsPluginsRouteChildren: AppSettingsPluginsRouteChildren = {
  AppSettingsPluginsPluginIdRoute: AppSettingsPluginsPluginIdRoute,
  AppSettingsPluginsIndexRoute: AppSettingsPluginsIndexRoute,
}

const AppSettingsPluginsRouteWithChildren =
  AppSettingsPluginsRoute._addFileChildren(AppSettingsPluginsRouteChildren)

interface AppSettingsProvidersRouteChildren {
  AppSettingsProvidersProviderIdRoute: typeof AppSettingsProvidersProviderIdRoute
}

const AppSettingsProvidersRouteChildren: AppSettingsProvidersRouteChildren = {
  AppSettingsProvidersProviderIdRoute: AppSettingsProvidersProviderIdRoute,
}

const AppSettingsProvidersRouteWithChildren =
  AppSettingsProvidersRoute._addFileChildren(AppSettingsProvidersRouteChildren)

interface AppSettingsUsersRouteChildren {
  AppSettingsUsersUserIdRoute: typeof AppSettingsUsersUserIdRoute
}

const AppSettingsUsersRouteChildren: AppSettingsUsersRouteChildren = {
  AppSettingsUsersUserIdRoute: AppSettingsUsersUserIdRoute,
}

const AppSettingsUsersRouteWithChildren =
  AppSettingsUsersRoute._addFileChildren(AppSettingsUsersRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAgentsRoute: typeof AppSettingsAgentsRouteWithChildren
  AppSettingsChannelsRoute: typeof AppSettingsChannelsRouteWithChildren
  AppSettingsCredentialsRoute: typeof AppSettingsCredentialsRouteWithChildren
  AppSettingsEmbeddingRoute: typeof AppSettingsEmbeddingRoute
  AppSettingsLibraryRoute: typeof AppSettingsLibraryRoute
  AppSettingsMcpRoute: typeof AppSettingsMcpRoute
  AppSettingsPluginsRoute: typeof AppSettingsPluginsRouteWithChildren
  AppSettingsProvidersRoute: typeof AppSettingsProvidersRouteWithChildren
  AppSettingsProvisioningRoute: typeof AppSettingsProvisioningRoute
  AppSettingsSkillsRoute: typeof AppSettingsSkillsRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRouteWithChildren
  AppSettingsVisionRoute: typeof AppSettingsVisionRoute
  AppSettingsWebhooksRoute: typeof AppSettingsWebhooksRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAgentsRoute: AppSettingsAgentsRouteWithChildren,
  AppSettingsChannelsRoute: AppSettingsChannelsRouteWithChildren,
  AppSettingsCredentialsRoute: AppSettingsCredentialsRouteWithChildren,
  AppSettingsEmbeddingRoute: AppSettingsEmbeddingRoute,
  AppSettingsLibraryRoute: AppSettingsLibraryRoute,
  AppSettingsMcpRoute: AppSettingsMcpRoute,
  AppSettingsPluginsRoute: AppSettingsPluginsRouteWithChildren,
  AppSettingsProvidersRoute: AppSettingsProvidersRouteWithChildren,
  AppSettingsProvisioningRoute: AppSettingsProvisioningRoute,
  AppSettingsSkillsRoute: AppSettingsSkillsRoute,
  AppSettingsUsersRoute: AppSettingsUsersRouteWithChildren,
  AppSettingsVisionRoute: AppSettingsVisionRoute,
  AppSettingsWebhooksRoute: AppSettingsWebhooksRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppInboxRoute: typeof AppInboxRoute
  AppRecallyRoute: typeof AppRecallyRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppSessionsRoute: typeof AppSessionsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppInboxRoute: AppInboxRoute,
  AppRecallyRoute: AppRecallyRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppSessionsRoute: AppSessionsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  DocsSplatRoute: DocsSplatRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
